# Generated by Django 5.1.1 on 2025-03-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_aitranslationprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitranslationprocess',
            name='cost',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
