# Generated by Django 5.1.1 on 2025-03-20 14:56

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_delete_aipointcontentgenerateprocess'),
        ('core', '0003_multitenantcompany_ai_points'),
        ('llm', '0003_alter_aitranslationprocess_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aitranslationprocess',
            name='prompt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aigenerateprocess',
            name='cost',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.CreateModel(
            name='AiImportProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('result', models.TextField()),
                ('result_time', models.FloatField()),
                ('input_tokens', models.FloatField(blank=True, null=True)),
                ('output_tokens', models.FloatField(blank=True, null=True)),
                ('cached_tokens', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=8, max_digits=10)),
                ('type', models.CharField(choices=[('PROPERTY_TYPE_DETECTOR', 'Property Type Detector')],
                 default='PROPERTY_TYPE_DETECTOR', help_text='Type of AI import process.', max_length=50)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                 related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                 related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.aipointtransaction')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
