# Generated by Django 5.1.1 on 2025-03-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_aitranslationprocess_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiimportprocess',
            name='type',
            field=models.CharField(choices=[('PROPERTY_TYPE_DETECTOR', 'Property Type Detector'), ('IMPORTABLE_PROPERTIES_DETECTOR',
                                   'Detects Importable Properties')], default='PROPERTY_TYPE_DETECTOR', help_text='Type of AI import process.', max_length=50),
        ),
    ]
