# Generated by Django 5.2 on 2025-07-21 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_alter_brandcustomprompt_language'),
        ('properties', '0014_property_unique_internal_name_per_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandcustomprompt',
            unique_together={('brand_value', 'language')},
        ),
    ]
