# Generated by Django 5.2 on 2025-10-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0013_chatgptproductfeedconfig_units'),
        ('properties', '0017_alter_propertyselectvalue_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgptproductfeedconfig',
            old_name='gender_system_property',
            new_name='gender_property',
        ),
        migrations.AddField(
            model_name='chatgptproductfeedconfig',
            name='size_system_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='properties.property'),
        ),
    ]
