# Generated by Django 5.2 on 2025-10-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0014_rename_gender_system_property_chatgptproductfeedconfig_gender_property_and_more'),
        ('properties', '0017_alter_propertyselectvalue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptproductfeedconfig',
            name='gender_female_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='properties.propertyselectvalue'),
        ),
        migrations.AddField(
            model_name='chatgptproductfeedconfig',
            name='gender_male_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='properties.propertyselectvalue'),
        ),
        migrations.AddField(
            model_name='chatgptproductfeedconfig',
            name='gender_unisex_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='properties.propertyselectvalue'),
        ),
    ]
