# Generated by Django 5.2 on 2026-04-17 13:14

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0025_alter_export_language'),
        ('llm', '0017_alter_brandcustomprompt_language_mcpapikey'),
        ('sales_channels', '0088_remotedocumenttype_uploadable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpToolRun',
            fields=[
                ('import_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imports_exports.import')),
                ('tool_name', models.CharField(db_index=True, help_text='MCP tool name that created this run, for example create_products or upsert_products.', max_length=128)),
                ('payload_content', models.JSONField(blank=True, default=dict, help_text='Normalized MCP tool payload stored for traceability. Long values are truncated before saving.')),
                ('response_content', models.JSONField(blank=True, default=dict, help_text='Lean MCP tool response payload stored for traceability. Long values are truncated before saving.')),
                ('assigned_views', models.ManyToManyField(blank=True, help_text='Website/storefront views explicitly referenced by this MCP tool run, when applicable.', related_name='mcp_tool_runs', to='sales_channels.saleschannelview')),
            ],
            options={
                'verbose_name': 'MCP Tool Run',
                'verbose_name_plural': 'MCP Tool Runs',
                'ordering': ['-created_at'],
            },
            bases=('imports_exports.import', dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
    ]
