# Generated by Django 5.2 on 2026-04-21 12:27

from django.db import migrations


def delete_existing_mcp_api_keys(apps, schema_editor):
    McpApiKey = apps.get_model("llm", "McpApiKey")
    McpApiKey.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0018_mcptoolrun'),
    ]

    operations = [
        migrations.RunPython(delete_existing_mcp_api_keys, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='mcpapikey',
            name='multi_tenant_company',
        ),
    ]
