# Generated by Django 5.2 on 2026-04-21 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0019_remove_mcpapikey_multi_tenant_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpapikey',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_api_key', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
