# Generated by Django 4.2.5 on 2023-09-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_prices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesprice',
            old_name='company',
            new_name='multi_tenant_company',
        ),
        migrations.RenameField(
            model_name='salespricelist',
            old_name='company',
            new_name='multi_tenant_company',
        ),
        migrations.RenameField(
            model_name='salespricelistassign',
            old_name='company',
            new_name='multi_tenant_company',
        ),
        migrations.RenameField(
            model_name='salespricelistitem',
            old_name='company',
            new_name='multi_tenant_company',
        ),
    ]
