# Generated by Django 4.2.5 on 2023-09-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('units', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.unit'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.supplierproduct'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_address_set', to='contacts.shippingaddress'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_address_set', to='contacts.internalcompany'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.supplier'),
        ),
    ]
