# Generated by Django 4.2.5 on 2023-09-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('CONFIRMED', 'Confirmation Received'),
                                   ('PENDING_DELIVERY', 'Pending Delivery'), ('DELIVERED', 'Delivered')], default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorder'),
            preserve_default=False,
        ),
    ]
