# Generated by Django 4.2.6 on 2023-10-13 14:32

from django.db import migrations, models
import django.db.models.deletion
import core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=5)),
                ('video_url', models.URLField()),
                ('image_type', models.CharField(choices=[('MOOD', 'Mood Shot'), ('PACK', 'Pack Shot')], default='PACK', max_length=4)),
                ('image', models.ImageField(upload_to='images/', validators=[
                 core.validators.validate_image_extension], verbose_name='Image (High resolution)')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaProductThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.IntegerField(default=10)),
                ('is_main_image', models.BooleanField(default=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ('-is_main_image', 'sort_order'),
            },
        ),
        migrations.AddField(
            model_name='media',
            name='products',
            field=models.ManyToManyField(through='media.MediaProductThrough', to='products.product'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('media.media',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('media.media',),
        ),
    ]
