# Generated by Django 4.2.9 on 2024-02-20 15:30

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('media.media',),
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/',
                                   validators=[core.validators.validate_file_extensions, core.validators.no_dots_in_filename], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/',
                                    validators=[core.validators.validate_image_extension, core.validators.no_dots_in_filename], verbose_name='Image (High resolution)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File')], max_length=5),
        ),
        migrations.AlterField(
            model_name='media',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
