# Generated by Django 5.2.1 on 2025-05-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_type',
            field=models.CharField(choices=[('MOOD', 'Mood Shot'), ('PACK', 'Pack Shot')], default='PACK', max_length=5),
        ),
    ]
