# Generated by Django 5.2 on 2025-08-13 11:01

import core.upload_paths
import core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_media_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'depth': 3, 'segment_length': 2, 'subdir': 'files'}), validators=[core.validators.validate_file_extensions, core.validators.no_dots_in_filename], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'depth': 3, 'segment_length': 2, 'subdir': 'images'}), validators=[core.validators.validate_image_extension], verbose_name='Image (High resolution)'),
        ),
    ]
