# Generated by Django 5.2 on 2025-10-06 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_multitenantcompany_active_and_more'),
        ('media', '0007_auto_20250930_0953'),
        ('products', '0023_producttranslation_subtitle'),
        ('sales_channels', '0041_saleschannel_starting_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediaproductthrough',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mediaproductthrough',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_product_assignments', to='sales_channels.saleschannel'),
        ),
        migrations.AddConstraint(
            model_name='mediaproductthrough',
            constraint=models.UniqueConstraint(condition=models.Q(('sales_channel__isnull', True)), fields=('product', 'media'), name='media_product_unique_default_sales_channel'),
        ),
        migrations.AddConstraint(
            model_name='mediaproductthrough',
            constraint=models.UniqueConstraint(condition=models.Q(('sales_channel__isnull', False)), fields=('product', 'media', 'sales_channel'), name='media_product_unique_per_sales_channel'),
        ),
    ]
