# Generated by Django 5.1.1 on 2025-02-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_mediaproductthrough_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image hash'),
        ),
    ]
