# Generated by Django 5.2 on 2026-01-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_alter_mediaproductthrough_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_type',
            field=models.CharField(choices=[('MOOD', 'Mood Shot'), ('PACK', 'Pack Shot'), ('COLOR', 'Color Image')], default='PACK', max_length=5),
        ),
    ]
