# Generated by Django 5.1.1 on 2025-02-11 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_demodatarelation_created_by_multi_tenant_user_and_more'),
        ('media', '0009_remove_media_duplicates'),
        ('products', '0037_rename_supplierprices_supplierprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(condition=models.Q(('image_hash__isnull', False)), fields=('multi_tenant_company', 'image_hash'), name='unique_image_hash_per_tenant'),
        ),
    ]
