# Generated by Django 5.1.1 on 2025-02-11 11:19

from django.db import migrations, models

def remove_duplicate_media_entries(apps, schema_editor):
    MediaProductThrough = apps.get_model('media', 'MediaProductThrough')

    duplicates = (
        MediaProductThrough.objects
        .values('product', 'media')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
    )

    for duplicate in duplicates:
        product = duplicate['product']
        media = duplicate['media']

        entries = list(MediaProductThrough.objects.filter(product=product, media=media))

        # Keep the `is_main_image=True` entry if available, otherwise keep one randomly
        entries_to_keep = [entry for entry in entries if entry.is_main_image]

        if not entries_to_keep:
            entries_to_keep.append(entries[0])  # Keep at least one

        ids_to_keep = {entry.id for entry in entries_to_keep}
        MediaProductThrough.objects.filter(product=product, media=media).exclude(id__in=ids_to_keep).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_media_unique_image_hash_per_tenant'),
        ('products', '0037_rename_supplierprices_supplierprice'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_media_entries, atomic=False),
        migrations.AlterUniqueTogether(
            name='mediaproductthrough',
            unique_together={('product', 'media')},
        ),
    ]
