# Generated by Django 5.1.1 on 2025-02-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_media_unique_image_hash_per_tenant'),
        ('products', '0037_rename_supplierprices_supplierprice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediaproductthrough',
            unique_together={('product', 'media')},
        ),
    ]
