# Generated by Django 5.2 on 2026-02-20 15:18

import core.upload_paths
import core.validators
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('media', '0011_populate_internal_document_type'),
        ('products', '0023_producttranslation_subtitle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='document_image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'document_thumbnails'}), validators=[core.validators.validate_image_extension], verbose_name='Document image thumbnail'),
        ),
        migrations.AddField(
            model_name='media',
            name='is_document_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('is_document_image', False), models.Q(('image__isnull', False), ('type', 'FILE')), _connector='OR'), name='media_document_image_requires_image', violation_error_message='Document image media must be FILE type and include an image.'),
        ),
    ]
