# Generated by Django 5.2 on 2026-02-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_media_document_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
