# Generated by Django 5.2 on 2026-02-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_alter_documenttype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='original_url',
            field=models.URLField(blank=True, help_text='Original source URL used during imports, when available.', max_length=2048, null=True),
        ),
    ]
