from properties.models import Property

# the key is the original type in the remote property
# the values with Ture/False are the local types
REMOTE_PROPERTY_TYPE_CHANGE_RULES = {
    Property.TYPES.INT: {
        Property.TYPES.INT: True,
        Property.TYPES.FLOAT: True,
        Property.TYPES.TEXT: True,
        Property.TYPES.DESCRIPTION: True,
        Property.TYPES.BOOLEAN: False,
        Property.TYPES.DATE: False,
        Property.TYPES.DATETIME: False,
        Property.TYPES.SELECT: True,
        Property.TYPES.MULTISELECT: False,
    },
    Property.TYPES.FLOAT: {
        Property.TYPES.INT: True,
        Property.TYPES.FLOAT: True,
        Property.TYPES.TEXT: True,
        Property.TYPES.DESCRIPTION: True,
        Property.TYPES.BOOLEAN: False,
        Property.TYPES.DATE: False,
        Property.TYPES.DATETIME: False,
        Property.TYPES.SELECT: True,
        Property.TYPES.MULTISELECT: False,
    },
    Property.TYPES.TEXT: {
        Property.TYPES.INT: True,
        Property.TYPES.FLOAT: True,
        Property.TYPES.TEXT: True,
        Property.TYPES.DESCRIPTION: True,
        Property.TYPES.BOOLEAN: True,
        Property.TYPES.DATE: True,
        Property.TYPES.DATETIME: True,
        Property.TYPES.SELECT: True,
        Property.TYPES.MULTISELECT: True,
    },
    Property.TYPES.DESCRIPTION: {
        Property.TYPES.INT: True,
        Property.TYPES.FLOAT: True,
        Property.TYPES.TEXT: True,
        Property.TYPES.DESCRIPTION: True,
        Property.TYPES.BOOLEAN: True,
        Property.TYPES.DATE: True,
        Property.TYPES.DATETIME: True,
        Property.TYPES.SELECT: True,
        Property.TYPES.MULTISELECT: True,
    },
    Property.TYPES.BOOLEAN: {
        Property.TYPES.INT: False,
        Property.TYPES.FLOAT: False,
        Property.TYPES.TEXT: True,
        Property.TYPES.DESCRIPTION: True,
        Property.TYPES.BOOLEAN: True,
        Property.TYPES.DATE: False,
        Property.TYPES.DATETIME: False,
        Property.TYPES.SELECT: False,
        Property.TYPES.MULTISELECT: False,
    },
    Property.TYPES.DATE: {
        Property.TYPES.INT: False,
        Property.TYPES.FLOAT: False,
        Property.TYPES.TEXT: False,
        Property.TYPES.DESCRIPTION: False,
        Property.TYPES.BOOLEAN: False,
        Property.TYPES.DATE: True,
        Property.TYPES.DATETIME: True,
        Property.TYPES.SELECT: False,
        Property.TYPES.MULTISELECT: False,
    },
    Property.TYPES.DATETIME: {
        Property.TYPES.INT: False,
        Property.TYPES.FLOAT: False,
        Property.TYPES.TEXT: False,
        Property.TYPES.DESCRIPTION: False,
        Property.TYPES.BOOLEAN: False,
        Property.TYPES.DATE: True,
        Property.TYPES.DATETIME: True,
        Property.TYPES.SELECT: False,
        Property.TYPES.MULTISELECT: False,
    },
    "SELECT__allows_custom_values": {
        Property.TYPES.INT: True,
        Property.TYPES.FLOAT: True,
        Property.TYPES.TEXT: True,
        Property.TYPES.DESCRIPTION: True,
        Property.TYPES.BOOLEAN: True,
        Property.TYPES.DATE: True,
        Property.TYPES.DATETIME: True,
        Property.TYPES.SELECT: True,
        Property.TYPES.MULTISELECT: True,
    },
    "SELECT__not_allows_custom_values": {
        Property.TYPES.INT: False,
        Property.TYPES.FLOAT: False,
        Property.TYPES.TEXT: False,
        Property.TYPES.DESCRIPTION: False,
        Property.TYPES.BOOLEAN: True,
        Property.TYPES.DATE: False,
        Property.TYPES.DATETIME: False,
        Property.TYPES.SELECT: True,
        Property.TYPES.MULTISELECT: False,
    },
    "MULTISELECT__allows_custom_values": {
        Property.TYPES.INT: True,
        Property.TYPES.FLOAT: True,
        Property.TYPES.TEXT: True,
        Property.TYPES.DESCRIPTION: True,
        Property.TYPES.BOOLEAN: True,
        Property.TYPES.DATE: True,
        Property.TYPES.DATETIME: True,
        Property.TYPES.SELECT: True,
        Property.TYPES.MULTISELECT: True,
    },
    "MULTISELECT__not_allows_custom_values": {
        Property.TYPES.INT: False,
        Property.TYPES.FLOAT: False,
        Property.TYPES.TEXT: False,
        Property.TYPES.DESCRIPTION: False,
        Property.TYPES.BOOLEAN: True,
        Property.TYPES.DATE: False,
        Property.TYPES.DATETIME: False,
        Property.TYPES.SELECT: True,
        Property.TYPES.MULTISELECT: True,
    },
}
