def get_product_type_name(language):
    names = {
        'en': 'Product Type',
        'fr': 'Type de produit',
        'nl': 'Producttype',
        'de': 'Produkttyp',
        'it': 'Tipo di prodotto',
        'es': 'Tipo de producto',
        'pt': 'Tipo de produto',
        'pt-br': 'Tipo de produto',
        'pl': 'Rodzaj produktu',
        'ro': 'Tip de produs',
        'bg': 'Тип продукт',
        'hr': 'Vrsta proizvoda',
        'cs': 'Typ produktu',
        'da': 'Produkttype',
        'et': 'Toodetüüp',
        'fi': 'Tuotetyyppi',
        'el': 'Τύπος προϊόντος',
        'hu': 'Terméktípus',
        'lv': 'Produkta veids',
        'lt': 'Produkto tipas',
        'sk': 'Typ produktu',
        'sl': 'Vrsta izdelka',
        'sv': 'Produkttyp',
        'th': 'ประเภทสินค้า',
        'ja': '製品タイプ',
        'zh-hans': '产品类型',
        'hi': 'उत्पाद प्रकार',
        'ru': 'Тип продукта',
        'af': 'Produk Tipe',
        'ar': 'نوع المنتج',
        'he': 'סוג מוצר',
        'tr': 'Ürün Türü',
        'id': 'Jenis Produk',
        'ko': '제품 유형',
        'ms': 'Jenis Produk',
        'vi': 'Loại sản phẩm',
        'fa': 'نوع محصول',
        'ur': 'مصنوع کی قسم',
    }
    return names.get(language, names['en'])


def get_brand_name(language):
    names = {
        'en': 'Brand',
        'fr': 'Marque',
        'nl': 'Merk',
        'de': 'Marke',
        'it': 'Marca',
        'es': 'Marca',
        'pt': 'Marca',
        'pt-br': 'Marca',
        'pl': 'Marka',
        'ro': 'Brand',
        'bg': 'Марка',
        'hr': 'Marka',
        'cs': 'Značka',
        'da': 'Mærke',
        'et': 'Bränd',
        'fi': 'Brändi',
        'el': 'Μάρκα',
        'hu': 'Márka',
        'lv': 'Zīmols',
        'lt': 'Prekės ženklas',
        'sk': 'Značka',
        'sl': 'Znamka',
        'sv': 'Märke',
        'th': 'แบรนด์',
        'ja': 'ブランド',
        'zh-hans': '品牌',
        'hi': 'ब्रांड',
        'ru': 'Бренд',
        'af': 'Handelsmerk',
        'ar': 'العلامة التجارية',
        'he': 'מותג',
        'tr': 'Marka',
        'id': 'Merek',
        'ko': '브랜드',
        'ms': 'Jenama',
        'vi': 'Thương hiệu',
        'fa': 'برند',
        'ur': 'برانڈ',
    }
    return names.get(language, names['en'])
