# Generated by Django 5.1.1 on 2025-02-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitenantuser',
            name='onboarding_status',
            field=models.CharField(choices=[('GENERATE_DEMO_DATA', 'Generate Demo Data'), ('ADD_COMPANY', 'Add Company'), ('ADD_CURRENCY', 'Add Currency'), ('CONFIRM_VAT_RATE', 'Confirm VAT Rate'), ('DASHBOARD_CARDS_PRESENTATION', 'Dashboard Cards Presentation'), ('COMPLETE_DASHBOARD_CARDS', 'Complete Dashboard Cards'), ('DONE', 'Done')], default='ADD_COMPANY', max_length=30),
        ),
    ]
