# Generated by Django 4.2.6 on 2023-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitenantuser',
            name='language',
            field=models.CharField(choices=[('nl', 'Nederlands'), ('en-gb', 'English GB')], default='en-gb', max_length=7),
        ),
        migrations.AlterField(
            model_name='multitenantuser',
            name='username',
            field=models.EmailField(help_text='Email Address', max_length=254, unique=True),
        ),
    ]
