# Generated by Django 4.2.6 on 2023-11-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_multitenantuser_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitenantuser',
            name='invitation_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multitenantuser',
            name='is_multi_tenant_company_owner',
            field=models.BooleanField(default=False),
        ),
    ]
