# Generated by Django 5.1.1 on 2025-03-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_multitenantuser_onboarding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitenantcompany',
            name='ai_points',
            field=models.IntegerField(default=0, help_text='Points allocated for AI processes.'),
        ),
    ]
