# Generated by Django 5.1.7 on 2025-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_multitenantcompany_ai_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitenantcompany',
            name='language',
            field=models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'French')], default='en', max_length=7),
        ),
        migrations.AlterField(
            model_name='multitenantuser',
            name='language',
            field=models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'French')], default='en', max_length=7),
        ),
    ]
