# Generated by Django 4.2.6 on 2023-11-28 16:14

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_multitenantuser_invitation_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitenantuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars', validators=[core.validators.validate_image_extension, core.validators.no_dots_in_filename]),
        ),
    ]
