# Generated by Django 5.2 on 2025-04-10 19:02

from django.db import migrations

def set_default_languages(apps, schema_editor):
    MultiTenantCompany = apps.get_model('core', 'MultiTenantCompany')
    default_languages = ['nl', 'en', 'fr']

    for company in MultiTenantCompany.objects.all():
        company.languages = default_languages
        company.save(update_fields=['languages'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_multitenantcompany_languages_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_languages),
    ]
