# Generated by Django 5.2 on 2025-08-13 11:01

import core.upload_paths
import core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitenantuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'depth': 3, 'segment_length': 2, 'subdir': 'avatars'}), validators=[core.validators.validate_image_extension, core.validators.no_dots_in_filename]),
        ),
    ]
