# Generated by Django 5.2 on 2025-08-14 14:14

import core.upload_paths
import core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_multitenantuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitenantuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'avatars'}), validators=[core.validators.validate_image_extension, core.validators.no_dots_in_filename]),
        ),
    ]
