# Generated by Django 5.2.5 on 2025-08-20 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_multitenantuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitenantcompany',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multitenantcompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multitenantcompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
