# Generated by Django 4.2.6 on 2023-12-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_multitenantuser_timezone'),
        ('core', '0010_multitenantuserlogintoken_token_and_more'),
    ]

    operations = [
    ]
