# Generated by Django 4.2.6 on 2023-12-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_multitenantuser_timezone'),
        ('core', '0011_merge_20231212_2011'),
    ]

    operations = [
    ]
