# Generated by Django 5.2 on 2025-11-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dashboardsection_dashboardcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
