# Generated by Django 5.2 on 2025-11-21 14:17

from django.db import migrations
from get_absolute_url.helpers import generate_absolute_url
from core.defaults import DASHBOARD_SECTION_DEFINITIONS


def _update_fields(instance, field_map):
    updated_fields = []
    for field, value in field_map.items():
        if getattr(instance, field) != value:
            setattr(instance, field, value)
            updated_fields.append(field)
    return updated_fields


def create_dashboard_defaults(apps, schema_editor):
    DashboardSection = apps.get_model("core", "DashboardSection")
    DashboardCard = apps.get_model("core", "DashboardCard")
    MultiTenantUser = apps.get_model("core", "MultiTenantUser")

    base_url = generate_absolute_url(trailing_slash=False)

    for user in MultiTenantUser.objects.select_related("multi_tenant_company"):
        company = user.multi_tenant_company
        if company is None:
            continue

        for section_def in DASHBOARD_SECTION_DEFINITIONS:
            defaults = {
                "description": section_def["description"],
                "sort_order": section_def["sort_order"],
                "multi_tenant_company": company,
                "created_by_multi_tenant_user": user,
                "last_update_by_multi_tenant_user": user,
            }
            section, created = DashboardSection.objects.get_or_create(
                user=user,
                title=section_def["title"],
                defaults=defaults,
            )

            if not created:
                updates = {
                    "description": section_def["description"],
                    "sort_order": section_def["sort_order"],
                }
                if section.multi_tenant_company_id != company.id:
                    updates["multi_tenant_company"] = company
                updated_fields = _update_fields(section, updates)
                if updated_fields:
                    section.last_update_by_multi_tenant_user = user
                    updated_fields.append("last_update_by_multi_tenant_user")
                    section.save(update_fields=updated_fields)

            cards = section_def.get("cards", [])
            if not cards:
                continue

            for order, card_def in enumerate(cards, start=1):
                variables = card_def.get("variables", {}).copy()
                error_code = variables.get("errorCode")
                url_path = card_def.get("url_path")
                full_url = f"{base_url}{url_path}" if url_path else None

                lookup_kwargs = {
                    "user": user,
                    "section": section,
                    "query_key": card_def["query_key"],
                    "url": full_url,
                }
                if error_code is not None:
                    lookup_kwargs["variables__errorCode"] = error_code
                else:
                    lookup_kwargs["variables"] = variables

                defaults = {
                    "title": card_def["title"],
                    "description": card_def["description"],
                    "color": card_def["color"],
                    "query": card_def["query"],
                    "variables": variables,
                    "sort_order": card_def.get("sort_order", order),
                    "url": full_url,
                    "multi_tenant_company": company,
                    "created_by_multi_tenant_user": user,
                    "last_update_by_multi_tenant_user": user,
                }

                card, created = DashboardCard.objects.get_or_create(
                    defaults=defaults,
                    **lookup_kwargs,
                )

                if not created:
                    updates = {
                        "title": card_def["title"],
                        "description": card_def["description"],
                        "color": card_def["color"],
                        "query": card_def["query"],
                        "variables": variables,
                        "sort_order": card_def.get("sort_order", order),
                        "url": full_url,
                    }
                    if card.multi_tenant_company_id != company.id:
                        updates["multi_tenant_company"] = company
                    updated_fields = _update_fields(card, updates)
                    if updated_fields:
                        card.last_update_by_multi_tenant_user = user
                        updated_fields.append("last_update_by_multi_tenant_user")
                        card.save(update_fields=updated_fields)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dashboardcard_url'),
    ]

    operations = [
        migrations.RunPython(create_dashboard_defaults, migrations.RunPython.noop),
    ]

