# Generated by Django 5.2 on 2025-11-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20251121_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardcard',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterModelOptions(
            name='dashboardsection',
            options={'ordering': ('sort_order',)},
        ),
    ]
