# Generated by Django 5.2 on 2025-12-15

from django.db import migrations
from django.db.models import Q


def delete_deprecated_inspector_dashboard_cards(apps, schema_editor):
    DashboardCard = apps.get_model("core", "DashboardCard")
    DashboardCard.objects.filter(
        Q(url__contains="inspectorNotSuccessfullyCodeError=125")
        | Q(url__contains="inspectorNotSuccessfullyCodeError=126")
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_dashboardcard_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            delete_deprecated_inspector_dashboard_cards,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

