# Generated by Django 5.2 on 2026-01-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_deprecated_inspector_dashboard_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
