# Generated by Django 5.2 on 2026-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_multitenantcompany_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcard',
            name='url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
