# Generated by Django 5.0.2 on 2024-04-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_multitenantuser_timezone_demodatarelation'),
        ('core', '0044_alter_multitenantuser_timezone'),
    ]

    operations = [
    ]
