# Generated by Django 5.0.2 on 2024-07-16 13:42

from django.db import migrations


def forwards(apps, schema_editor):
    MultiTenantCompany = apps.get_model('core.MultiTenantCompany')
    languages_allowed = ['en', 'nl']

    for mtc in MultiTenantCompany.objects.exclude(language__in=languages_allowed):
        mtc.language = 'en'
        mtc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_alter_multitenantuser_timezone'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
