# Generated by Django 5.0.7 on 2024-07-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_alter_multitenantuser_timezone'),
        ('core', '0130_alter_multitenantuser_timezone'),
    ]

    operations = [
    ]
