# Generated by Django 4.2.6 on 2023-10-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('currencies', '0001_initial'),
        ('units', '0001_initial'),
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('CONFIRMED',
                 'Confirmation Received'), ('PENDING_DELIVERY', 'Pending Delivery'), ('DELIVERED', 'Delivered')], max_length=16)),
                ('order_reference', models.CharField(max_length=100)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_address_set', to='contacts.shippingaddress')),
                ('invoice_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_address_set', to='contacts.internalcompany')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.simpleproduct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.supplier')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.supplierproduct')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorder')),
            ],
        ),
    ]
