# Generated by Django 4.2.5 on 2023-09-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('django_shared_multi_tenant', '0002_multitenantcompany_language'),
        ('products', '0002_bundleproduct_productvariation_umbrellaproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('EUR', 'Euro')], max_length=3)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('PC', 'Pieces')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_shared_multi_tenant.multitenantcompany')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
