# Generated by Django 4.2.5 on 2023-09-15 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_alter_supplierproduct_currency'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.unit'),
        ),
    ]
