# Generated by Django 5.0.2 on 2024-03-04 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_address_contact'),
        ('purchasing', '0004_alter_purchaseorder_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_address_set', to='contacts.invoiceaddress'),
        ),
    ]
