# Generated by Django 5.0.2 on 2024-03-18 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_bundlevariation_unique_together_and_more'),
        ('purchasing', '0005_alter_purchaseorder_invoice_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
