# Generated by Django 5.0.2 on 2024-04-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_alter_purchaseorder_supplier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together={('purchase_order', 'item')},
        ),
    ]
