# Generated by Django 5.0.2 on 2024-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_alter_purchaseorderitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
