# Generated by Django 5.0.2 on 2024-05-31 12:11

from django.db import migrations

def delete_all_order_items(apps, schema_editor):
    PurchaseOrderItem = apps.get_model('purchasing', 'PurchaseOrderItem')
    PurchaseOrderItem.objects.all().delete()

def reverse_func(apps, schema_editor):
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_alter_purchaseorder_order_reference'),
    ]

    operations = [
        migrations.RunPython(delete_all_order_items, reverse_func),
    ]
