# Generated by Django 5.0.2 on 2024-05-31 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_supplierproduct_dropshipproduct_and_more'),
        ('purchasing', '0010_auto_20240531_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.supplierproduct'),
        ),
        migrations.DeleteModel(
            name='SupplierProduct',
        ),
    ]
