# Generated by Django 5.0.7 on 2024-08-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_sku_required_for_supplier_product_and_more'),
        ('purchasing', '0012_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='item',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together={('purchase_order', 'product')},
        ),
    ]
