# Generated by Django 5.0.7 on 2024-08-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
        ('purchasing', '0014_purchaseorderitem_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
        ),
    ]
