# Generated by Django 5.0.7 on 2024-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0015_purchaseorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TO_ORDER', 'To Order'), ('ORDERED', 'Ordered'), ('CONFIRMED',
                                   'Confirmation Received'), ('PENDING_DELIVERY', 'Pending Delivery'), ('DELIVERED', 'Delivered')], max_length=16),
        ),
    ]
