# Generated by Django 5.0.7 on 2024-08-22 17:22

from django.db import migrations


def set_internal_contacts(apps, schema):
    PurchaseOrder = apps.get_model('purchasing', 'PurchaseOrder')

    for po in PurchaseOrder.objects.filter(internal_contact__isnull=True).iterator():
        po.internal_contact = po.multi_tenant_company.multitenantuser_set.filter(is_multi_tenant_company_owner=True).first()
        po.save()


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0018_alter_purchaseorder_internal_contact'),
    ]

    operations = [
        migrations.RunPython(set_internal_contacts),
    ]
