# Generated by Django 5.0.7 on 2024-08-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0020_alter_purchaseorder_internal_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
    ]
