# Generated by Django 5.1 on 2024-08-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0022_purchaseorder_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity_received',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
