# Generated by Django 5.1 on 2024-08-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0023_purchaseorderitem_quantity_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity_received',
            field=models.IntegerField(default=0),
        ),
    ]
