# Generated by Django 5.1.1 on 2024-10-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0024_alter_purchaseorderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TO_ORDER', 'To Order'), ('ORDERED', 'Ordered'), ('CONFIRMED', 'Confirmation Received'), ('PENDING_DELIVERY', 'Pending Delivery'), ('DELIVERED', 'Delivered')], default='DRAFT', max_length=16),
        ),
    ]
