# Generated by Django 5.1.1 on 2024-10-20 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0007_accountingmirroraccount_accountingmirrorcreditnote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickbooksAccount',
            fields=[
                ('accountingmirroraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.accountingmirroraccount')),
                ('client_id', models.CharField(help_text='Client ID for QuickBooks API.', max_length=255)),
                ('client_secret', models.CharField(help_text='Client Secret for QuickBooks API.', max_length=255)),
                ('access_token', models.CharField(blank=True, help_text='Access Token for QuickBooks API.', max_length=255, null=True)),
                ('environment', models.CharField(default='sandbox', help_text='QuickBooks environment (sandbox or production).', max_length=50)),
                ('redirect_uri', models.URLField(help_text='Redirect URI for QuickBooks OAuth2 authentication.')),
                ('remote_currency', models.CharField(help_text='The currency in the remote system.', max_length=10)),
                ('quickbooks_currency', models.CharField(help_text='The currency configured in QuickBooks.', max_length=10)),
                ('code_of_service', models.CharField(blank=True, help_text='Code of service for QuickBooks integration.', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'QuickBooks Account',
                'verbose_name_plural': 'QuickBooks Accounts',
            },
            bases=('accounting.accountingmirroraccount',),
        ),
        migrations.CreateModel(
            name='QuickbooksCreditNote',
            fields=[
                ('accountingmirrorcreditnote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.accountingmirrorcreditnote')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('accounting.accountingmirrorcreditnote',),
        ),
        migrations.CreateModel(
            name='QuickbooksCustomer',
            fields=[
                ('accountingmirrorcustomer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.accountingmirrorcustomer')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('accounting.accountingmirrorcustomer',),
        ),
        migrations.CreateModel(
            name='QuickbooksInvoice',
            fields=[
                ('accountingmirrorinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.accountingmirrorinvoice')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('accounting.accountingmirrorinvoice',),
        ),
        migrations.CreateModel(
            name='QuickbooksVat',
            fields=[
                ('accountingmirrorvat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.accountingmirrorvat')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('accounting.accountingmirrorvat',),
        ),
    ]
