# Generated by Django 5.1.1 on 2024-10-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickbooksaccount',
            name='quickbooks_currency',
        ),
        migrations.RemoveField(
            model_name='quickbooksaccount',
            name='remote_currency',
        ),
        migrations.AddField(
            model_name='quickbooksaccount',
            name='authorization_code',
            field=models.CharField(blank=True, help_text='Authorization code for OAuth2.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksaccount',
            name='realm_id',
            field=models.CharField(blank=True, help_text='QuickBooks realm ID.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksaccount',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksaccount',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quickbooksaccount',
            name='access_token',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quickbooksaccount',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quickbooksaccount',
            name='client_secret',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quickbooksaccount',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quickbooksaccount',
            name='redirect_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
