# Generated by Django 5.1.1 on 2024-10-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0002_remove_quickbooksaccount_quickbooks_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksaccount',
            name='company_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
