# Generated by Django 5.1.1 on 2024-10-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0004_alter_quickbookscustomer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickbookscustomer',
            name='sync_token',
        ),
    ]
