# Generated by Django 5.1.1 on 2024-11-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0005_remove_quickbookscustomer_sync_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksvat',
            name='remote_name',
            field=models.CharField(blank=True, help_text='Name of the tax code in QuickBooks', max_length=255, null=True),
        ),
    ]
