# Generated by Django 5.1.1 on 2024-11-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0006_quickbooksvat_remote_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksvat',
            name='rate_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate percentage of the TaxRate', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksvat',
            name='tax_code_name',
            field=models.CharField(blank=True, help_text='Name of the TaxCode in QuickBooks', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksvat',
            name='tax_rate_id',
            field=models.CharField(blank=True, help_text='ID of the TaxRate in QuickBooks', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksvat',
            name='tax_rate_name',
            field=models.CharField(blank=True, help_text='Name of the TaxRate in QuickBooks', max_length=255, null=True),
        ),
    ]
