# Generated by Django 5.1.1 on 2024-11-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0007_quickbooksvat_rate_value_quickbooksvat_tax_code_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickbooksvat',
            name='tax_code_name',
        ),
    ]
