currencies = {
    'AT': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'BE': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'BG': {'name': 'Bulgarian Lev', 'iso_code': 'BGN', 'symbol': 'лв'},
    'HR': {'name': 'Croatian Kuna', 'iso_code': 'HRK', 'symbol': 'kn'},
    'CY': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'CZ': {'name': 'Czech Koruna', 'iso_code': 'CZK', 'symbol': 'Kč'},
    'DK': {'name': 'Danish Krone', 'iso_code': 'DKK', 'symbol': 'kr'},
    'EE': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'FI': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'FR': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'DE': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'GR': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'HU': {'name': 'Hungarian Forint', 'iso_code': 'HUF', 'symbol': 'Ft'},
    'IE': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'IT': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'LV': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'LT': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'LU': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'MT': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'NL': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'PL': {'name': 'Polish Zloty', 'iso_code': 'PLN', 'symbol': 'zł'},
    'PT': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'RO': {'name': 'Romanian Leu', 'iso_code': 'RON', 'symbol': 'lei'},
    'SK': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'SI': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'ES': {'name': 'Euro', 'iso_code': 'EUR', 'symbol': '€'},
    'SE': {'name': 'Swedish Krona', 'iso_code': 'SEK', 'symbol': 'kr'},
    'GB': {'name': 'Pound Sterling', 'iso_code': 'GBP', 'symbol': '£'},
    'US': {'name': 'United States Dollar', 'iso_code': 'USD', 'symbol': '$'},
    'CA': {'name': 'Canadian Dollar', 'iso_code': 'CAD', 'symbol': '$'},
    'AU': {'name': 'Australian Dollar', 'iso_code': 'AUD', 'symbol': '$'},
    'JP': {'name': 'Japanese Yen', 'iso_code': 'JPY', 'symbol': '¥'},
    'CN': {'name': 'Chinese Yuan', 'iso_code': 'CNY', 'symbol': '¥'},
    'IN': {'name': 'Indian Rupee', 'iso_code': 'INR', 'symbol': '₹'},
    'BR': {'name': 'Brazilian Real', 'iso_code': 'BRL', 'symbol': 'R$'},
    'RU': {'name': 'Russian Ruble', 'iso_code': 'RUB', 'symbol': '₽'},
    'ZA': {'name': 'South African Rand', 'iso_code': 'ZAR', 'symbol': 'R'},
    'SA': {'name': 'Saudi Riyal', 'iso_code': 'SAR', 'symbol': 'ر.س'},
    'AE': {'name': 'United Arab Emirates Dirham', 'iso_code': 'AED', 'symbol': 'د.إ'},
    'MX': {'name': 'Mexican Peso', 'iso_code': 'MXN', 'symbol': '$'}
}
