# Generated by Django 5.1.1 on 2024-09-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magentoproperty',
            options={'verbose_name': 'Magento Property', 'verbose_name_plural': 'Magento Properties'},
        ),
        migrations.AddField(
            model_name='magentoproperty',
            name='attribute_code',
            field=models.CharField(default='', help_text='The attribute code used in Magento for this property.', max_length=255, verbose_name='Attribute Code'),
            preserve_default=False,
        ),
    ]
