# Generated by Django 5.1.1 on 2024-09-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0002_alter_magentoproperty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magentosaleschannelview',
            name='code',
            field=models.CharField(default='', help_text='Unique code for the sales channel view.', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
