# Generated by Django 5.1.1 on 2024-09-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0003_magentosaleschannelview_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='magentoremotelanguage',
            name='sales_channel_view',
            field=models.ForeignKey(default=1, help_text='The sales channel view associated with this remote language.', on_delete=django.db.models.deletion.CASCADE, related_name='remote_languages', to='magento2.magentosaleschannelview'),
            preserve_default=False,
        ),
    ]
