# Generated by Django 5.1.1 on 2024-09-11 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0004_magentoremotelanguage_sales_channel_view'),
        ('properties', '0021_productpropertiesrule_created_by_multi_tenant_user_and_more'),
        ('sales_channels', '0010_alter_remoteproductproperty_local_instance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='magentoattributeset',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='magentoattributeset',
            name='local_instance',
            field=models.ForeignKey(help_text='The local ProductPropertiesRule associated with this Magento attribute set.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.productpropertiesrule'),
        ),
        migrations.AlterField(
            model_name='magentoattributesetattribute',
            name='local_instance',
            field=models.ForeignKey(help_text='The local ProductPropertiesRuleItem associated with this Magento attribute.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.productpropertiesruleitem'),
        ),
        migrations.AlterUniqueTogether(
            name='magentoattributeset',
            unique_together={('local_instance', 'group_remote_id', 'sales_channel')},
        ),
    ]
