# Generated by Django 5.1.1 on 2025-03-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0004_magentoeancode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magentoattributesetimport',
            name='created_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='magentoattributesetimport',
            name='import_process',
        ),
        migrations.RemoveField(
            model_name='magentoattributesetimport',
            name='last_update_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='magentoattributesetimport',
            name='multi_tenant_company',
        ),
        migrations.RemoveField(
            model_name='magentoattributesetimport',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='magentoattributesetimport',
            name='remote_attribute_set',
        ),
        migrations.DeleteModel(
            name='MagentoAttributeSetAttributeImport',
        ),
        migrations.DeleteModel(
            name='MagentoAttributeSetImport',
        ),
    ]
