# Generated by Django 5.1.1 on 2024-09-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0005_alter_magentoattributeset_unique_together_and_more'),
        ('properties', '0021_productpropertiesrule_created_by_multi_tenant_user_and_more'),
        ('sales_channels', '0010_alter_remoteproductproperty_local_instance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='magentoattributeset',
            unique_together={('local_instance', 'sales_channel')},
        ),
    ]
