# Generated by Django 5.1.1 on 2025-03-26 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0006_magentoattributesetattributeimport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magentoattributesetattributeimport',
            name='remote_attribute',
            field=models.ForeignKey(blank=True, help_text='The remote attribute associated with this import process.', null=True, on_delete=django.db.models.deletion.CASCADE, to='magento2.magentoattributesetattribute'),
        ),
        migrations.AlterField(
            model_name='magentoattributesetimport',
            name='remote_attribute_set',
            field=models.ForeignKey(blank=True, help_text='The remote attribute set associated with this import process.', null=True, on_delete=django.db.models.deletion.CASCADE, to='magento2.magentoattributeset'),
        ),
    ]
