# Generated by Django 5.1.1 on 2024-09-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0006_alter_magentoattributeset_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='magentoattributesetattribute',
            name='remote_property',
            field=models.ForeignKey(default=2, help_text='The MagentoProperty associated with this attribute set attribute.', on_delete=django.db.models.deletion.PROTECT, to='magento2.magentoproperty'),
            preserve_default=False,
        ),
    ]
