# Generated by Django 5.1.1 on 2024-09-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0008_magentoremoteorderitem'),
        ('sales_channels', '0011_remoteorderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MagentoRemoteOrderItem',
            new_name='MagentoOrderItem',
        ),
    ]
