# Generated by Django 5.2 on 2025-04-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0008_alter_magentoattributesetattributeimport_structured_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magentocurrency',
            name='store_view_code',
            field=models.CharField(default='', help_text='The language code store view (will be used as scope).', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magentoremotelanguage',
            name='store_view_code',
            field=models.CharField(default='', help_text='The language code store view (will be used as scope).', max_length=10),
            preserve_default=False,
        ),
    ]
