# Generated by Django 5.2 on 2025-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0009_magentocurrency_store_view_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magentocurrency',
            name='store_view_code',
            field=models.CharField(help_text='The language code store view (will be used as scope).', max_length=126),
        ),
        migrations.AlterField(
            model_name='magentoremotelanguage',
            name='store_view_code',
            field=models.CharField(help_text='The language code store view (will be used as scope).', max_length=126),
        ),
    ]
