# Generated by Django 5.1.1 on 2024-09-11 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0009_rename_magentoremoteorderitem_magentoorderitem'),
        ('sales_channels', '0012_alter_remotecurrency_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagentoCurrency',
            fields=[
                ('remotecurrency_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotecurrency')),
                ('sales_channel_view', models.ForeignKey(help_text='The sales channel view associated with this remote currency.', on_delete=django.db.models.deletion.CASCADE, related_name='remote_currencies', to='magento2.magentosaleschannelview')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotecurrency',),
        ),
    ]
