# Generated by Django 5.1.1 on 2024-09-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0010_magentocurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magentosaleschannel',
            name='always_use_configurable_name',
        ),
        migrations.RemoveField(
            model_name='magentosaleschannel',
            name='sync_contents',
        ),
    ]
