# Generated by Django 5.1.1 on 2024-09-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0011_remove_magentosaleschannel_always_use_configurable_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagentoSalesChannelViewAssign',
        ),
    ]
