# Generated by Django 5.2 on 2025-04-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0011_magentotaxclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magentocurrency',
            name='sales_channel_view',
        ),
        migrations.RemoveField(
            model_name='magentocurrency',
            name='store_view_code',
        ),
        migrations.AddField(
            model_name='magentocurrency',
            name='website_code',
            field=models.CharField(default='', help_text='Magento website code. Prices are scoped at the website level.', max_length=64),
            preserve_default=False,
        ),
    ]
