# Generated by Django 5.1.1 on 2024-09-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0012_delete_magentosaleschannelviewassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magentosaleschannelview',
            name='code',
            field=models.CharField(help_text='Unique code for the sales channel view.', max_length=50),
        ),
    ]
