# Generated by Django 5.2 on 2025-04-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0012_remove_magentocurrency_sales_channel_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magentocurrency',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Indicates whether this is the default/global currency for Magento price updates (no scope).'),
        ),
        migrations.AddField(
            model_name='magentocurrency',
            name='store_view_codes',
            field=models.JSONField(blank=True, default=list, help_text='List of store view codes related to this website/currency.'),
        ),
    ]
