# Generated by Django 5.2.1 on 2025-05-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0013_magentocurrency_is_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magentoproductproperty',
            options={'verbose_name_plural': 'Magento Product Properties'},
        ),
    ]
