# Generated by Django 5.1.1 on 2024-09-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0013_alter_magentosaleschannelview_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magentoattributesetattribute',
            name='remote_property',
            field=models.ForeignKey(help_text='The MagentoProperty associated with this attribute set attribute.', on_delete=django.db.models.deletion.CASCADE, to='magento2.magentoproperty'),
        ),
    ]
