# Generated by Django 5.2 on 2026-04-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magento2', '0014_alter_magentoproductproperty_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagentoInventory',
        ),
    ]
