# Generated by Django 5.2 on 2025-06-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_channels', '0031_remove_remoteproduct_unique_remote_sku_per_channel_if_present_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCategory',
            fields=[
                ('remotecategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotecategory')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotecategory',),
        ),
        migrations.CreateModel(
            name='AmazonCurrency',
            fields=[
                ('remotecurrency_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotecurrency')),
                ('is_default', models.BooleanField(default=False, help_text='Marks the primary currency for this Amazon store.')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotecurrency',),
        ),
        migrations.CreateModel(
            name='AmazonEanCode',
            fields=[
                ('remoteeancode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteeancode')),
            ],
            options={
                'verbose_name': 'Amazon EAN Code',
                'verbose_name_plural': 'Amazon EAN Codes',
            },
            bases=('sales_channels.remoteeancode',),
        ),
        migrations.CreateModel(
            name='AmazonImageProductAssociation',
            fields=[
                ('remoteimageproductassociation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteimageproductassociation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteimageproductassociation',),
        ),
        migrations.CreateModel(
            name='AmazonInventory',
            fields=[
                ('remoteinventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteinventory')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteinventory',),
        ),
        migrations.CreateModel(
            name='AmazonOrder',
            fields=[
                ('remoteorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteorder')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteorder',),
        ),
        migrations.CreateModel(
            name='AmazonOrderItem',
            fields=[
                ('remoteorderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteorderitem')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteorderitem',),
        ),
        migrations.CreateModel(
            name='AmazonPrice',
            fields=[
                ('remoteprice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteprice')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteprice',),
        ),
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('remoteproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproduct')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteproduct',),
        ),
        migrations.CreateModel(
            name='AmazonProductContent',
            fields=[
                ('remoteproductcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproductcontent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteproductcontent',),
        ),
        migrations.CreateModel(
            name='AmazonProductProperty',
            fields=[
                ('remoteproductproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproductproperty')),
            ],
            options={
                'verbose_name_plural': 'Amazon Product Properties',
            },
            bases=('sales_channels.remoteproductproperty',),
        ),
        migrations.CreateModel(
            name='AmazonProperty',
            fields=[
                ('remoteproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproperty')),
                ('attribute_code', models.CharField(help_text='The attribute code used in Amazon for this property.', max_length=255, verbose_name='Attribute Code')),
            ],
            options={
                'verbose_name': 'Amazon Property',
                'verbose_name_plural': 'Amazon Properties',
            },
            bases=('sales_channels.remoteproperty',),
        ),
        migrations.CreateModel(
            name='AmazonPropertySelectValue',
            fields=[
                ('remotepropertyselectvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotepropertyselectvalue')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotepropertyselectvalue',),
        ),
        migrations.CreateModel(
            name='AmazonRemoteLanguage',
            fields=[
                ('remotelanguage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotelanguage')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotelanguage',),
        ),
        migrations.CreateModel(
            name='AmazonSalesChannel',
            fields=[
                ('saleschannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannel')),
                ('refresh_token', models.CharField(help_text='Refresh token used to generate new access tokens.', max_length=512)),
                ('access_token', models.CharField(blank=True, help_text='Access token for API requests.', max_length=512, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Expiration datetime of the access token.', null=True)),
                ('region', models.CharField(blank=True, choices=[('NA', 'North America'), ('EU', 'Europe'), ('FE', 'Far East')], help_text='Amazon region of this store.', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Amazon Sales Channel',
                'verbose_name_plural': 'Amazon Sales Channels',
            },
            bases=('sales_channels.saleschannel',),
        ),
        migrations.CreateModel(
            name='AmazonSalesChannelView',
            fields=[
                ('saleschannelview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannelview')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.saleschannelview',),
        ),
        migrations.CreateModel(
            name='AmazonVat',
            fields=[
                ('remotevat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotevat')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotevat',),
        ),
    ]
