# Generated by Django 5.2 on 2025-06-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonsaleschannel',
            name='refresh_token',
            field=models.CharField(blank=True, help_text='Refresh token used to generate new access tokens.', max_length=512, null=True),
        ),
    ]
