# Generated by Django 5.2 on 2025-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_alter_amazonsaleschannel_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonsaleschannel',
            name='country',
            field=models.CharField(blank=True, choices=[('CA', 'Canada'), ('US', 'United States'), ('MX', 'Mexico'), ('BR', 'Brazil'), ('IE', 'Ireland'), ('ES', 'Spain'), ('GB', 'United Kingdom'), ('FR', 'France'), ('BE', 'Belgium'), ('NL', 'Netherlands'), ('DE', 'Germany'), ('IT', 'Italy'), ('SE', 'Sweden'), ('ZA', 'South Africa'), ('PL', 'Poland'), ('EG', 'Egypt'), ('TR', 'Turkey'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('IN', 'India'), ('SG', 'Singapore'), ('AU', 'Australia'), ('JP', 'Japan')], help_text='Country code for Seller Central domain.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='amazonsaleschannel',
            name='state',
            field=models.CharField(blank=True, help_text='Unique state used for OAuth verification', max_length=64, null=True, unique=True),
        ),
    ]
