# Generated by Django 5.2 on 2025-06-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_amazonsaleschannel_country_amazonsaleschannel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonsaleschannel',
            name='refresh_token_expiration',
            field=models.DateTimeField(blank=True, help_text='When the refresh token will expire (typically 1 year).', null=True),
        ),
    ]
