# Generated by Django 5.2 on 2025-06-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_amazonsaleschannel_refresh_token_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazoncurrency',
            name='is_default',
        ),
    ]
