# Generated by Django 5.2 on 2025-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_amazon_language_currency_view_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonsaleschannel',
            name='remote_id',
            field=models.CharField(blank=True, help_text='Selling Partner ID (merchant ID) for Amazon SP-API.', max_length=64, null=True, unique=True),
        ),
    ]
