# Generated by Django 5.2 on 2025-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_amazonsaleschannel_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonsaleschannel',
            name='connection_error',
            field=models.TextField(blank=True, help_text='Stores the last OAuth connection failure traceback.', null=True),
        ),
    ]
