# Generated by Django 5.2 on 2025-06-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_amazonproducttype_amazonproducttypeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproducttype',
            name='remote_name',
            field=models.CharField(blank=True, help_text="Display name for the Amazon product type (e.g., 'Toys & Games').", max_length=255, null=True, verbose_name='Remote Name'),
        ),
        migrations.AddField(
            model_name='amazonproducttypeitem',
            name='remote_type',
            field=models.CharField(choices=[('REQUIRED_IN_CONFIGURATOR', 'Required in Configurator'), ('OPTIONAL_IN_CONFIGURATOR', 'Optional in Configurator'), ('REQUIRED', 'Required'), ('OPTIONAL', 'Optional')], help_text='The type of requirement in Amazon.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='amazonproperty',
            name='remote_name',
            field=models.CharField(blank=True, help_text="The display label for the remote value (e.g., 'Red').", max_length=255, null=True, verbose_name='Remote Name'),
        ),
        migrations.AddField(
            model_name='amazonpropertyselectvalue',
            name='remote_name',
            field=models.CharField(blank=True, help_text="The display label for the remote value (e.g., 'Red').", max_length=255, null=True, verbose_name='Remote Name'),
        ),
        migrations.AddField(
            model_name='amazonpropertyselectvalue',
            name='remote_value',
            field=models.CharField(blank=True, help_text="The raw option value from Amazon (e.g., 'RED').", max_length=255, null=True, verbose_name='Remote Value'),
        ),
    ]
