# Generated by Django 5.2 on 2025-06-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_amazonproducttype_remote_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmazonPropertySelectValue',
        ),
    ]
