# Generated by Django 5.2 on 2025-06-11 08:22

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_delete_amazonpropertyselectvalue'),
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('properties', '0009_merge_20250512_1309'),
        ('sales_channels', '0032_alter_saleschannelview_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonPropertySelectValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True)),
                ('successfully_created', models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.')),
                ('outdated', models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.')),
                ('outdated_since', models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True)),
                ('remote_value', models.CharField(help_text="The raw value from Amazon, in the marketplace's locale.", max_length=255)),
                ('remote_name', models.CharField(blank=True, help_text='The display name of the value in the given locale.', max_length=255, null=True)),
                ('amazon_property', models.ForeignKey(help_text='The Amazon property this value belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='select_values', to='amazon.amazonproperty')),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('local_instance', models.ForeignKey(blank=True, help_text='Optional link to local PropertySelectValue.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyselectvalue')),
                ('marketplace', models.ForeignKey(help_text='The Amazon marketplace for this value.', on_delete=django.db.models.deletion.CASCADE, to='amazon.amazonsaleschannelview')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel')),
            ],
            options={
                'unique_together': {('amazon_property', 'marketplace', 'remote_value')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
