# Generated by Django 5.2 on 2025-06-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0012_amazonpropertyselectvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonPublicDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_region_code', models.CharField(max_length=8)),
                ('product_type_code', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('raw_schema', models.JSONField()),
                ('type', models.CharField(choices=[('INT', 'Integer'), ('FLOAT', 'Float'), ('TEXT', 'Text'), ('DESCRIPTION', 'Description'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DATETIME', 'Date time'), ('SELECT', 'Select'), ('MULTISELECT', 'Multi Select')], default='TEXT', max_length=16)),
                ('usage_definition', models.TextField(help_text='Template for rendering this attribute into SP-API payload.\nTokens: %value%, %unit:weight%, %key:battery__cell_composition%, %marketplace_id%, %language_tag%')),
                ('export_definition', models.JSONField()),
                ('allows_unmapped_values', models.BooleanField(default=False)),
                ('unmapped_value_key', models.CharField(blank=True, default='value', help_text='If allows_unmapped_values == True, which JSON key gets free-text?', max_length=64)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_internal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Amazon Public Definition',
                'verbose_name_plural': 'Amazon Public Definitions',
                'indexes': [models.Index(fields=['api_region_code'], name='amazon_amaz_api_reg_df153a_idx'), models.Index(fields=['product_type_code'], name='amazon_amaz_product_ea0817_idx')],
                'unique_together': {('api_region_code', 'product_type_code', 'code')},
            },
        ),
    ]
