# Generated by Django 5.2 on 2025-06-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0013_amazonpublicdefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonpublicdefinition',
            name='export_definition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazonpublicdefinition',
            name='raw_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
