# Generated by Django 5.2 on 2025-06-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0016_rename_remote_name_amazonproperty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproperty',
            name='allows_unmapped_values',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonproperty',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonproperty',
            name='type',
            field=models.CharField(choices=[('INT', 'Integer'), ('FLOAT', 'Float'), ('TEXT', 'Text'), ('DESCRIPTION', 'Description'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DATETIME', 'Date time'), ('SELECT', 'Select'), ('MULTISELECT', 'Multi Select')], default='TEXT', max_length=16),
        ),
    ]
