# Generated by Django 5.2 on 2025-06-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0017_amazonproperty_allows_unmapped_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonsaleschannelview',
            name='api_region_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
