# Generated by Django 5.2 on 2025-06-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0018_amazonsaleschannelview_api_region_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonproducttype',
            old_name='remote_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='amazonproducttype',
            old_name='category_code',
            new_name='product_type_code',
        ),
        migrations.RemoveField(
            model_name='amazonproperty',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='amazonpublicdefinition',
            name='allows_unmapped_values',
        ),
        migrations.RemoveField(
            model_name='amazonpublicdefinition',
            name='type',
        ),
        migrations.RemoveField(
            model_name='amazonpublicdefinition',
            name='unmapped_value_key',
        ),
    ]
