# Generated by Django 5.2 on 2025-06-19 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0019_rename_remote_name_amazonproducttype_name_and_more'),
        ('sales_channels', '0032_alter_saleschannelview_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonSalesChannelImport',
            fields=[
                ('saleschannelimport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannelimport')),
                ('type', models.CharField(choices=[('schema', 'Schema'), ('products', 'Products')], max_length=32)),
            ],
            options={
                'verbose_name': 'Amazon Sales Channel Import',
                'verbose_name_plural': 'Amazon Sales Channel Imports',
            },
            bases=('sales_channels.saleschannelimport',),
        ),
    ]
