# Generated by Django 5.2 on 2025-06-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0020_amazonsaleschannelimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='asin',
            field=models.CharField(blank=True, help_text='ASIN identifier for the product.', max_length=32, null=True),
        ),
    ]
