# Generated by Django 5.2 on 2025-07-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0024_amazonproperty_main_code'),
        ('amazon', '0024_variation_themes_and_allowed_in_configurator'),
    ]

    operations = [
    ]
