# Generated by Django 5.2 on 2025-07-01 19:06

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0025_merge_20250701_1750'),
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('sales_channels', '0037_alter_remoteproperty_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproperty',
            name='main_code',
            field=models.CharField(blank=True, help_text="The main attribute code (part before '__').", max_length=255),
        ),
        migrations.CreateModel(
            name='AmazonDefaultUnitConfigurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('selected_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_unit_configurators', to='sales_channels.saleschannel')),
            ],
            options={
                'verbose_name': 'Default Unit Configurator',
                'verbose_name_plural': 'Default Unit Configurators',
                'unique_together': {('sales_channel', 'code')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
