# Generated by Django 5.2 on 2025-07-02 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0027_amazondefaultunitconfigurator_marketplace'),
        ('sales_channels', '0037_alter_remoteproperty_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmazonVat',
            new_name='AmazonTaxCode',
        ),
    ]
