# Generated by Django 5.2 on 2025-07-04 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0029_amazonproduct_ean_and_marketplaces'),
        ('sales_channels', '0037_alter_remoteproperty_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonRemoteLog',
            fields=[
                ('remotelog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotelog')),
                ('submission_id', models.CharField(blank=True, max_length=255, null=True)),
                ('issues', models.JSONField(blank=True, null=True)),
                ('processing_status', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Amazon Remote Log',
                'verbose_name_plural': 'Amazon Remote Logs',
                'ordering': ['-created_at'],
            },
            bases=('sales_channels.remotelog',),
        ),
    ]
