# Generated by Django 5.2 on 2025-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0031_amazonsaleschannel_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproducttype',
            name='listing_offer_required_properties',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
