# Generated by Django 5.2 on 2025-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0032_amazonproducttype_listing_offer_required_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonpublicdefinition',
            name='allowed_in_listing_offer_request',
            field=models.BooleanField(default=False),
        ),
    ]
