# Generated by Django 5.2 on 2025-07-15 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0035_amazonproducttype_imported'),
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('properties', '0012_alter_property_options_and_more'),
        ('sales_channels', '0037_alter_remoteproperty_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amazonproducttype',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='amazonproducttype',
            constraint=models.UniqueConstraint(condition=models.Q(('local_instance__isnull', False)), fields=('local_instance', 'sales_channel'), name='unique_amazonproducttype_local_instance_sales_channel_not_null'),
        ),
        migrations.AddConstraint(
            model_name='amazonproducttype',
            constraint=models.UniqueConstraint(condition=models.Q(('product_type_code__isnull', False)), fields=('product_type_code', 'sales_channel'), name='unique_amazonproducttype_code_sales_channel_not_null'),
        ),
    ]
