# Generated by Django 5.2.4 on 2025-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0039_amazonsaleschannelview_is_default"),
        ("sales_channels", "0037_alter_remoteproperty_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amazonsaleschannelview",
            options={},
        ),
        migrations.AddConstraint(
            model_name="amazonsaleschannelview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("sales_channel",),
                name="unique_default_marketplace",
                violation_error_message="You can only have one default marketplace per Amazon store.",
            ),
        ),
    ]
