# Generated by Django 5.2 on 2025-08-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0044_amazonimportbrokenrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonimportbrokenrecord',
            options={'verbose_name': 'Amazon Import Broken Record', 'verbose_name_plural': 'Amazon Import Broken Records'},
        ),
    ]
