# Generated by Django 5.2 on 2025-08-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0045_alter_amazonimportbrokenrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonpropertyselectvalue',
            name='remote_name',
            field=models.CharField(blank=True, help_text='The display name of the value in the given locale.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='amazonpropertyselectvalue',
            name='remote_value',
            field=models.CharField(help_text="The raw value from Amazon, in the marketplace's locale.", max_length=512),
        ),
    ]
