# Generated by Django 5.2.5 on 2025-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0046_alter_amazonpropertyselectvalue_remote_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="amazonimageproductassociation",
            name="imported_url",
            field=models.URLField(
                blank=True,
                help_text="Original URL of the image when imported from Amazon.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
