# Generated by Django 5.2 on 2025-08-14 14:14

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0049_amazonpropertyselectvalue_translated_remote_name'),
        ('core', '0009_alter_multitenantuser_avatar'),
        ('products', '0019_alter_producttranslation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonImportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_import_data', to='products.product')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_data', to='amazon.amazonsaleschannel')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_data', to='amazon.amazonsaleschannelview')),
            ],
            options={
                'verbose_name': 'Amazon Import Data',
                'verbose_name_plural': 'Amazon Import Data',
                'unique_together': {('sales_channel', 'product', 'view')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
    ]
