# Generated by Django 5.2 on 2025-08-14 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0051_amazonproductproperty_remote_select_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproductproperty',
            name='remote_select_value',
            field=models.ForeignKey(blank=True, help_text='Reference to the remote select value if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_properties', to='amazon.amazonpropertyselectvalue'),
        ),
        migrations.AlterField(
            model_name='amazonproductproperty',
            name='remote_select_values',
            field=models.ManyToManyField(blank=True, help_text='References to remote select values for multiselect properties.', related_name='product_properties_multi', to='amazon.amazonpropertyselectvalue'),
        ),
    ]
