# Generated by Django 5.2 on 2025-08-15 18:25

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0052_alter_amazonproductproperty_remote_select_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonBrowseNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marketplace_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('context_name', models.CharField(blank=True, max_length=255, null=True)),
                ('has_children', models.BooleanField(default=False)),
                ('child_node_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Only populated if has_children is True', size=None)),
                ('browse_path_by_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Full browsePathById chain', size=None)),
                ('browse_path_by_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Full browsePathByName chain', size=None)),
                ('product_type_definitions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('path_depth', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['marketplace_id'], name='amazon_amaz_marketp_630389_idx'), models.Index(fields=['path_depth'], name='amazon_amaz_path_de_61d913_idx'), django.contrib.postgres.indexes.GinIndex(fields=['product_type_definitions'], name='amazon_amaz_product_a2055c_gin')],
                'unique_together': {('remote_id', 'marketplace_id')},
            },
        ),
    ]
