# Generated by Django 5.2 on 2025-08-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0053_amazonbrowsenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonbrowsenode',
            name='is_root',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='amazonbrowsenode',
            name='context_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='amazonbrowsenode',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
