# Generated by Django 5.2 on 2025-08-19 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0056_amazongtinexemption_amazonvariationtheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonbrowsenode',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='amazon.amazonbrowsenode'),
        ),
    ]
