# Generated by Django 5.2 on 2025-08-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0058_clear_amazonbrowsenode_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonbrowsenode',
            name='parent_node',
        ),
        migrations.DeleteModel(
            name='AmazonBrowseNode',
        ),
    ]
