# Generated by Django 5.2 on 2025-08-19 13:43

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0059_auto_20250819_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonBrowseNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(db_index=True, max_length=50)),
                ('marketplace_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('context_name', models.CharField(blank=True, max_length=512, null=True)),
                ('has_children', models.BooleanField(default=False)),
                ('is_root', models.BooleanField(db_index=True, default=False)),
                ('child_node_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Only populated if has_children is True', size=None)),
                ('browse_path_by_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Full browsePathById chain', size=None)),
                ('browse_path_by_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Full browsePathByName chain', size=None)),
                ('product_type_definitions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('path_depth', models.PositiveSmallIntegerField(default=0)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='amazon.amazonbrowsenode')),
            ],
            options={
                'indexes': [models.Index(fields=['marketplace_id'], name='amazon_amaz_marketp_630389_idx'), models.Index(fields=['path_depth'], name='amazon_amaz_path_de_61d913_idx'), django.contrib.postgres.indexes.GinIndex(fields=['product_type_definitions'], name='amazon_amaz_product_a2055c_gin')],
                'unique_together': {('remote_id', 'marketplace_id')},
            },
        ),
    ]
