# Generated by Django 5.2 on 2025-08-20 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0060_amazonbrowsenode'),
        ('core', '0010_multitenantcompany_active_and_more'),
        ('products', '0019_alter_producttranslation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmazonMerchantAsin',
            new_name='AmazonExternalProductId',
        ),
    ]
