# Generated by Django 5.2 on 2025-08-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0061_rename_amazonmerchantasin_amazonexternalproductid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonexternalproductid',
            old_name='asin',
            new_name='value',
        ),
    ]
