# Generated by Django 5.2 on 2025-08-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0062_rename_asin_amazonexternalproductid_value'),
        ('products', '0019_alter_producttranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonexternalproductid',
            options={'verbose_name': 'Amazon External Product ID', 'verbose_name_plural': 'Amazon External Product IDs'},
        ),
        migrations.AddField(
            model_name='amazonexternalproductid',
            name='created_asin',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='amazonexternalproductid',
            name='type',
            field=models.CharField(choices=[('ASIN', 'ASIN'), ('UPC', 'UPC'), ('ISBN', 'ISBN'), ('GCID', 'GCID'), ('GTIN', 'GTIN'), ('JAN', 'JAN')], default='ASIN', max_length=4),
        ),
        migrations.AlterField(
            model_name='amazonexternalproductid',
            name='product',
            field=models.ForeignKey(help_text='The product this identifier belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='amazon_merchant_asins', to='products.product'),
        ),
        migrations.AlterField(
            model_name='amazonexternalproductid',
            name='view',
            field=models.ForeignKey(help_text='Marketplace for this identifier.', on_delete=django.db.models.deletion.CASCADE, related_name='product_asins', to='amazon.amazonsaleschannelview'),
        ),
    ]
