# Generated by Django 5.2 on 2025-08-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0063_alter_amazonexternalproductid_options_and_more'),
        ('products', '0019_alter_producttranslation_unique_together_and_more'),
        ('sales_channels', '0038_remove_saleschannelviewassign_issues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonproductbrowsenode',
            old_name='sales_channel_view',
            new_name='view',
        ),
        migrations.AlterUniqueTogether(
            name='amazonproductbrowsenode',
            unique_together={('product', 'view')},
        ),
    ]
