# Generated by Django 5.2 on 2025-08-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0064_rename_sales_channel_view_amazonproductbrowsenode_view_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonsaleschannel',
            name='listing_owner',
        ),
    ]
