# Generated by Django 5.2 on 2025-12-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0065_remove_amazonsaleschannel_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproductissue',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='amazonproductissue',
            name='enforcement_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='amazonproductissue',
            name='enforcement_attribute_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='amazonproductissue',
            name='enforcement_exemption_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazonproductissue',
            name='enforcement_exemption_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='amazonproductissue',
            name='is_suppressed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
