# Generated by Django 5.2 on 2025-12-15

from django.db import migrations


def _listify(value):
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def backfill_issue_fields(apps, schema_editor):
    AmazonProductIssue = apps.get_model("amazon", "AmazonProductIssue")

    try:
        from django.utils import timezone
        from django.utils.dateparse import parse_datetime
    except Exception:
        timezone = None
        parse_datetime = None

    batch_size = 1000
    to_update = []

    qs = AmazonProductIssue.objects.all().only(
        "id",
        "raw_data",
        "categories",
        "enforcement_actions",
        "enforcement_exemption_status",
        "enforcement_exemption_expiry_date",
        "enforcement_attribute_names",
        "is_suppressed",
    )

    for issue in qs.iterator(chunk_size=batch_size):
        raw = issue.raw_data if isinstance(issue.raw_data, dict) else {}

        issue.categories = _listify(raw.get("categories"))

        enforcements = raw.get("enforcements") if isinstance(raw.get("enforcements"), dict) else {}
        actions_raw = _listify(enforcements.get("actions"))
        actions = []
        for action_entry in actions_raw:
            if isinstance(action_entry, dict):
                action_value = action_entry.get("action")
                if action_value:
                    actions.append(str(action_value))
            elif action_entry:
                actions.append(str(action_entry))
        issue.enforcement_actions = actions
        issue.is_suppressed = bool(actions)

        exemption = enforcements.get("exemption") if isinstance(enforcements.get("exemption"), dict) else {}
        issue.enforcement_exemption_status = exemption.get("status") or None

        expiry_date = exemption.get("expiry_date") if isinstance(exemption, dict) else None
        parsed_expiry = None
        if expiry_date and parse_datetime:
            parsed_expiry = parse_datetime(str(expiry_date))
            if parsed_expiry and timezone and getattr(timezone, "is_naive", None) and timezone.is_naive(parsed_expiry):
                try:
                    parsed_expiry = timezone.make_aware(parsed_expiry, timezone=timezone.utc)
                except Exception:
                    pass
        issue.enforcement_exemption_expiry_date = parsed_expiry

        issue.enforcement_attribute_names = _listify(raw.get("attribute_names"))

        to_update.append(issue)
        if len(to_update) >= batch_size:
            AmazonProductIssue.objects.bulk_update(
                to_update,
                [
                    "categories",
                    "enforcement_actions",
                    "enforcement_exemption_status",
                    "enforcement_exemption_expiry_date",
                    "enforcement_attribute_names",
                    "is_suppressed",
                ],
                batch_size=batch_size,
            )
            to_update = []

    if to_update:
        AmazonProductIssue.objects.bulk_update(
            to_update,
            [
                "categories",
                "enforcement_actions",
                "enforcement_exemption_status",
                "enforcement_exemption_expiry_date",
                "enforcement_attribute_names",
                "is_suppressed",
            ],
            batch_size=batch_size,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("amazon", "0066_amazonproductissue_categories_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_issue_fields, reverse_code=migrations.RunPython.noop),
    ]

