# Generated by Django 5.2 on 2026-02-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0067_backfill_amazonproductissue_structured_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproduct',
            name='product_owner',
            field=models.BooleanField(default=True, help_text='Indicates if this listing was created by us and we can manage listing level data.'),
        ),
    ]
