# Generated by Django 5.2 on 2026-02-04 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0068_alter_amazonproduct_product_owner'),
        ('core', '0016_alter_dashboardsection_description'),
        ('properties', '0018_alter_productpropertiesrule_unique_together_and_more'),
        ('sales_channels', '0061_remoteproductcontent_content_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='amazonproducttypeitem',
            index=models.Index(fields=['amazon_rule', 'remote_property'], name='amazon_amaz_amazon__0d69fb_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonpropertyselectvalue',
            index=models.Index(fields=['amazon_property', 'marketplace', 'local_instance'], name='amazon_amaz_amazon__3622fa_idx'),
        ),
    ]
