# Generated by Django 5.2 on 2026-02-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0069_amazonproducttypeitem_amazon_amaz_amazon__0d69fb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonpropertyselectvalue',
            name='bool_value',
            field=models.BooleanField(blank=True, help_text='Boolean meaning for this option when mapping select/multiselect remote values to boolean.', null=True),
        ),
    ]
