# Generated by Django 5.2 on 2026-02-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0071_remove_amazonproperty_type'),
        ('sales_channels', '0068_backfill_remoteproperty_allows_unmapped_values_remote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonproperty',
            name='allows_unmapped_values',
        ),
    ]
