# Generated by Django 5.2 on 2026-02-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0072_remove_amazonproperty_allows_unmapped_values'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='amazonproducttype',
            name='unique_amazonproducttype_code_sales_channel_not_null',
        ),
    ]
