# Generated by Django 5.2 on 2026-02-23 21:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0075_populate_amazonproductbrowsenodenew'),
        ('core', '0016_alter_dashboardsection_description'),
        ('products', '0023_producttranslation_subtitle'),
        ('sales_channels', '0077_remoteproductcategory_legacy_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmazonProductBrowseNode',
            new_name='AmazonProductBrowseNodeOld',
        ),
    ]
