# Generated by Django 5.2 on 2026-02-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0076_rename_amazonproductbrowsenode_amazonproductbrowsenodeold'),
        ('sales_channels', '0077_remoteproductcategory_legacy_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmazonProductBrowseNodeNew',
            new_name='AmazonProductBrowseNode',
        ),
    ]
