# Generated by Django 5.2 on 2026-02-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0077_rename_amazonproductbrowsenodenew_amazonproductbrowsenode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonproductbrowsenode',
            options={'verbose_name': 'Amazon Product Browse Node', 'verbose_name_plural': 'Amazon Product Browse Nodes'},
        ),
    ]
