# Generated by Django 5.2 on 2026-02-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0073_remove_amazonproducttype_unique_amazonproducttype_code_sales_channel_not_null'),
        ('amazon', '0078_alter_amazonproductbrowsenode_options'),
    ]

    operations = [
    ]
