# Generated by Django 5.2 on 2026-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0079_merge_20260224_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonpublicdefinition',
            name='is_document_field',
            field=models.BooleanField(default=False),
        ),
    ]
