# Generated by Django 5.2 on 2026-02-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0080_amazonpublicdefinition_is_document_field'),
        ('sales_channels', '0079_alter_syncrequest_sync_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonDocumentThroughProduct',
            fields=[
                ('remotedocumentproductassociation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotedocumentproductassociation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotedocumentproductassociation',),
        ),
    ]
