# Generated by Django 5.2 on 2026-04-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0081_amazondocumentthroughproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmazonInventory',
        ),
    ]
