# Generated by Django 5.1.1 on 2025-03-20 10:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_multitenantcompany_ai_points'),
        ('imports_exports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportProcess',
            new_name='Import',
        ),
    ]
