# Generated by Django 5.1.1 on 2025-03-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0002_rename_importprocess_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('processing', 'Processing'), ('success', 'Success')], default='processing', max_length=10),
        ),
    ]
