# Generated by Django 5.1.1 on 2025-04-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0003_alter_import_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('failed', 'Failed'), ('processing', 'Processing'), ('success', 'Success')], default='new', max_length=10),
        ),
    ]
