# Generated by Django 5.2 on 2025-05-29 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0005_alter_import_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypedImport',
            fields=[
                ('import_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imports_exports.import')),
                ('is_periodic', models.BooleanField(default=False)),
                ('interval_hours', models.PositiveIntegerField(blank=True, help_text='Repeat interval in hours if this import is periodic.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When this import was last executed.', null=True)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('nl', 'Dutch'), ('de', 'German'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pl', 'Polish'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('et', 'Estonian'), ('fi', 'Finnish'), ('el', 'Greek'), ('hu', 'Hungarian'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('th', 'Thai'), ('ja', 'Japanese'), ('zh-hans', 'Chinese (Simplified)'), ('hi', 'Hindi'), ('pt-br', 'Portuguese (Brazil)'), ('ru', 'Russian'), ('af', 'Afrikaans'), ('ar', 'Arabic'), ('he', 'Hebrew'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('ko', 'Korean'), ('ms', 'Malay'), ('vi', 'Vietnamese'), ('fa', 'Persian'), ('ur', 'Urdu')], help_text='Language context for imported records (e.g., en, de, fr).', max_length=7, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('imports_exports.import',),
        ),
        migrations.CreateModel(
            name='MappedImport',
            fields=[
                ('typedimport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imports_exports.typedimport')),
                ('json_file', models.FileField(blank=True, help_text='Optional uploaded mapped JSON file.', null=True, upload_to='mapped_imports/')),
                ('json_url', models.URLField(blank=True, help_text='URL pointing to mapped JSON data.', null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('imports_exports.typedimport',),
        ),
    ]
