# Generated by Django 5.2 on 2025-05-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0006_typedimport_mappedimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedimport',
            name='type',
            field=models.CharField(blank=True, choices=[('property', 'Property'), ('property_select_value', 'Property Select Value'), ('property_rule', 'Product Property Rule'), ('product', 'Product')], help_text='What kind of import this is (e.g., Product, Property, Image...).', max_length=32, null=True),
        ),
    ]
