# Generated by Django 5.2 on 2025-06-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0008_typedimport_create_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typedimport',
            name='create_only',
        ),
    ]
