# Generated by Django 5.2 on 2025-06-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0009_remove_typedimport_create_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='create_only',
            field=models.BooleanField(default=False, help_text='If True, existing objects fetched during the import will not be updated.'),
        ),
    ]
