# Generated by Django 5.2 on 2025-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0010_import_create_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='broken_records',
            field=models.JSONField(blank=True, default=list, help_text='JSON array storing details of records that failed during import.'),
        ),
        migrations.AddField(
            model_name='import',
            name='skip_broken_records',
            field=models.BooleanField(default=False, help_text='If True, the import will skip records that raise errors and continue processing.'),
        ),
    ]
