# Generated by Django 5.2.3 on 2025-06-20 20:00

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_multitenantcompany_ai_points_and_more"),
        ("imports_exports", "0011_import_broken_records_import_skip_broken_records"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_emails",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of external emails that will receive a report.",
                    ),
                ),
                (
                    "created_by_multi_tenant_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_multi_tenant_user_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "import_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="imports_exports.import",
                    ),
                ),
                (
                    "last_update_by_multi_tenant_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_last_update_by_multi_tenant_user_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "multi_tenant_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.multitenantcompany",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Internal users that will receive a report.",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
