# Generated by Django 5.2 on 2025-08-13 11:01

import core.upload_paths
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0013_import_async_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappedimport',
            name='json_file',
            field=models.FileField(blank=True, help_text='Optional uploaded mapped JSON file.', null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'depth': 3, 'segment_length': 2, 'subdir': 'mapped_imports'})),
        ),
    ]
