# Generated by Django 5.2 on 2025-08-14 14:14

import core.upload_paths
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0015_import_update_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappedimport',
            name='json_file',
            field=models.FileField(blank=True, help_text='Optional uploaded mapped JSON file.', null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'mapped_imports'})),
        ),
    ]
