# Generated by Django 5.2 on 2025-08-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0016_alter_mappedimport_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='name',
            field=models.CharField(blank=True, help_text='Optional human-readable name for the import process.', max_length=255, null=True),
        ),
    ]
