# Generated by Django 5.2 on 2025-09-17 10:03

from django.db import migrations

def migrate_broken_records(apps, schema_editor):
    Import = apps.get_model("imports_exports", "Import")
    ImportBrokenRecord = apps.get_model("imports_exports", "ImportBrokenRecord")


    for imp in Import.objects.all():
        if not imp.broken_records:
            continue

        for record in imp.broken_records:
            ImportBrokenRecord.objects.create(
                import_process=imp,
                record=record,
                multi_tenant_company=imp.multi_tenant_company,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0018_importbrokenrecord'),
    ]

    operations = [
        migrations.RunPython(migrate_broken_records, reverse_code=migrations.RunPython.noop),
    ]
