# Generated by Django 5.2 on 2026-01-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0019_auto_20250917_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='override_only',
            field=models.BooleanField(default=False, help_text='If True, the import will only fill empty values and will not override existing data.'),
        ),
    ]
