# Generated by Django 5.2 on 2026-04-02 16:59

import core.models.core
import core.upload_paths
import dirtyfields.dirtyfields
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_multitenantcompany_language_and_more'),
        ('imports_exports', '0021_alter_typedimport_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedimport',
            name='language',
            field=models.CharField(blank=True, choices=[('en-gb', 'English (United Kingdom)'), ('fr-fr', 'French (France)'), ('nl-nl', 'Dutch (Netherlands)'), ('de-de', 'German (Germany)'), ('it-it', 'Italian (Italy)'), ('es-es', 'Spanish (Spain)'), ('pt-pt', 'Portuguese (Portugal)'), ('pl-pl', 'Polish (Poland)'), ('ro-ro', 'Romanian (Romania)'), ('bg-bg', 'Bulgarian (Bulgaria)'), ('hr-hr', 'Croatian (Croatia)'), ('cs-cz', 'Czech (Czech Republic)'), ('da-dk', 'Danish (Denmark)'), ('et-ee', 'Estonian (Estonia)'), ('fi-fi', 'Finnish (Finland)'), ('el-gr', 'Greek (Greece)'), ('hu-hu', 'Hungarian (Hungary)'), ('lv-lv', 'Latvian (Latvia)'), ('lt-lt', 'Lithuanian (Lithuania)'), ('sk-sk', 'Slovak (Slovakia)'), ('sl-si', 'Slovenian (Slovenia)'), ('sv-se', 'Swedish (Sweden)'), ('th-th', 'Thai (Thailand)'), ('ja-jp', 'Japanese (Japan)'), ('zh-cn', 'Chinese (Simplified)'), ('hi-in', 'Hindi (India)'), ('pt-br', 'Portuguese (Brazil)'), ('ru-ru', 'Russian (Russia)'), ('af-za', 'Afrikaans (South Africa)'), ('ar-sa', 'Arabic (Saudi Arabia)'), ('he-il', 'Hebrew (Israel)'), ('tr-tr', 'Turkish (Turkey)'), ('id-id', 'Indonesian (Indonesia)'), ('ko-kr', 'Korean (South Korea)'), ('ms-my', 'Malay (Malaysia)'), ('vi-vn', 'Vietnamese (Vietnam)'), ('fa-ir', 'Persian (Iran)'), ('ur-pk', 'Urdu (Pakistan)'), ('en', 'English'), ('fr', 'French'), ('nl', 'Dutch'), ('de', 'German'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pl', 'Polish'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('et', 'Estonian'), ('fi', 'Finnish'), ('el', 'Greek'), ('hu', 'Hungarian'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('th', 'Thai'), ('ja', 'Japanese'), ('zh-hans', 'Chinese (Simplified)'), ('hi', 'Hindi'), ('pt-br', 'Portuguese (Brazil)'), ('ru', 'Russian'), ('af', 'Afrikaans'), ('ar', 'Arabic'), ('he', 'Hebrew'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('ko', 'Korean'), ('ms', 'Malay'), ('vi', 'Vietnamese'), ('fa', 'Persian'), ('ur', 'Urdu')], help_text='Language context for imported records (e.g., en, de, fr).', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='typedimport',
            name='type',
            field=models.CharField(blank=True, choices=[('property', 'Property'), ('property_select_value', 'Property Select Value'), ('property_rule', 'Product Property Rule'), ('product', 'Product'), ('ean_code', 'EAN Code')], help_text='What kind of import this is (e.g., Product, Property, Image...).', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Optional human-readable name for the export process.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('failed', 'Failed'), ('processing', 'Processing'), ('success', 'Success')], default='new', max_length=10)),
                ('type', models.CharField(choices=[('json_feed', 'JSON Feed'), ('json', 'JSON'), ('csv', 'CSV'), ('excel', 'Excel')], default='json_feed', max_length=16)),
                ('kind', models.CharField(choices=[('products', 'Products'), ('product_properties', 'Product Properties'), ('properties', 'Properties'), ('property_select_values', 'Property Select Values'), ('images', 'Images'), ('documents', 'Documents'), ('videos', 'Videos'), ('sales_prices', 'Sales Prices'), ('price_lists', 'Price Lists'), ('price_list_prices', 'Price List Prices'), ('rules', 'Rules'), ('ean_codes', 'EAN Codes')], max_length=64)),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Whole integer representing the export progress.')),
                ('error_traceback', models.TextField(blank=True, help_text='Stores the error traceback if the export fails.', null=True)),
                ('raw_data', models.JSONField(blank=True, default=list, help_text='Canonical export data that remains compatible with our import payloads.')),
                ('feed_key', models.CharField(blank=True, db_index=True, help_text='Opaque identifier used by direct feed URLs.', max_length=64, null=True)),
                ('total_records', models.PositiveIntegerField(default=0, help_text='Total number of exported records.')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Behavior flags and filters that affect how the export is built.')),
                ('columns', models.JSONField(blank=True, default=list, help_text='List of export fields to include in raw_data.')),
                ('file', models.FileField(blank=True, help_text='Materialized export file when the type requires one.', null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'exports'}))),
                ('language', models.CharField(blank=True, choices=[('en-gb', 'English (United Kingdom)'), ('fr-fr', 'French (France)'), ('nl-nl', 'Dutch (Netherlands)'), ('de-de', 'German (Germany)'), ('it-it', 'Italian (Italy)'), ('es-es', 'Spanish (Spain)'), ('pt-pt', 'Portuguese (Portugal)'), ('pl-pl', 'Polish (Poland)'), ('ro-ro', 'Romanian (Romania)'), ('bg-bg', 'Bulgarian (Bulgaria)'), ('hr-hr', 'Croatian (Croatia)'), ('cs-cz', 'Czech (Czech Republic)'), ('da-dk', 'Danish (Denmark)'), ('et-ee', 'Estonian (Estonia)'), ('fi-fi', 'Finnish (Finland)'), ('el-gr', 'Greek (Greece)'), ('hu-hu', 'Hungarian (Hungary)'), ('lv-lv', 'Latvian (Latvia)'), ('lt-lt', 'Lithuanian (Lithuania)'), ('sk-sk', 'Slovak (Slovakia)'), ('sl-si', 'Slovenian (Slovenia)'), ('sv-se', 'Swedish (Sweden)'), ('th-th', 'Thai (Thailand)'), ('ja-jp', 'Japanese (Japan)'), ('zh-cn', 'Chinese (Simplified)'), ('hi-in', 'Hindi (India)'), ('pt-br', 'Portuguese (Brazil)'), ('ru-ru', 'Russian (Russia)'), ('af-za', 'Afrikaans (South Africa)'), ('ar-sa', 'Arabic (Saudi Arabia)'), ('he-il', 'Hebrew (Israel)'), ('tr-tr', 'Turkish (Turkey)'), ('id-id', 'Indonesian (Indonesia)'), ('ko-kr', 'Korean (South Korea)'), ('ms-my', 'Malay (Malaysia)'), ('vi-vn', 'Vietnamese (Vietnam)'), ('fa-ir', 'Persian (Iran)'), ('ur-pk', 'Urdu (Pakistan)'), ('en', 'English'), ('fr', 'French'), ('nl', 'Dutch'), ('de', 'German'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pl', 'Polish'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('et', 'Estonian'), ('fi', 'Finnish'), ('el', 'Greek'), ('hu', 'Hungarian'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('th', 'Thai'), ('ja', 'Japanese'), ('zh-hans', 'Chinese (Simplified)'), ('hi', 'Hindi'), ('pt-br', 'Portuguese (Brazil)'), ('ru', 'Russian'), ('af', 'Afrikaans'), ('ar', 'Arabic'), ('he', 'Hebrew'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('ko', 'Korean'), ('ms', 'Malay'), ('vi', 'Vietnamese'), ('fa', 'Persian'), ('ur', 'Urdu')], help_text='Language context for the export when applicable.', max_length=16, null=True)),
                ('is_periodic', models.BooleanField(default=False)),
                ('interval_hours', models.PositiveIntegerField(blank=True, help_text='Repeat interval in hours if this export is periodic.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When this export was last executed.', null=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
    ]
