# Generated by Django 5.2 on 2026-04-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0022_alter_typedimport_language_alter_typedimport_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappedimport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='export',
            name='kind',
            field=models.CharField(choices=[('products', 'Products'), ('properties', 'Properties'), ('property_select_values', 'Property Select Values'), ('images', 'Images'), ('documents', 'Documents'), ('videos', 'Videos'), ('sales_prices', 'Sales Prices'), ('price_lists', 'Price Lists'), ('price_list_prices', 'Price List Prices'), ('rules', 'Rules'), ('ean_codes', 'EAN Codes')], max_length=64),
        ),
    ]
