# Generated by Django 5.2 on 2026-04-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports_exports', '0022_alter_typedimport_language'),
        ('imports_exports', '0023_alter_mappedimport_options_alter_export_kind'),
    ]

    operations = [
    ]
