# Generated by Django 5.0.6 on 2025-05-03 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('currencies', '0002_auto_20250225_1139'),
        ('products', '0005_alter_product_sku_alter_producttranslation_name_and_more'),
        ('sales_prices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesprice',
            name='rrp_gte_price',
        ),
        migrations.RemoveConstraint(
            model_name='salesprice',
            name='rrp_nonzero',
        ),
        migrations.RemoveConstraint(
            model_name='salesprice',
            name='price_nonzero',
        ),
        migrations.AddConstraint(
            model_name='salesprice',
            constraint=models.CheckConstraint(check=models.Q(('rrp__gte', models.F('price'))), name='RRP cannot be less then the price'),
        ),
        migrations.AddConstraint(
            model_name='salesprice',
            constraint=models.CheckConstraint(check=models.Q(('rrp__gte', '0.01')), name='RRP cannot be 0'),
        ),
        migrations.AddConstraint(
            model_name='salesprice',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', '0.01')), name='Price cannot be 0'),
        ),
    ]
