# Generated by Django 5.2 on 2025-08-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_prices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespricelist',
            name='customers',
        ),
    ]
