# Generated by Django 4.2.5 on 2023-09-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_company_unique_together'),
        ('sales_prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespricelist',
            name='customers',
            field=models.ManyToManyField(to='contacts.customer'),
        ),
        migrations.DeleteModel(
            name='SalesPriceListAssign',
        ),
    ]
