# Generated by Django 5.2 on 2025-09-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_prices', '0002_remove_salespricelist_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespricelist',
            name='vat_included',
            field=models.BooleanField(default=True, verbose_name='Price list includes VAT'),
        ),
    ]
