# Generated by Django 5.0.2 on 2024-04-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_prices', '0002_alter_salesprice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespricelistitem',
            name='salesprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
