# Generated by Django 5.0.2 on 2024-06-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_company_currency'),
        ('sales_prices', '0003_alter_salespricelistitem_salesprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespricelist',
            name='customers',
            field=models.ManyToManyField(to='contacts.company'),
        ),
    ]
