# Generated by Django 5.0.2 on 2024-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_company_currency'),
        ('sales_prices', '0004_alter_salespricelist_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespricelist',
            name='customers',
            field=models.ManyToManyField(blank=True, to='contacts.company'),
        ),
    ]
