# Generated by Django 5.0.2 on 2024-07-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_prices', '0005_alter_salespricelist_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespricelist',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='salespricelist',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
