# Generated by Django 5.0.7 on 2024-07-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_prices', '0006_salespricelist_end_date_salespricelist_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesprice',
            old_name='discount_amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='salesprice',
            old_name='amount',
            new_name='rrp',
        ),
        migrations.RenameField(
            model_name='salespricelist',
            old_name='discount',
            new_name='discount_auto',
        ),
        migrations.AddField(
            model_name='salespricelist',
            name='price_auto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
