# Generated by Django 5.0.7 on 2024-07-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_prices', '0008_alter_salesprice_rrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salespricelist',
            old_name='discount_auto',
            new_name='discount_pcnt',
        ),
        migrations.RenameField(
            model_name='salespricelist',
            old_name='price_auto',
            new_name='price_change_pcnt',
        ),
        migrations.RemoveField(
            model_name='salespricelist',
            name='auto_update',
        ),
        migrations.RemoveField(
            model_name='salespricelistitem',
            name='salesprice',
        ),
        migrations.AddField(
            model_name='salespricelist',
            name='auto_add_products',
            field=models.BooleanField(default=False, verbose_name='Auto add all products'),
        ),
        migrations.AddField(
            model_name='salespricelist',
            name='auto_update_prices',
            field=models.BooleanField(default=True, verbose_name='Auto Update Price and Discount Price'),
        ),
        migrations.AddField(
            model_name='salespricelistitem',
            name='discount_auto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salespricelistitem',
            name='discount_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salespricelistitem',
            name='price_auto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salespricelistitem',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salespricelist',
            name='vat_included',
            field=models.BooleanField(default=False, verbose_name='Price list includes VAT'),
        ),
    ]
