# Generated by Django 5.0.7 on 2024-07-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_alter_multitenantuser_timezone'),
        ('currencies', '0010_auto_20240724_1848'),
        ('products', '0024_remove_product_base_product_product_base_products'),
        ('sales_prices', '0010_alter_salespricelistitem_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesprice',
            constraint=models.CheckConstraint(check=models.Q(('rrp__gt', models.F('price'))), name='RRP cannot be less then the price'),
        ),
        migrations.AddConstraint(
            model_name='salesprice',
            constraint=models.CheckConstraint(check=models.Q(('rrp__gte', '0.01')), name='RRP cannot be 0'),
        ),
        migrations.AddConstraint(
            model_name='salesprice',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', '0.01')), name='Price cannot be 0'),
        ),
    ]
