# Generated by Django 5.0.7 on 2024-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_alter_multitenantuser_timezone'),
        ('currencies', '0009_currency_unique_iso_code_multi_tenant_company'),
        ('products', '0024_remove_product_base_product_product_base_products'),
        ('sales_prices', '0010_alter_salespricelistitem_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesprice',
            constraint=models.CheckConstraint(check=models.Q(('rrp__isnull', False), ('price__isnull', False), _connector='OR'), name='rrp_or_price'),
        ),
    ]
