# Generated by Django 5.0.7 on 2024-08-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_alter_multitenantuser_timezone'),
        ('currencies', '0010_auto_20240724_1848'),
        ('products', '0025_rename_always_on_stock_product_allow_backorder'),
        ('sales_prices', '0011_salesprice_rrp_cannot_be_less_then_the_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesprice',
            name='RRP cannot be less then the price',
        ),
        migrations.AddConstraint(
            model_name='salesprice',
            constraint=models.CheckConstraint(check=models.Q(('rrp__gte', models.F('price'))), name='RRP cannot be less then the price'),
        ),
    ]
