# Generated by Django 5.0.7 on 2024-08-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_prices', '0012_remove_salesprice_rrp_cannot_be_less_then_the_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespricelist',
            name='discount_pcnt',
            field=models.FloatField(blank=True, help_text='What percentage discount would you like to apply?  For a 20\\% discount, write 20', null=True),
        ),
        migrations.AlterField(
            model_name='salespricelist',
            name='price_change_pcnt',
            field=models.FloatField(
                blank=True, help_text='How would you like to influence the max price?  Write 20 to increase it with 20%.  Or -20 to decrease with 20\\%', null=True),
        ),
    ]
