# Generated by Django 5.1 on 2024-08-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_prices', '0013_alter_salespricelist_discount_pcnt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salespricelist',
            options={'ordering': ['id']},
        ),
    ]
