# Generated by Django 5.1 on 2024-08-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_prices', '0014_alter_salespricelist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salespricelist',
            options={'ordering': ['-id']},
        ),
    ]
