# Generated by Django 4.2.5 on 2023-09-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_shared_multi_tenant', '0002_multitenantcompany_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('bundle_variations', models.ManyToManyField(blank=True, related_name='bundles', through='products.BundleVariation', to='products.product')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_shared_multi_tenant.multitenantcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UmbrellaVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umbrellavariation_umbrellas', to='products.product')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umbrellavariation_variations', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('nl', 'Nederlands'), ('en-gb', 'English GB'),
                 ('en-us', 'English US'), ('fr', 'French'), ('de', 'German')], max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_shared_multi_tenant.multitenantcompany')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='umbrella_variations',
            field=models.ManyToManyField(blank=True, related_name='umbrellas', through='products.UmbrellaVariation', to='products.product'),
        ),
        migrations.AddField(
            model_name='bundlevariation',
            name='umbrella',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlevariation_umbrellas', to='products.product'),
        ),
        migrations.AddField(
            model_name='bundlevariation',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlevariation_variations', to='products.product'),
        ),
    ]
