# Generated by Django 4.2.6 on 2023-10-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('VARIATION', 'Product Variation'),
                 ('BUNDLE', 'Bundle Product'), ('UMBRELLA', 'Umbrella Product')], max_length=9)),
                ('always_on_stock', models.BooleanField(default=False)),
                ('bundle_variations', models.ManyToManyField(blank=True, related_name='bundles', through='products.BundleVariation', to='products.product')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.tax')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UmbrellaVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('umbrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umbrellavariation_umbrellas', to='products.product')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umbrellavariation_variations', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('NL', 'Dutch'), ('EN', 'English')], max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='umbrella_variations',
            field=models.ManyToManyField(blank=True, related_name='umbrellas', through='products.UmbrellaVariation', to='products.product'),
        ),
        migrations.AddField(
            model_name='bundlevariation',
            name='umbrella',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlevariation_umbrellas', to='products.product'),
        ),
        migrations.AddField(
            model_name='bundlevariation',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlevariation_variations', to='products.product'),
        ),
        migrations.CreateModel(
            name='BundleProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='UmbrellaProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
