# Generated by Django 4.2.5 on 2023-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='UmbrellaProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('VARIATION', 'Product Variation'), ('BUNDLE', 'Bundle Product'),
                                   ('UMBRELLA', 'Umbrella Product')], default='SIMPLE', max_length=9),
            preserve_default=False,
        ),
    ]
