# Generated by Django 4.2.5 on 2023-10-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='always_on_stock',
            field=models.BooleanField(default=False),
        ),
    ]
