# Generated by Django 5.0.2 on 2024-03-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_producttranslation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bundlevariation',
            unique_together={('umbrella', 'variation')},
        ),
        migrations.AlterUniqueTogether(
            name='umbrellavariation',
            unique_together={('umbrella', 'variation')},
        ),
    ]
