# Generated by Django 5.2 on 2025-04-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_producttranslation_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='url_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
