# Generated by Django 5.0.2 on 2024-04-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='taxes.vatrate'),
        ),
    ]
