# Generated by Django 5.2 on 2025-05-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_sku_alter_producttranslation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='alias_parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('BUNDLE', 'Bundle Product'), ('CONFIGURABLE', 'Configurable Product'),
                                   ('SIMPLE', 'Simple Product'), ('ALIAS', 'Alias Product')], max_length=15),
        ),
    ]
