# Generated by Django 5.0.2 on 2024-03-25 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_tax_rate'),
        ('taxes', '0003_vatrate_delete_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='taxes.vatrate'),
            preserve_default=False,
        ),
    ]
