# Generated by Django 5.0.2 on 2024-04-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240403_1052'),
        ('taxes', '0004_alter_vatrate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.vatrate'),
        ),
    ]
