# Generated by Django 5.2 on 2025-05-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_alias_requires_parent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='alias_requires_parent',
        ),
    ]
