# Generated by Django 5.0.2 on 2024-04-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_multitenantuser_timezone'),
        ('products', '0008_alter_product_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'multi_tenant_company')},
        ),
    ]
