# Generated by Django 5.2 on 2025-06-23 09:44

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('products', '0009_product_alias_requires_parent'),
        ('sales_channels', '0032_alter_saleschannelview_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('url_key', 'multi_tenant_company')},
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_translations', to='sales_channels.saleschannel'),
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('product', 'language', 'sales_channel'), ('url_key', 'multi_tenant_company')},
        ),
        migrations.CreateModel(
            name='ProductTranslationBulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the bullet point')),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('product_translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='products.producttranslation')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
