# Generated by Django 5.0.2 on 2024-04-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
