# Generated by Django 5.2.1 on 2025-06-05 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_alias_requires_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alias_parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alias_products', to='products.product'),
        ),
    ]
