# Generated by Django 5.2 on 2025-06-23 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_producttranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttranslationbulletpoint',
            options={'ordering': ['sort_order']},
        ),
        migrations.RenameField(
            model_name='producttranslationbulletpoint',
            old_name='order',
            new_name='sort_order',
        ),
    ]
