# Generated by Django 5.0.2 on 2024-05-31 12:12

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_remove_address_people_address_person'),
        ('core', '0078_alter_multitenantuser_timezone'),
        ('products', '0012_alter_producttranslation_language'),
        ('taxes', '0006_alter_vatrate_name'),
        ('units', '0002_auto_20240403_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='DropshipProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ManufacturableProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='base_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='supplier_products', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='production_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('BUNDLE', 'Bundle Product'), ('UMBRELLA', 'Umbrella Product'), ('MANUFACTURABLE', 'Manufacturable Product'),
                                   ('DROPSHIP', 'Dropship Product'), ('SUPPLIER', 'Supplier Product'), ('SIMPLE', 'Simple Product')], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxes.vatrate'),
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_components', to='products.product')),
                ('manufacturable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_manufacturables', to='products.product')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
            ],
            options={
                'unique_together': {('manufacturable', 'component')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='bom_variations',
            field=models.ManyToManyField(blank=True, related_name='manufacturables', through='products.BillOfMaterial', to='products.product'),
        ),
        migrations.CreateModel(
            name='SupplierPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.unit')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.supplierproduct')),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
