# Generated by Django 5.2 on 2025-06-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_producttranslationbulletpoint_text'),
        ('sales_channels', '0032_alter_saleschannelview_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('product', 'language', 'sales_channel')},
        ),
    ]
