# Generated by Django 5.2 on 2025-06-24 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('products', '0013_alter_producttranslation_unique_together'),
        ('sales_channels', '0032_alter_saleschannelview_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producttranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('url_key__isnull', False)), fields=('url_key', 'multi_tenant_company'), name='uniq_nonnull_url_key_per_company'),
        ),
    ]
