# Generated by Django 5.0.2 on 2024-06-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_supplierproduct_dropshipproduct_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billofmaterial',
            unique_together=set(),
        ),
    ]
