# Generated by Django 5.2 on 2025-06-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_producttranslation_uniq_nonnull_url_key_per_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='url_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
