# Generated by Django 5.0.2 on 2024-06-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_billofmaterial_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='manufacturable',
            new_name='umbrella',
        ),
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='component',
            new_name='variation',
        ),
    ]
