# Generated by Django 5.2 on 2025-07-09 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('products', '0015_alter_producttranslation_name_and_more'),
        ('sales_channels', '0037_alter_remoteproperty_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producttranslation',
            name='uniq_nonnull_url_key_per_company',
        ),
        migrations.AddConstraint(
            model_name='producttranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('sales_channel__isnull', False)), fields=('url_key', 'multi_tenant_company'), name='uniq_nonnull_url_key_per_company_for_default'),
        ),
    ]
