# Generated by Django 5.0.2 on 2024-06-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_manufacturable_billofmaterial_umbrella_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billofmaterial',
            unique_together={('umbrella', 'variation')},
        ),
    ]
