# Generated by Django 5.2 on 2025-07-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_producttranslation_uniq_nonnull_url_key_per_company_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producttranslation',
            name='uniq_nonnull_url_key_per_company_for_default',
        ),
    ]
