# Generated by Django 5.2 on 2025-07-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_alias_parent_product'),
        ('products', '0017_remove_producttranslation_uniq_nonnull_url_key_per_company_for_default'),
    ]

    operations = [
    ]
