# Generated by Django 5.0.2 on 2024-06-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_company_currency'),
        ('core', '0086_alter_multitenantuser_timezone'),
        ('products', '0017_alter_product_unique_together'),
        ('taxes', '0006_alter_vatrate_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('sku', 'supplier', 'multi_tenant_company'), name='unique_sku_with_supplier'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', True)), fields=('sku', 'multi_tenant_company'), name='unique_sku_without_supplier'),
        ),
    ]
