# Generated by Django 5.2 on 2025-08-07 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('products', '0018_merge_20250717_1208'),
        ('sales_channels', '0038_remove_saleschannelviewassign_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='producttranslation',
            constraint=models.UniqueConstraint(fields=('product', 'language', 'sales_channel'), name='uniq_product_language_sales_channel', nulls_distinct=False),
        ),
    ]
