# Generated by Django 5.2 on 2025-08-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_producttranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslationbulletpoint',
            name='text',
            field=models.CharField(max_length=1024),
        ),
    ]
