# Generated by Django 5.0.2 on 2024-06-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20240606_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='bundlevariation',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
