# Generated by Django 5.2 on 2025-09-04 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_multitenantcompany_active_and_more'),
        ('products', '0020_alter_producttranslationbulletpoint_text'),
        ('sales_channels', '0038_remove_saleschannelviewassign_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producttranslation',
            index=models.Index(fields=['product', 'language', 'sales_channel'], name='products_pr_product_fa6933_idx'),
        ),
    ]
