# Generated by Django 5.0.2 on 2024-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_alter_multitenantuser_timezone'),
        ('products', '0020_alter_billofmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('product', 'language'), ('url_key', 'multi_tenant_company')},
        ),
    ]
