# Generated by Django 5.2 on 2025-09-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_producttranslation_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
