# Generated by Django 5.0.2 on 2024-06-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_producttranslation_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_product',
        ),
        migrations.AddField(
            model_name='product',
            name='base_products',
            field=models.ManyToManyField(blank=True, related_name='supplier_products', to='products.product'),
        ),
    ]
