# Generated by Django 5.0.7 on 2024-07-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_base_product_product_base_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='always_on_stock',
            new_name='allow_backorder',
        ),
    ]
