# Generated by Django 5.0.7 on 2024-08-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_base_product_product_base_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umbrellavariation',
            old_name='umbrella',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='umbrellavariation',
            unique_together={('parent', 'variation')},
        ),
    ]
