# Generated by Django 5.0.7 on 2024-08-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rename_umbrella_umbrellavariation_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundlevariation',
            old_name='umbrella',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='bundlevariation',
            unique_together={('parent', 'variation')},
        ),
    ]
