# Generated by Django 5.0.7 on 2024-08-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_company_currency'),
        ('core', '0133_alter_multitenantuser_timezone'),
        ('products', '0025_rename_always_on_stock_product_allow_backorder'),
        ('taxes', '0006_alter_vatrate_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('sku__isnull', False), ('type', models.Value('SUPPLIER'))),
                                              name='Supplier products require an sku'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('supplier__isnull', False), ('type', models.Value('SUPPLIER'))),
                                              name='Supplier products require a Supplier'),
        ),
    ]
