# Generated by Django 5.0.7 on 2024-08-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rename_always_on_stock_product_allow_backorder'),
        ('products', '0028_rename_umbrella_variations_product_configurable_variations_and_more'),
    ]

    operations = [
    ]
