# Generated by Django 5.0.7 on 2024-08-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_sku_required_for_supplier_product_and_more'),
        ('products', '0029_merge_20240806_1619'),
    ]

    operations = [
    ]
