# Generated by Django 5.0.7 on 2024-08-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20240810_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='umbrella',
            new_name='parent',
        ),
    ]
