# Generated by Django 5.0.7 on 2024-08-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20240810_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_through_parents', to='products.product'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_through_variations', to='products.product'),
        ),
        migrations.AlterField(
            model_name='bundlevariation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlevariation_parents', to='products.product'),
        ),
        migrations.AlterField(
            model_name='configurablevariation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurablevariation_parents', to='products.product'),
        ),
        migrations.AlterField(
            model_name='configurablevariation',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurablevariation_variations', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='configurable_variations',
            field=models.ManyToManyField(blank=True, related_name='configurables', through='products.ConfigurableVariation', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('BUNDLE', 'Bundle Product'), ('CONFIGURABLE', 'Configurable Product'), ('MANUFACTURABLE', 'Manufacturable Product'), (
                'DROPSHIP', 'Dropship Product'), ('SUPPLIER', 'Supplier Product'), ('SIMPLE', 'Simple Product')], max_length=15),
        ),
    ]
