# Generated by Django 5.0.7 on 2024-08-10 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_billofmaterial_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlevariation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlevariation_through_parents', to='products.product'),
        ),
        migrations.AlterField(
            model_name='bundlevariation',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlevariation_through_variations', to='products.product'),
        ),
        migrations.AlterField(
            model_name='configurablevariation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurablevariation_through_parents', to='products.product'),
        ),
        migrations.AlterField(
            model_name='configurablevariation',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='configurablevariation_through_variations', to='products.product'),
        ),
    ]
