# Generated by Django 5.0.7 on 2024-08-10 14:50

from django.db import migrations


def migrate_umbrella_to_configurable(apps, schema_editor):
    Product = apps.get_model('products', 'Product')

    for config in Product.objects.filter(type='UMBRELLA').iterator():
        config.type = "CONFIGURABLE"


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_bundlevariation_parent_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_umbrella_to_configurable)
    ]
