# Generated by Django 5.1.1 on 2025-02-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_rename_supplierprices_supplierprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierprice',
            name='created_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='supplierprice',
            name='last_update_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='supplierprice',
            name='multi_tenant_company',
        ),
        migrations.RemoveField(
            model_name='supplierprice',
            name='supplier_product',
        ),
        migrations.RemoveField(
            model_name='supplierprice',
            name='unit',
        ),
        migrations.DeleteModel(
            name='SupplierProduct',
        ),
        migrations.DeleteModel(
            name='SupplierPrice',
        ),
    ]
