# Generated by Django 5.1.1 on 2025-02-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_remove_supplierprice_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billofmaterial',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='created_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='last_update_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='multi_tenant_company',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bom_variations',
        ),
        migrations.DeleteModel(
            name='DropshipProduct',
        ),
        migrations.DeleteModel(
            name='ManufacturableProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='production_time',
        ),
        migrations.DeleteModel(
            name='BillOfMaterial',
        ),
    ]
