# Generated by Django 5.1.1 on 2025-02-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_billofmaterial_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_sku_with_supplier',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_sku_without_supplier',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='sku_required_for_supplier_product',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='supplier_required_for_supplier_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('BUNDLE', 'Bundle Product'), ('CONFIGURABLE', 'Configurable Product'), ('SIMPLE', 'Simple Product')], max_length=15),
        ),
    ]
