# Generated by Django 5.1.1 on 2025-02-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_demodatarelation_created_by_multi_tenant_user_and_more'),
        ('products', '0040_remove_product_unique_sku_with_supplier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'multi_tenant_company')},
        ),
    ]
