# Generated by Django 5.1.1 on 2025-02-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_alter_product_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
    ]
