# Generated by Django 5.1.1 on 2025-02-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_remove_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='for_sale',
        ),
    ]
