from .products import MagentoProductSyncFactory, MagentoProductCreateFactory, MagentoProductDeleteFactory, MagentoProductUpdateFactory
from .variations import MagentoProductVariationAddFactory
from .content import MagentoProductContentUpdateFactory
from .eancodes import MagentoEanCodeUpdateFactory
from .assigns import MagentoSalesChannelViewAssignUpdateFactory
from .images import MagentoImageDeleteFactory, MagentoMediaProductThroughCreateFactory, MagentoMediaProductThroughUpdateFactory, MagentoMediaProductThroughDeleteFactory