# Generated by Django 5.2 on 2025-07-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaysaleschannel',
            name='access_token',
            field=models.CharField(blank=True, help_text='Access token for API requests.', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='ebaysaleschannel',
            name='refresh_token',
            field=models.CharField(blank=True, help_text='Refresh token used to generate new access tokens.', max_length=2048, null=True),
        ),
    ]
