# Generated by Django 5.2 on 2025-07-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_alter_ebaysaleschannel_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaysaleschannel',
            name='access_token',
            field=models.CharField(blank=True, help_text='Access token for API requests.', max_length=4096, null=True),
        ),
    ]
