# Generated by Django 5.2 on 2025-09-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0006_ebaysaleschannelview_default_category_tree_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ebaypropertyselectvalue',
            unique_together={('ebay_property', 'marketplace', 'localized_value')},
        ),
    ]
