# Generated by Django 5.2 on 2025-09-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0007_ebaysaleschannelview_default_category_tree_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebayproducttypeitem',
            old_name='remote_property',
            new_name='ebay_property',
        ),
    ]
