# Generated by Django 5.2 on 2025-09-23 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_multitenantcompany_active_and_more'),
        ('ebay', '0009_ebaysaleschannelimport_and_more'),
        ('properties', '0017_alter_propertyselectvalue_options'),
        ('sales_channels', '0040_remove_remoteproduct_unique_remote_sku_per_channel_if_present_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ebayproducttype',
            name='unique_ebayproducttype_remote_id_per_channel',
        ),
        migrations.RenameField(
            model_name='ebayinternalproperty',
            old_name='label',
            new_name='name',
        ),
        migrations.AddField(
            model_name='ebayproducttype',
            name='marketplace',
            field=models.ForeignKey(help_text='Marketplace in which this category applies.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='ebay.ebaysaleschannelview'),
        ),
        migrations.AddConstraint(
            model_name='ebayproducttype',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_id__isnull', False)), fields=('marketplace', 'remote_id'), name='unique_ebayproducttype_remote_id_per_marketplace'),
        ),
    ]
