# Generated by Django 5.2 on 2025-09-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0010_remove_ebayproducttype_unique_ebayproducttype_remote_id_per_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayproducttype',
            name='marketplace',
            field=models.ForeignKey(default=1, help_text='Marketplace in which this category applies.', on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='ebay.ebaysaleschannelview'),
            preserve_default=False,
        ),
    ]
