# Generated by Django 5.2 on 2025-09-23 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_multitenantcompany_active_and_more'),
        ('ebay', '0011_alter_ebayproducttype_marketplace'),
        ('properties', '0017_alter_propertyselectvalue_options'),
        ('sales_channels', '0040_remove_remoteproduct_unique_remote_sku_per_channel_if_present_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ebayproducttype',
            name='unique_ebayproducttype_local_rule_per_channel',
        ),
        migrations.AddConstraint(
            model_name='ebayproducttype',
            constraint=models.UniqueConstraint(condition=models.Q(('local_instance__isnull', False)), fields=('sales_channel', 'marketplace', 'local_instance'), name='unique_ebayproducttype_local_rule_per_channel'),
        ),
    ]
