# Generated by Django 5.2 on 2025-09-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0012_remove_ebayproducttype_unique_ebayproducttype_local_rule_per_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_default_tree_id', models.CharField(db_index=True, max_length=50)),
                ('remote_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ('marketplace_default_tree_id', 'name'),
                'unique_together': {('marketplace_default_tree_id', 'remote_id')},
            },
        ),
    ]
