# Generated by Django 5.2 on 2025-10-09 12:12

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_multitenantcompany_active_and_more'),
        ('ebay', '0013_ebaycategory'),
        ('properties', '0017_alter_propertyselectvalue_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayInternalPropertyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='Remote enumeration value expected by eBay.', max_length=64)),
                ('label', models.CharField(help_text='Human readable label presented to users.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description explaining when to use this value.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order for this option.')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to hide the option from selection lists without deleting it.')),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('internal_property', models.ForeignKey(help_text='Internal property this option belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ebay.ebayinternalproperty')),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('local_instance', models.ForeignKey(blank=True, help_text='Optional link to a local property select value mapped to this option.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyselectvalue')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('sales_channel', models.ForeignKey(help_text='Sales channel that owns this option.', on_delete=django.db.models.deletion.CASCADE, related_name='internal_property_options', to='ebay.ebaysaleschannel')),
            ],
            options={
                'verbose_name': 'eBay Internal Property Option',
                'verbose_name_plural': 'eBay Internal Property Options',
                'ordering': ('sort_order', 'label'),
                'unique_together': {('internal_property', 'value')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
    ]
