# Generated by Django 5.2 on 2025-10-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0015_ebayproductoffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebaycategory',
            options={'ordering': ('marketplace_default_tree_id', 'full_name')},
        ),
        migrations.RenameField(
            model_name='ebaycategory',
            old_name='name',
            new_name='full_name',
        ),
    ]
