# Generated by Django 5.2 on 2025-10-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0016_alter_ebaycategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaycategory',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebaycategory',
            name='is_root',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ebaycategory',
            name='name',
            field=models.CharField(default='Name', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebaycategory',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='ebay.ebaycategory'),
        ),
    ]
