# Generated by Django 5.2 on 2025-10-29 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0018_ebayproductcategory'),
        ('properties', '0017_alter_propertyselectvalue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayproducttype',
            name='local_instance',
            field=models.ForeignKey(blank=True, help_text='Local product type rule associated with this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.productpropertiesrule'),
        ),
    ]
