# Generated by Django 5.2 on 2025-11-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0019_alter_ebayproducttype_local_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaycategory',
            name='configurator_properties',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
