# Generated by Django 5.2 on 2025-11-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0020_ebaycategory_configurator_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaysaleschannelimport',
            name='content_class',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
