# Generated by Django 5.2 on 2026-02-04 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('ebay', '0021_ebaysaleschannelimport_content_class'),
        ('products', '0023_producttranslation_subtitle'),
        ('properties', '0018_alter_productpropertiesrule_unique_together_and_more'),
        ('sales_channels', '0061_remoteproductcontent_content_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ebayproductcategory',
            index=models.Index(fields=['product', 'view'], name='ebay_ebaypr_product_794989_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayproducttypeitem',
            index=models.Index(fields=['product_type', 'ebay_property'], name='ebay_ebaypr_product_e306db_idx'),
        ),
        migrations.AddIndex(
            model_name='ebaypropertyselectvalue',
            index=models.Index(fields=['ebay_property', 'marketplace', 'local_instance'], name='ebay_ebaypr_ebay_pr_8d8a8e_idx'),
        ),
    ]
