# Generated by Django 5.2 on 2026-02-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0022_ebayproductcategory_ebay_ebaypr_product_794989_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaypropertyselectvalue',
            name='bool_value',
            field=models.BooleanField(blank=True, help_text='Boolean meaning for this option when mapping select/multiselect remote values to boolean.', null=True),
        ),
    ]
