# Generated by Django 5.2 on 2026-02-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0023_ebaypropertyselectvalue_bool_value'),
        ('sales_channels', '0065_remoteproperty_type_remote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebayproperty',
            name='type',
        ),
    ]
