# Generated by Django 5.2 on 2026-02-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0025_remove_ebayproperty_allows_unmapped_values'),
        ('properties', '0019_productpropertiesruleitem_properties__rule_id_884958_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaypropertyselectvalue',
            name='local_instance',
            field=models.ForeignKey(blank=True, help_text='Optional link to the local PropertySelectValue.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyselectvalue'),
        ),
    ]
