# Generated by Django 5.2 on 2026-02-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0026_alter_ebaypropertyselectvalue_local_instance'),
        ('properties', '0019_productpropertiesruleitem_properties__rule_id_884958_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayinternalproperty',
            name='local_instance',
            field=models.ForeignKey(blank=True, help_text='Local property associated with this internal eBay field.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
    ]
