# Generated by Codex on 2026-02-23

from django.db import migrations
from django.utils import timezone


EBAY_DOCUMENT_TYPE_DEFAULTS = [
    {
        "value": "CERTIFICATE_OF_ANALYSIS",
        "name": "Certificate of Analysis",
        "description": (
            "This document is provided by the manufacturer or a qualified third-party "
            "laboratory and confirms the product was tested and meets the specified criteria."
        ),
    },
    {
        "value": "CERTIFICATE_OF_CONFORMITY",
        "name": "Certificate of Conformity",
        "description": (
            "This certificate is issued by a manufacturer or a certification body to "
            "declare that a product meets all required safety and regulatory standards."
        ),
    },
    {
        "value": "DECLARATION_OF_CONFORMITY",
        "name": "Declaration of Conformity",
        "description": (
            "This document is self-issued by a manufacturer declaring the product "
            "complies with GPSR and other relevant requirements, regulations, and standards."
        ),
    },
    {
        "value": "INSTRUCTIONS_FOR_USE",
        "name": "Instructions for Use",
        "description": (
            "These are detailed directions provided by the manufacturer that explain how "
            "consumers should use the product correctly and safely."
        ),
    },
    {
        "value": "OTHER_SAFETY_DOCUMENTS",
        "name": "Other Safety Documents",
        "description": (
            "Additional safety documentation such as warnings, emergency procedures, "
            "safe storage and handling guidance, or other safety information not covered "
            "by other categories."
        ),
    },
    {
        "value": "SAFETY_DATA_SHEET",
        "name": "Safety Data Sheet",
        "description": (
            "A detailed document describing chemical product properties, hazards "
            "(health, fire, reactivity, environmental), safe handling practices, and "
            "emergency control measures."
        ),
    },
    {
        "value": "TROUBLE_SHOOTING_GUIDE",
        "name": "Trouble Shooting Guide",
        "description": (
            "A guide that helps users diagnose and resolve problems they may encounter "
            "with a product."
        ),
    },
    {
        "value": "USER_GUIDE_OR_MANUAL",
        "name": "User Guide or Manual",
        "description": (
            "A comprehensive resource containing the information consumers need to "
            "understand and operate the product."
        ),
    },
    {
        "value": "INSTALLATION_INSTRUCTIONS",
        "name": "Installation Instructions",
        "description": (
            "Step-by-step instructions provided by the manufacturer that explain how to "
            "properly install a product."
        ),
    },
    {
        "value": "ACCESSIBILITY_INFORMATION",
        "name": "Accessibility Information",
        "description": (
            "Details about product accessibility features to support use by individuals "
            "with disabilities or special needs."
        ),
    },
]


def populate_ebay_document_types(apps, schema_editor):
    EbaySalesChannel = apps.get_model("ebay", "EbaySalesChannel")
    EbayDocumentType = apps.get_model("ebay", "EbayDocumentType")
    RemoteDocumentType = apps.get_model("sales_channels", "RemoteDocumentType")
    ContentType = apps.get_model("contenttypes", "ContentType")

    ebay_document_type_ct = ContentType.objects.get_for_model(EbayDocumentType)

    now = timezone.now()

    for sales_channel in EbaySalesChannel.objects.all().only("id", "multi_tenant_company_id").iterator():
        for definition in EBAY_DOCUMENT_TYPE_DEFAULTS:
            remote_id = str(definition.get("value") or "").strip()
            if not remote_id:
                continue

            defaults = {
                "multi_tenant_company_id": sales_channel.multi_tenant_company_id,
                "name": definition.get("name"),
                "description": definition.get("description"),
                "created_at": now,
                "updated_at": now,
            }

            document_type, created = EbayDocumentType.objects.get_or_create(
                sales_channel_id=sales_channel.id,
                remote_id=remote_id,
                defaults=defaults,
            )

            if created:
                continue

            updates = {}
            if document_type.multi_tenant_company_id != sales_channel.multi_tenant_company_id:
                updates["multi_tenant_company_id"] = sales_channel.multi_tenant_company_id

            expected_name = definition.get("name")
            if document_type.name != expected_name:
                updates["name"] = expected_name

            expected_description = definition.get("description")
            if document_type.description != expected_description:
                updates["description"] = expected_description

            if updates:
                updates["updated_at"] = now
                EbayDocumentType.objects.filter(pk=document_type.pk).update(**updates)

            if document_type.polymorphic_ctype_id != ebay_document_type_ct.id:
                RemoteDocumentType.objects.filter(pk=document_type.pk).update(
                    polymorphic_ctype_id=ebay_document_type_ct.id
                )

    ebay_document_type_ids = EbayDocumentType.objects.values_list("id", flat=True)
    RemoteDocumentType.objects.filter(
        id__in=ebay_document_type_ids
    ).exclude(
        polymorphic_ctype_id=ebay_document_type_ct.id
    ).update(
        polymorphic_ctype_id=ebay_document_type_ct.id
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ebay", "0028_ebaydocumenttype"),
    ]

    operations = [
        migrations.RunPython(
            populate_ebay_document_types,
            migrations.RunPython.noop,
        ),
    ]
