# Generated by Django 5.2 on 2026-02-23 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0030_fix_ebay_document_types_polymorphic_ctype'),
        ('sales_channels', '0077_remoteproductcategory_legacy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayProductCategoryNew',
            fields=[
                ('remoteproductcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproductcategory')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteproductcategory',),
        ),
    ]
