# Generated by Django 5.2 on 2026-02-24 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('ebay', '0032_populate_ebayproductcategorynew'),
        ('products', '0023_producttranslation_subtitle'),
        ('sales_channels', '0077_remoteproductcategory_legacy_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EbayProductCategory',
            new_name='EbayProductCategoryOld',
        ),
        migrations.RenameIndex(
            model_name='ebayproductcategoryold',
            new_name='ebay_ebaypr_product_8f1a3f_idx',
            old_name='ebay_ebaypr_product_794989_idx',
        ),
    ]
