# Generated by Django 5.2 on 2026-02-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0033_rename_ebayproductcategory_ebayproductcategoryold_and_more'),
        ('sales_channels', '0077_remoteproductcategory_legacy_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EbayProductCategoryNew',
            new_name='EbayProductCategory',
        ),
    ]
