# Generated by Django 5.2 on 2026-02-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0034_rename_ebayproductcategorynew_ebayproductcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebayproductcategory',
            options={'verbose_name': 'eBay Product Category', 'verbose_name_plural': 'eBay Product Categories'},
        ),
    ]
