# Generated by Django 5.2 on 2026-02-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0035_alter_ebayproductcategory_options'),
        ('sales_channels', '0078_remotedocument_remotedocumentproductassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayDocumentThroughProduct',
            fields=[
                ('remotedocumentproductassociation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotedocumentproductassociation')),
            ],
            options={
                'verbose_name': 'eBay Document Through Product',
                'verbose_name_plural': 'eBay Documents Through Products',
            },
            bases=('sales_channels.remotedocumentproductassociation',),
        ),
        migrations.CreateModel(
            name='EbayRemoteDocument',
            fields=[
                ('remotedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotedocument')),
                ('status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PENDING_UPLOAD', 'Pending Upload'), ('EXPIRED', 'Expired')], max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'eBay Remote Document',
                'verbose_name_plural': 'eBay Remote Documents',
            },
            bases=('sales_channels.remotedocument',),
        ),
    ]
