# Generated by Django 5.2 on 2026-03-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0036_ebaydocumentthroughproduct_ebayremotedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayproductcategory',
            name='secondary_category_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
