# Generated by Django 5.2 on 2026-03-06 19:58

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('ebay', '0037_ebayproductcategory_secondary_category_id'),
        ('products', '0023_producttranslation_subtitle'),
        ('sales_channels', '0081_remove_remotedocument_remote_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayStoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True)),
                ('successfully_created', models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.')),
                ('outdated', models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.')),
                ('outdated_since', models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('is_leaf', models.BooleanField(default=False)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ebay.ebaystorecategory')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel')),
            ],
            options={
                'verbose_name': 'eBay Store Category',
                'verbose_name_plural': 'eBay Store Categories',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EbayProductStoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_store_categories', to='products.product')),
                ('primary_store_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_product_store_categories', to='ebay.ebaystorecategory')),
                ('secondary_store_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_product_store_categories', to='ebay.ebaystorecategory')),
            ],
            options={
                'verbose_name': 'eBay Product Store Category',
                'verbose_name_plural': 'eBay Product Store Categories',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='ebaystorecategory',
            index=models.Index(fields=['sales_channel', 'remote_id'], name='ebay_ebayst_sales_c_129671_idx'),
        ),
        migrations.AddIndex(
            model_name='ebaystorecategory',
            index=models.Index(fields=['sales_channel', 'parent'], name='ebay_ebayst_sales_c_6e42ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ebaystorecategory',
            unique_together={('sales_channel', 'remote_id')},
        ),
        migrations.AddIndex(
            model_name='ebayproductstorecategory',
            index=models.Index(fields=['product'], name='ebay_ebaypr_product_c63f60_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayproductstorecategory',
            index=models.Index(fields=['primary_store_category'], name='ebay_ebaypr_primary_1f117c_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayproductstorecategory',
            index=models.Index(fields=['secondary_store_category'], name='ebay_ebaypr_seconda_58330d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ebayproductstorecategory',
            unique_together={('product', 'primary_store_category', 'secondary_store_category')},
        ),
    ]
