# Generated by Django 5.2 on 2026-03-06 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('ebay', '0038_ebaystorecategory_ebayproductstorecategory_and_more'),
        ('products', '0023_producttranslation_subtitle'),
        ('sales_channels', '0081_remove_remotedocument_remote_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ebayproductstorecategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ebayproductstorecategory',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebay_product_store_categories', to='sales_channels.saleschannel'),
        ),
        migrations.AddIndex(
            model_name='ebayproductstorecategory',
            index=models.Index(fields=['product', 'sales_channel'], name='ebay_ebaypr_product_cddc20_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayproductstorecategory',
            index=models.Index(fields=['sales_channel'], name='ebay_ebaypr_sales_c_1c1adc_idx'),
        ),
        migrations.AddConstraint(
            model_name='ebayproductstorecategory',
            constraint=models.UniqueConstraint(fields=('product', 'sales_channel'), name='ebay_product_store_category_unique_product_sales_channel'),
        ),
    ]
