# Generated by Django 5.2 on 2025-05-07 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_channels', '0022_alter_saleschannelview_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoocommerceProduct',
            fields=[
                ('remoteproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                 parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproduct')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteproduct',),
        ),
        migrations.CreateModel(
            name='WoocommerceSalesChannel',
            fields=[
                ('saleschannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                 parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannel')),
                ('api_url', models.URLField(help_text='Woocommerce API URL')),
                ('api_key', models.CharField(help_text='Woocommerce API Key', max_length=255)),
                ('api_secret', models.CharField(help_text='Woocommerce API Secret', max_length=255)),
                ('api_version', models.CharField(choices=[('wc/v3', 'Woocommerce API v3')], help_text='Woocommerce API Version', max_length=5)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.saleschannel',),
        ),
    ]
