# Generated by Django 5.2 on 2025-05-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0022_alter_saleschannelview_name'),
        ('woocommerce', '0002_woocommerceattribute_woocommerceattributeselectvalue_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WoocommerceAttribute',
            new_name='WoocommerceGlobalAttribute',
        ),
        migrations.RemoveField(
            model_name='woocommercebrand',
            name='created_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='woocommercebrand',
            name='last_update_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='woocommercebrand',
            name='multi_tenant_company',
        ),
        migrations.RemoveField(
            model_name='woocommercebrand',
            name='sales_channel',
        ),
        migrations.RemoveField(
            model_name='woocommerceproduct',
            name='remoteproduct_ptr',
        ),
        migrations.RemoveField(
            model_name='woocommerceproductproperty',
            name='remoteproductproperty_ptr',
        ),
        migrations.DeleteModel(
            name='WoocommerceAttributeSelectValue',
        ),
        migrations.DeleteModel(
            name='WoocommerceBrand',
        ),
        migrations.DeleteModel(
            name='WoocommerceProduct',
        ),
        migrations.DeleteModel(
            name='WoocommerceProductProperty',
        ),
    ]
