# Generated by Django 5.2 on 2025-05-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0022_alter_saleschannelview_name'),
        ('woocommerce', '0004_woocommercesaleschannelview'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoocommerceGlobalAttributeValue',
            fields=[
                ('remotepropertyselectvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                 parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotepropertyselectvalue')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotepropertyselectvalue',),
        ),
    ]
