# Generated by Django 5.2.1 on 2025-05-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0022_alter_saleschannelview_name'),
        ('woocommerce', '0007_woocommerceproductproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoocommerceEanCode',
            fields=[
                ('remoteeancode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                 parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteeancode')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteeancode',),
        ),
    ]
