# Generated by Django 5.2.1 on 2025-05-21 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0029_saleschannel_mark_for_delete'),
        ('woocommerce', '0010_woocommerceremotelanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoocommercePrice',
            fields=[
                ('remoteprice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                 parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteprice')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteprice',),
        ),
    ]
