# Generated by Django 5.2.1 on 2025-05-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0012_woocommerceproductcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woocommercecurrency',
            options={'verbose_name_plural': 'Woocommerce Currencies'},
        ),
        migrations.AlterModelOptions(
            name='woocommerceglobalattribute',
            options={'verbose_name_plural': 'Woocommerce Product Properties'},
        ),
    ]
