# Generated by Django 5.2.1 on 2025-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0013_alter_woocommercecurrency_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woocommercesaleschannel',
            name='api_url',
        ),
        migrations.AlterField(
            model_name='woocommercesaleschannel',
            name='api_version',
            field=models.CharField(choices=[('wc/v3', 'Woocommerce API v3')], default='wc/v3', help_text='Woocommerce API Version', max_length=5),
        ),
    ]
