# Generated by Django 5.2 on 2025-08-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0014_remove_woocommercesaleschannel_api_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woocommercesaleschannel',
            options={},
        ),
    ]
