# Generated by Django 5.1.1 on 2024-09-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='verify_ssl',
            field=models.BooleanField(default=True),
        ),
    ]
