# Generated by Django 5.1.1 on 2025-03-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleschannel',
            name='sync_orders_after',
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='sync_ean_codes',
            field=models.BooleanField(default=True, verbose_name='Sync EAN Codes'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='sync_prices',
            field=models.BooleanField(default=True, verbose_name='Sync Prices'),
        ),
    ]
