# Generated by Django 5.1.1 on 2025-03-09 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0003_remoteeancode'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproduct',
            name='syncing_current_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Current sync progress percentage (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
