# Generated by Django 5.1.1 on 2024-09-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0003_saleschannel_requests_per_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotetaskqueue',
            name='retry',
            field=models.IntegerField(default=0),
        ),
    ]
