# Generated by Django 5.1.1 on 2024-09-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0004_remotetaskqueue_retry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotetaskqueue',
            name='task_args',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remotetaskqueue',
            name='task_kwargs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
