# Generated by Django 5.1.1 on 2025-03-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0004_remoteproduct_syncing_current_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='first_import_complete',
            field=models.BooleanField(default=False, help_text='Set to True once the first import has been completed.'),
        ),
        migrations.AlterField(
            model_name='importprocess',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('processing', 'Processing'), ('success', 'Success')], default='failed', max_length=10),
        ),
    ]
