# Generated by Django 5.1.1 on 2024-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0005_alter_remotetaskqueue_task_args_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotelog',
            name='related_object_str',
            field=models.CharField(blank=True, help_text='String representation of the related object.', max_length=556, null=True),
        ),
        migrations.AlterField(
            model_name='remotelog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
