# Generated by Django 5.1.1 on 2024-09-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_address_created_by_multi_tenant_user_and_more'),
        ('currencies', '0011_currency_created_by_multi_tenant_user_and_more'),
        ('media', '0006_media_created_by_multi_tenant_user_and_more'),
        ('orders', '0010_order_created_by_multi_tenant_user_and_more'),
        ('products', '0036_billofmaterial_created_by_multi_tenant_user_and_more'),
        ('properties', '0021_productpropertiesrule_created_by_multi_tenant_user_and_more'),
        ('sales_channels', '0006_remotelog_related_object_str_and_more'),
        ('taxes', '0007_vatrate_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecurrency',
            name='local_instance',
            field=models.ForeignKey(help_text='The local currency instance associated with this remote currency.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='remotecustomer',
            name='local_instance',
            field=models.ForeignKey(help_text='The local customer associated with this remote customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customer'),
        ),
        migrations.AlterField(
            model_name='remoteimage',
            name='local_instance',
            field=models.ForeignKey(help_text='The local media instance associated with this remote image.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media'),
        ),
        migrations.AlterField(
            model_name='remoteimageproductassociation',
            name='local_instance',
            field=models.ForeignKey(help_text='The local MediaProductThrough instance associated with this remote association.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediaproductthrough'),
        ),
        migrations.AlterField(
            model_name='remoteorder',
            name='local_instance',
            field=models.ForeignKey(help_text='The local order associated with this remote order.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='remoteproduct',
            name='local_instance',
            field=models.ForeignKey(help_text='The local Product instance associated with this remote product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='remoteproductproperty',
            name='local_instance',
            field=models.ForeignKey(help_text='The local ProductProperty instance associated with this remote property.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.productproperty'),
        ),
        migrations.AlterField(
            model_name='remoteproperty',
            name='local_instance',
            field=models.ForeignKey(help_text='The local property associated with this remote property.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='remotepropertyselectvalue',
            name='local_instance',
            field=models.ForeignKey(help_text='The local PropertySelectValue associated with this remote value.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyselectvalue'),
        ),
        migrations.AlterField(
            model_name='remotevat',
            name='local_instance',
            field=models.ForeignKey(help_text='The local VAT rate instance associated with this remote VAT.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxes.vatrate'),
        ),
    ]
