# Generated by Django 5.1.1 on 2025-03-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0007_importcurrency_importimage_importproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importproperty',
            name='remote_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_channels.remoteproperty'),
        ),
    ]
