# Generated by Django 5.1.1 on 2025-03-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0008_alter_importproperty_remote_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importpropertyselectvalue',
            name='remote_property_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_channels.remotepropertyselectvalue'),
        ),
    ]
