# Generated by Django 5.1.1 on 2024-09-09 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0021_productpropertiesrule_created_by_multi_tenant_user_and_more'),
        ('sales_channels', '0008_alter_remoteproductproperty_local_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotelog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='remoteproductproperty',
            name='local_instance',
            field=models.ForeignKey(help_text='The local ProductProperty instance associated with this remote property.', on_delete=django.db.models.deletion.CASCADE, to='properties.productproperty'),
        ),
        migrations.AlterField(
            model_name='remoteproperty',
            name='local_instance',
            field=models.ForeignKey(help_text='The local property associated with this remote property.', on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='remotepropertyselectvalue',
            name='local_instance',
            field=models.ForeignKey(help_text='The local PropertySelectValue associated with this remote value.', on_delete=django.db.models.deletion.CASCADE, to='properties.propertyselectvalue'),
        ),
    ]
