# Generated by Django 5.1.1 on 2025-03-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0009_alter_importpropertyselectvalue_remote_property_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importproduct',
            name='remote_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_channels.remoteproduct'),
        ),
    ]
