# Generated by Django 5.1.1 on 2025-04-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0010_alter_importproduct_remote_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importcurrency',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='The structured data after processing the raw data.', null=True),
        ),
        migrations.AlterField(
            model_name='importimage',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='The structured data after processing the raw data.', null=True),
        ),
        migrations.AlterField(
            model_name='importproduct',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='The structured data after processing the raw data.', null=True),
        ),
        migrations.AlterField(
            model_name='importproperty',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='The structured data after processing the raw data.', null=True),
        ),
        migrations.AlterField(
            model_name='importpropertyselectvalue',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='The structured data after processing the raw data.', null=True),
        ),
        migrations.AlterField(
            model_name='importvat',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='The structured data after processing the raw data.', null=True),
        ),
    ]
