# Generated by Django 5.1.1 on 2024-09-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0011_currency_created_by_multi_tenant_user_and_more'),
        ('sales_channels', '0011_remoteorderitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remotecurrency',
            unique_together={('local_instance', 'sales_channel')},
        ),
        migrations.AddField(
            model_name='remotecurrency',
            name='remote_code',
            field=models.CharField(default='', help_text='The currency code in the remote system.', max_length=10),
            preserve_default=False,
        ),
    ]
