# Generated by Django 5.1.1 on 2025-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0011_alter_importcurrency_structured_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='is_importing',
            field=models.BooleanField(default=False, help_text='True while an import process is running.'),
        ),
    ]
