# Generated by Django 5.2 on 2025-04-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0012_saleschannel_is_importing'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='import_orders',
            field=models.BooleanField(default=True, verbose_name='Import Orders'),
        ),
    ]
