# Generated by Django 5.1.1 on 2024-09-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0013_remoteproductconfigurator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remoteproductconfigurator',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='remoteproductproperty',
            name='remote_value',
            field=models.TextField(blank=True, help_text='The value of this property in the remote system, stored as a string.', null=True),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='sync_contents',
            field=models.BooleanField(default=False, verbose_name='Sync Contents'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='sync_orders_after',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sync Orders After Date'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='use_configurable_name',
            field=models.BooleanField(default=False, verbose_name='Always use Configurable name over child'),
        ),
        migrations.RemoveField(
            model_name='remoteproductconfigurator',
            name='remote_product',
        ),
    ]
