# Generated by Django 5.1.1 on 2024-09-17 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0014_alter_remoteproductconfigurator_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproductconfigurator',
            name='remote_product',
            field=models.OneToOneField(default=1, help_text='The remote product associated with this configurator.', on_delete=django.db.models.deletion.CASCADE, related_name='configurator', to='sales_channels.remoteproduct'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='remoteproductconfigurator',
            unique_together={('remote_product',)},
        ),
    ]
