# Generated by Django 5.2 on 2025-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0014_alter_remotelanguage_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecurrency',
            name='remote_code',
            field=models.CharField(help_text='The currency code in the remote system.', max_length=64),
        ),
        migrations.AlterField(
            model_name='remotelanguage',
            name='remote_code',
            field=models.CharField(help_text='The language code in the remote system.', max_length=64),
        ),
    ]
