# Generated by Django 5.2 on 2025-04-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0015_alter_remotecurrency_remote_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remotecurrency',
            unique_together=set(),
        ),
    ]
