# Generated by Django 5.2 on 2025-04-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0016_alter_remotecurrency_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleschannelview',
            name='active',
        ),
    ]
