# Generated by Django 5.1.7 on 2025-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0017_remove_saleschannelview_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotelanguage',
            name='local_instance',
            field=models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'French')], default='en', help_text='The local language code associated with this remote language.', max_length=7),
        ),
    ]
