# Generated by Django 5.1.1 on 2024-09-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0019_alter_remoteinventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price of the product in the remote system.', max_digits=10, null=True),
        ),
    ]
