# Generated by Django 5.1.1 on 2024-09-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0020_alter_remoteprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleschannel',
            name='sync_contents',
            field=models.BooleanField(default=True, verbose_name='Sync Contents'),
        ),
    ]
