# Generated by Django 5.2 on 2025-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0020_alter_remotelanguage_local_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteprice',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='remoteprice',
            name='price',
        ),
        migrations.AddField(
            model_name='remoteprice',
            name='price_data',
            field=models.JSONField(blank=True, default=dict, help_text='Multi-currency price and discount data.'),
        ),
    ]
