# Generated by Django 5.2 on 2025-04-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0021_remove_remoteprice_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleschannelview',
            name='name',
            field=models.CharField(blank=True, max_length=216, null=True),
        ),
    ]
