# Generated by Django 5.2 on 2025-05-01 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0022_alter_saleschannelview_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteproductproperty',
            name='remote_property',
            field=models.ForeignKey(help_text='The remote property associated with this product property.', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='sales_channels.remoteproperty'),
        ),
    ]
