# Generated by Django 5.1.1 on 2024-09-22 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0022_alter_remotelog_sales_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecategory',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remotecurrency',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remotecustomer',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remoteimage',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remoteimageproductassociation',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remoteinventory',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remotelanguage',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remoteorder',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remoteorderitem',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remoteprice',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remoteproduct',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remoteproductconfigurator',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remoteproductcontent',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remoteproductproperty',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remoteproperty',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remotepropertyselectvalue',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='remotevat',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='saleschannelview',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='saleschannelviewassign',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
    ]
