# Generated by Django 5.1.1 on 2024-09-22 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0023_alter_remotecategory_sales_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotetaskqueue',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_channels.saleschannel'),
        ),
    ]
