# Generated by Django 5.2 on 2025-05-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_merge_20250512_1309'),
        ('sales_channels', '0023_alter_remoteproductproperty_remote_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproductconfigurator',
            name='properties',
            field=models.ManyToManyField(help_text='Local properties used for configurator logic.', related_name='remote_product_configurators', to='properties.property'),
        ),
    ]
