# Generated by Django 5.2 on 2025-05-13 16:48

from django.db import migrations


def populate_local_properties(apps, schema_editor):
    RemoteProductConfigurator = apps.get_model('sales_channels', 'RemoteProductConfigurator')

    for configurator in RemoteProductConfigurator.objects.all().prefetch_related('remote_properties'):
        local_props = [
            remote_prop.local_instance_id
            for remote_prop in configurator.remote_properties.all()
            if remote_prop.local_instance_id is not None
        ]

        if local_props:
            configurator.properties.set(local_props)
            configurator.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0024_remoteproductconfigurator_properties'),
    ]

    operations = [
        migrations.RunPython(populate_local_properties, reverse_code=migrations.RunPython.noop),
    ]
