# Generated by Django 5.1.1 on 2024-09-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_mediaproductthrough_options'),
        ('sales_channels', '0024_alter_remotetaskqueue_sales_channel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remoteimage',
            unique_together={('local_instance', 'sales_channel')},
        ),
        migrations.AlterUniqueTogether(
            name='remoteimageproductassociation',
            unique_together={('local_instance', 'sales_channel')},
        ),
    ]
