# Generated by Django 5.2 on 2025-05-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0025_auto_20250513_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteproductconfigurator',
            name='remote_properties',
        ),
    ]
