# Generated by Django 5.1.1 on 2024-09-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0025_alter_remoteimage_unique_together_and_more'),
        ('taxes', '0007_vatrate_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remotevat',
            unique_together={('local_instance', 'sales_channel')},
        ),
    ]
