# Generated by Django 5.1.1 on 2024-09-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0026_alter_remotevat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotetaskqueue',
            name='error_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
