# Generated by Django 5.2 on 2025-05-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_merge_20250512_1309'),
        ('sales_channels', '0026_remove_remoteproductconfigurator_remote_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteproductconfigurator',
            name='properties',
            field=models.ManyToManyField(help_text='Local properties used for configurator logic.', related_name='configurators', to='properties.property'),
        ),
    ]
