# Generated by Django 5.2 on 2025-05-15 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('products', '0005_alter_product_sku_alter_producttranslation_name_and_more'),
        ('sales_channels', '0027_alter_remoteproductconfigurator_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remoteproduct',
            unique_together={('sales_channel', 'local_instance', 'remote_parent_product')},
        ),
        migrations.AlterField(
            model_name='remoteproduct',
            name='remote_sku',
            field=models.CharField(blank=True, help_text='The SKU of the product in the remote system.', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='remoteproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_sku__isnull', False)), fields=('sales_channel', 'remote_sku'), name='unique_remote_sku_per_channel_if_present'),
        ),
    ]
