# Generated by Django 5.1.1 on 2024-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0027_remotetaskqueue_error_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotetaskqueue',
            name='error_history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
