# Generated by Django 5.2 on 2025-05-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0028_alter_remoteproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='mark_for_delete',
            field=models.BooleanField(default=False, help_text='Set to True when shop is scheduled for deletion (e.g. from shopify/shop_redact).'),
        ),
    ]
