# Generated by Django 5.1.1 on 2024-10-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0029_alter_remoteimageproductassociation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleschannel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='saleschannel',
            name='active',
        ),
        migrations.RemoveField(
            model_name='saleschannel',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='saleschannel',
            name='requests_per_minute',
        ),
        migrations.RemoveField(
            model_name='saleschannel',
            name='verify_ssl',
        ),
    ]
