# Generated by Django 5.2 on 2025-05-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0029_saleschannel_mark_for_delete', ),
        ('shopify', '0013_remove_shopifysaleschannel_is_external_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='is_external_install',
            field=models.BooleanField(default=False, help_text='True if the installation was initiated from the Shopify App Store or other stores.'),
        ),
    ]
