# Generated by Django 5.2 on 2025-06-01 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('products', '0009_product_alias_requires_parent'),
        ('sales_channels', '0030_saleschannel_is_external_install'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='remoteproduct',
            name='unique_remote_sku_per_channel_if_present',
        ),
        migrations.AddConstraint(
            model_name='remoteproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_sku__isnull', False)), fields=('sales_channel', 'remote_sku', 'is_variation'), name='unique_remote_sku_per_channel_if_present'),
        ),
    ]
