# Generated by Django 5.1.1 on 2024-10-17 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('sales_channels', '0031_remove_saleschannel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleschannel',
            name='id',
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='integration_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.integration'),
        ),
    ]
