# Generated by Django 5.2 on 2025-06-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0031_remove_remoteproduct_unique_remote_sku_per_channel_if_present_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleschannelview',
            unique_together=set(),
        ),
    ]
