# Generated by Django 5.1.1 on 2024-10-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0032_remove_saleschannel_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoteTaskQueue',
        ),
    ]
