# Generated by Django 5.2 on 2025-06-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0032_alter_saleschannelview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannelviewassign',
            name='amazon_issues',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
