# Generated by Django 5.1.1 on 2024-10-17 13:42

import django.db.models.deletion
from django.db import migrations, models

def forwards_func(apps, schema_editor):
    RemoteLog = apps.get_model('sales_channels', 'RemoteLog')
    RemoteLog.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_integrationlog'),
        ('sales_channels', '0033_delete_remotetaskqueue'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='remotelog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='created_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='error_traceback',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='keep',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='last_update_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='multi_tenant_company',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='related_object_str',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='response',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='sales_channel',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='user_error',
        ),
        migrations.AddField(
            model_name='remotelog',
            name='integrationlog_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.integrationlog'),
            preserve_default=False,
        ),
    ]
