# Generated by Django 5.2 on 2025-06-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0033_saleschannelviewassign_amazon_issues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleschannelviewassign',
            old_name='amazon_issues',
            new_name='issues',
        ),
    ]
