# Generated by Django 5.2.3 on 2025-06-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0034_rename_amazon_issues_saleschannelviewassign_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproductconfigurator',
            name='amazon_theme',
            field=models.CharField(blank=True, help_text='Amazon variation theme associated with this configurator.', max_length=255, null=True),
        ),
    ]
