# Generated by Django 5.2.3 on 2025-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0035_remoteproductconfigurator_amazon_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleschannelviewassign',
            name='issues',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
