# Generated by Django 5.2 on 2025-07-01 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('properties', '0012_alter_property_options_and_more'),
        ('sales_channels', '0036_alter_saleschannelviewassign_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remoteproperty',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='remoteproperty',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='Set to True to allow multiple remote properties to map to the same local property.'),
        ),
        migrations.AddConstraint(
            model_name='remoteproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('allow_multiple', False)), fields=('sales_channel', 'local_instance'), name='uniq_remoteproperty_by_channel_local_when_not_multi'),
        ),
    ]
