# Generated by Django 5.2 on 2025-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0037_alter_remoteproperty_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleschannelviewassign',
            name='issues',
        ),
        migrations.CreateModel(
            name='AmazonProductIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=255, null=True)),
                ('is_validation_issue', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('remote_product', models.ForeignKey(on_delete=models.CASCADE, related_name='issues', to='sales_channels.amazonproduct')),
                ('view', models.ForeignKey(on_delete=models.CASCADE, related_name='product_issues', to='sales_channels.amazonsaleschannelview')),
            ],
            options={
                'ordering': ('remote_product_id', 'view_id'),
                'verbose_name': 'Amazon Product Issue',
                'verbose_name_plural': 'Amazon Product Issues',
            },
        ),
    ]
