# Generated by Django 5.2.3 on 2025-07-01 18:21

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_multitenantcompany_ai_points_and_more"),
        ("sales_channels", "0037_alter_remoteproperty_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultUnitConfigurator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                (
                    "selected_unit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("choices", models.JSONField(blank=True, default=list)),
                (
                    "created_by_multi_tenant_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_multi_tenant_user_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_update_by_multi_tenant_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_last_update_by_multi_tenant_user_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "multi_tenant_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.multitenantcompany",
                    ),
                ),
                (
                    "sales_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_unit_configurators",
                        to="sales_channels.saleschannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Default Unit Configurator",
                "verbose_name_plural": "Default Unit Configurators",
                "unique_together": {("sales_channel", "code")},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
