# Generated by Django 5.2 on 2025-08-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0037_alter_remoteproperty_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleschannelviewassign',
            name='issues',
        ),
    ]
