# Generated by Django 5.2 on 2025-09-17 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_multitenantcompany_active_and_more'),
        ('products', '0022_alter_producttranslation_language'),
        ('sales_channels', '0039_alter_remotelanguage_local_instance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='remoteproduct',
            name='unique_remote_sku_per_channel_if_present',
        ),
        migrations.AddConstraint(
            model_name='remoteproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_sku__isnull', False)), fields=('sales_channel', 'remote_sku', 'is_variation', 'remote_parent_product'), name='unique_remote_sku_per_channel_with_parent_if_present'),
        ),
    ]
