# Generated by Django 5.2 on 2025-10-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0040_remove_remoteproduct_unique_remote_sku_per_channel_if_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='starting_stock',
            field=models.PositiveIntegerField(blank=True, help_text='Initial stock quantity to send when creating remote products.', null=True),
        ),
    ]
