# Generated by Django 5.2 on 2025-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0041_saleschannel_starting_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannelviewassign',
            name='listing_id',
            field=models.CharField(blank=True, help_text='Listing identifier returned by the remote marketplace.', max_length=64, null=True),
        ),
    ]
