# Generated by Django 5.2 on 2025-10-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0042_saleschannelviewassign_listing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleschannelviewassign',
            name='listing_id',
        ),
    ]
