# Generated by Django 5.2 on 2025-10-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0044_saleschannelcontenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannelcontenttemplate',
            name='add_as_iframe',
            field=models.BooleanField(default=False, help_text='Render the template output inside an iframe when syncing content.'),
        ),
    ]
