# Generated by Django 5.2 on 2025-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0046_remoteproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteproduct',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PROCESSING', 'Processing')], db_index=True, default='PROCESSING', help_text='Current sync status derived from progress and sync errors.', max_length=16),
        ),
    ]
