# Generated by Django 5.2 on 2025-10-28 19:43

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_multitenantcompany_active_and_more'),
        ('sales_channels', '0048_saleschannel_gpt_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproduct',
            name='required_feed_sync',
            field=models.BooleanField(default=False, help_text='Indicates if the GPT product feed needs to be refreshed for this remote product.'),
        ),
        migrations.CreateModel(
            name='SalesChannelGptFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.JSONField(blank=True, default=list, help_text='Cached GPT product feed entries for this sales channel.')),
                ('file', models.FileField(blank=True, help_text='Downloadable JSON file containing the GPT product feed.', null=True, upload_to='gpt_feeds/')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp when the GPT feed was last synchronised.', null=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('sales_channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_feed_record', to='sales_channels.saleschannel')),
            ],
            options={
                'verbose_name': 'Sales Channel GPT Feed',
                'verbose_name_plural': 'Sales Channel GPT Feeds',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
    ]
