# Generated by Django 5.2 on 2025-12-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0050_populate_saleschannelgptfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteproduct',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('APPROVAL_REJECTED', 'Approval rejected'), ('PARTIALLY_LISTED', 'Partially listed'), ('PENDING_APPROVAL', 'Pending approval'), ('PROCESSING', 'Processing')], db_index=True, default='PROCESSING', help_text='Current sync status derived from progress and sync errors.', max_length=17),
        ),
    ]
