# Generated by Django 5.2 on 2025-12-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0051_alter_remoteproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannelviewassign',
            name='status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Created'), ('PENDING_CREATION', 'Pending creation')], default='CREATED', help_text='Local assignment status for the view assignment.', max_length=32, null=True),
        ),
    ]
