# Generated by Django 5.2 on 2025-12-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0052_saleschannelviewassign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannelviewassign',
            name='link',
            field=models.URLField(blank=True, help_text='Remote product URL for this view assignment.', max_length=2048, null=True),
        ),
    ]
