# Generated by Django 5.2 on 2026-01-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0053_saleschannelviewassign_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='min_description_length',
            field=models.PositiveIntegerField(default=1000, help_text='Minimum product description length enforced by this sales channel.'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='min_name_length',
            field=models.PositiveIntegerField(default=150, help_text='Minimum product name length enforced by this sales channel.'),
        ),
    ]
