# Generated by Django 5.2 on 2026-01-16 18:28

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('sales_channels', '0054_saleschannel_min_description_length_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_type', models.CharField(choices=[('product', 'Product'), ('property', 'Property'), ('content', 'Content'), ('price', 'Price'), ('images', 'Images')], help_text='What kind of sync is required.', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', help_text='Current state of the sync request.', max_length=16)),
                ('reason', models.CharField(blank=True, help_text='Short reason for the sync request.', max_length=255, null=True)),
                ('task_func_path', models.CharField(blank=True, help_text='Python import path for the task function.', max_length=255, null=True)),
                ('task_kwargs', models.JSONField(blank=True, default=dict, help_text='Serialized task kwargs for enqueueing the sync request.')),
                ('number_of_remote_requests', models.PositiveIntegerField(blank=True, help_text='Optional number of remote requests for queue accounting.', null=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('remote_product', models.ForeignKey(help_text='Remote product that needs sync.', on_delete=django.db.models.deletion.CASCADE, related_name='sync_requests', to='sales_channels.remoteproduct')),
                ('sales_channel', models.ForeignKey(help_text='Sales channel associated with the sync request.', on_delete=django.db.models.deletion.CASCADE, related_name='sync_requests', to='sales_channels.saleschannel')),
                ('sales_channel_view', models.ForeignKey(blank=True, help_text='Marketplace view to sync (nullable for viewless changes).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_requests', to='sales_channels.saleschannelview')),
            ],
            options={
                'verbose_name': 'Sync Request',
                'verbose_name_plural': 'Sync Requests',
                'indexes': [models.Index(fields=['status'], name='sales_chann_status_97c9e2_idx'), models.Index(fields=['remote_product', 'status'], name='sales_chann_remote__a5536f_idx'), models.Index(fields=['sales_channel', 'status'], name='sales_chann_sales_c_47aa68_idx')],
                'constraints': [models.UniqueConstraint(fields=('remote_product', 'sales_channel', 'sales_channel_view', 'sync_type'), name='uniq_sync_request', nulls_distinct=False)],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
    ]
