# Generated by Django 5.2 on 2026-01-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0055_syncrequest'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syncrequest',
            name='uniq_sync_request',
        ),
        migrations.AlterField(
            model_name='syncrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the sync request was created.'),
        ),
        migrations.AlterField(
            model_name='syncrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the sync request was last updated.'),
        ),
    ]
