# Generated by Django 5.2 on 2026-01-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0056_remove_syncrequest_uniq_sync_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='syncrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
