# Generated by Django 5.2 on 2026-01-26 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0057_alter_syncrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrequest',
            name='escalation_remote_product',
            field=models.ForeignKey(blank=True, help_text='Remote product that should be refreshed to clear this sync request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalation_sync_requests', to='sales_channels.remoteproduct'),
        ),
    ]
