# Generated by Django 5.2 on 2026-01-27 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0058_syncrequest_escalation_remote_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncrequest',
            name='escalation_remote_product',
        ),
        migrations.AddField(
            model_name='syncrequest',
            name='skipped_for',
            field=models.ForeignKey(blank=True, help_text='Request that superseded this sync request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_requests', to='sales_channels.syncrequest'),
        ),
        migrations.AlterField(
            model_name='syncrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Current state of the sync request.', max_length=16),
        ),
    ]
