# Generated by Django 5.2 on 2026-02-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0059_remove_syncrequest_escalation_remote_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteprice',
            name='price_data_hash',
            field=models.CharField(blank=True, help_text='Hash of the canonical price_data payload.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='remoteprice',
            name='price_data',
            field=models.JSONField(blank=True, default=dict, help_text="Multi-currency price data, e.g. {'EUR': {'price': 10.0, 'discount_price': 8.0}}."),
        ),
    ]
