# Generated by Django 5.2 on 2026-02-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0060_remoteprice_price_data_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproductcontent',
            name='content_data',
            field=models.JSONField(blank=True, default=dict, help_text="Per-language content payload containing only fields relevant for the integration, e.g. {'en': {'name': 'Tee', 'description': '...'}}."),
        ),
        migrations.AddField(
            model_name='remoteproductcontent',
            name='content_data_hash',
            field=models.CharField(blank=True, help_text='Hash of the canonical content_data payload.', max_length=64, null=True),
        ),
    ]
