# Generated by Django 5.2 on 2026-02-04 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0016_alter_dashboardsection_description'),
        ('products', '0023_producttranslation_subtitle'),
        ('sales_channels', '0061_remoteproductcontent_content_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='syncrequest',
            name='sales_chann_status_97c9e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='syncrequest',
            name='sales_chann_remote__a5536f_idx',
        ),
        migrations.RemoveIndex(
            model_name='syncrequest',
            name='sales_chann_sales_c_47aa68_idx',
        ),
        migrations.AddIndex(
            model_name='remoteproduct',
            index=models.Index(fields=['local_instance', 'sales_channel'], name='sales_chann_local_i_97a0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='saleschannelviewassign',
            index=models.Index(fields=['product', 'sales_channel_view'], name='sales_chann_product_2dbdff_idx'),
        ),
        migrations.AddIndex(
            model_name='saleschannelviewassign',
            index=models.Index(fields=['remote_product', 'sales_channel_view'], name='sales_chann_remote__860ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrequest',
            index=models.Index(fields=['sales_channel', 'sales_channel_view', 'remote_product', 'status', 'sync_type'], name='sales_chann_sales_c_751402_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrequest',
            index=models.Index(fields=['sales_channel', 'remote_product', 'status'], name='sales_chann_sales_c_1d7c89_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrequest',
            index=models.Index(fields=['skipped_for'], name='sales_chann_skipped_80655c_idx'),
        ),
    ]
