# Generated by Django 5.2 on 2026-02-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0062_remove_syncrequest_sales_chann_status_97c9e2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproperty',
            name='no_text_value',
            field=models.CharField(blank=True, help_text='Text value treated as False when mapping text-like remote values to boolean.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='remoteproperty',
            name='original_type',
            field=models.CharField(blank=True, choices=[('INT', 'Integer'), ('FLOAT', 'Float'), ('TEXT', 'Text'), ('DESCRIPTION', 'Description'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DATETIME', 'Date time'), ('SELECT', 'Select'), ('MULTISELECT', 'Multi Select')], help_text='Original remote property type before any manual remapping.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='remoteproperty',
            name='yes_text_value',
            field=models.CharField(blank=True, help_text='Text value treated as True when mapping text-like remote values to boolean.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='remotepropertyselectvalue',
            name='bool_value',
            field=models.BooleanField(blank=True, help_text='Boolean meaning for this option when mapping select/multiselect remote values to boolean.', null=True),
        ),
    ]
