# Generated by Django 5.2 on 2026-02-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0065_remoteproperty_type_remote'),
        ('amazon', '0071_remove_amazonproperty_type'),
        ('ebay', '0024_remove_ebayproperty_type'),
        ('shein', '0022_remove_sheinproperty_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteproperty',
            old_name='type_remote',
            new_name='type',
        ),
    ]
