# Generated by Django 5.2 on 2026-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0066_rename_type_remote_remoteproperty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproperty',
            name='allows_unmapped_values_remote',
            field=models.BooleanField(default=False, help_text='Whether this remote property accepts values outside predefined options.'),
        ),
    ]
