# Generated by Django 5.2 on 2026-02-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0068_backfill_remoteproperty_allows_unmapped_values_remote'),
        ('amazon', '0072_remove_amazonproperty_allows_unmapped_values'),
        ('ebay', '0025_remove_ebayproperty_allows_unmapped_values'),
        ('shein', '0023_remove_sheinproperty_allows_unmapped_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteproperty',
            old_name='allows_unmapped_values_remote',
            new_name='allows_unmapped_values',
        ),
    ]
