# Generated by Django 5.2 on 2026-02-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_productpropertiesruleitem_properties__rule_id_884958_idx'),
        ('sales_channels', '0069_rename_allows_unmapped_values_remote_remoteproperty_allows_unmapped_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotepropertyselectvalue',
            name='local_instance',
            field=models.ForeignKey(blank=True, help_text='The local PropertySelectValue associated with this remote value.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyselectvalue'),
        ),
    ]
