# Generated by Django 5.2 on 2026-02-16 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0016_alter_dashboardsection_description'),
        ('properties', '0019_productpropertiesruleitem_properties__rule_id_884958_idx'),
        ('sales_channels', '0071_backfill_allow_multiple_for_marketplace_remote_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remotepropertyselectvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='remotepropertyselectvalue',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='Set to True to allow multiple remote values to map to the same local property select value.'),
        ),
        migrations.AddConstraint(
            model_name='remotepropertyselectvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('allow_multiple', False)), fields=('sales_channel', 'local_instance'), name='uniq_remotepropselval_by_channel_local_not_multi'),
        ),
    ]
