# Generated by Django 5.2 on 2026-02-17 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0016_alter_dashboardsection_description'),
        ('properties', '0019_productpropertiesruleitem_properties__rule_id_884958_idx'),
        ('sales_channels', '0073_backfill_remotepropertyselectvalue_allow_multiple'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='remotepropertyselectvalue',
            constraint=models.UniqueConstraint(fields=('remote_property', 'local_instance'), name='uniq_rpsv_remoteprop_localinst'),
        ),
    ]
