# Generated by Django 5.2 on 2026-02-23 20:52

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0016_alter_dashboardsection_description'),
        ('products', '0023_producttranslation_subtitle'),
        ('sales_channels', '0075_remotedocumenttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True)),
                ('successfully_created', models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.')),
                ('outdated', models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.')),
                ('outdated_since', models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True)),
                ('require_view', models.BooleanField(default=True, help_text='When true, the category assignment is scoped to a sales channel view.')),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('product', models.ForeignKey(help_text='Local product linked to the remote category assignment.', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel')),
                ('view', models.ForeignKey(blank=True, help_text='Sales channel view/marketplace for view-specific category assignments.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannelview')),
            ],
            options={
                'verbose_name': 'Remote Product Category',
                'verbose_name_plural': 'Remote Product Categories',
                'indexes': [models.Index(fields=['product', 'view', 'require_view'], name='sales_chann_product_c343fa_idx'), models.Index(fields=['product', 'sales_channel', 'require_view'], name='sales_chann_product_622731_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('require_view', True), ('view__isnull', False)), models.Q(('require_view', False), ('view__isnull', True)), _connector='OR'), name='remote_product_category_view_required_consistency', violation_error_message='Store is required only when require_view is enabled.'), models.UniqueConstraint(condition=models.Q(('require_view', True)), fields=('product', 'view', 'require_view'), name='remote_product_category_unique_product_view_when_required'), models.UniqueConstraint(condition=models.Q(('require_view', False)), fields=('product', 'sales_channel', 'require_view'), name='remote_product_category_unique_product_channel_when_not_required')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
    ]
