# Generated by Django 5.2 on 2026-02-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0076_remoteproductcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproductcategory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Legacy row ID used during migration from old category-assignment models.', null=True),
        ),
    ]
