# Generated by Django 5.2 on 2026-02-25 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0016_alter_dashboardsection_description'),
        ('media', '0013_alter_documenttype_code'),
        ('sales_channels', '0078_remotedocument_remotedocumentproductassociation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrequest',
            name='sync_type',
            field=models.CharField(choices=[('product', 'Product'), ('property', 'Property'), ('content', 'Content'), ('price', 'Price'), ('images', 'Images'), ('documents', 'Documents')], help_text='What kind of sync is required.', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='remotedocumenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('local_instance__isnull', False)), fields=('sales_channel', 'local_instance'), name='unique_remote_document_type_mapping_per_channel', violation_error_message='A local document type can only be mapped once per sales channel.'),
        ),
    ]
