# Generated by Django 5.2 on 2026-02-27 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0016_alter_dashboardsection_description'),
        ('media', '0014_media_original_url'),
        ('sales_channels', '0079_alter_syncrequest_sync_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remotedocumentproductassociation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='remotedocumentproductassociation',
            name='require_document',
            field=models.BooleanField(default=True, help_text='When enabled, a linked remote_document is required for this assignment.'),
        ),
        migrations.AlterField(
            model_name='remotedocumentproductassociation',
            name='remote_document',
            field=models.ForeignKey(blank=True, help_text='Remote document assigned to the remote product.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_channels.remotedocument'),
        ),
        migrations.AddConstraint(
            model_name='remotedocumentproductassociation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('require_document', True), ('remote_document__isnull', False)), models.Q(('require_document', False), ('remote_document__isnull', True)), _connector='OR'), name='remote_document_product_assoc_require_document_consistency', violation_error_message='remote_document is required only when require_document is enabled.'),
        ),
        migrations.AddConstraint(
            model_name='remotedocumentproductassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('require_document', True)), fields=('local_instance', 'sales_channel', 'remote_product', 'remote_document'), name='remote_document_product_assoc_unique_with_remote_document'),
        ),
        migrations.AddConstraint(
            model_name='remotedocumentproductassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('require_document', False)), fields=('local_instance', 'sales_channel', 'remote_product'), name='remote_document_product_assoc_unique_without_remote_document'),
        ),
    ]
