# Generated by Django 5.2 on 2026-02-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0080_alter_remotedocumentproductassociation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotedocument',
            name='remote_url',
        ),
        migrations.AddField(
            model_name='remotedocumentproductassociation',
            name='remote_url',
            field=models.URLField(blank=True, help_text='Public source URL used for this remote document association sync.', max_length=2048, null=True),
        ),
    ]
