# Generated by Django 5.2 on 2026-03-12 12:54

import core.models.core
import core.upload_paths
import dirtyfields.dirtyfields
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0016_alter_dashboardsection_description'),
        ('sales_channels', '0081_remove_remotedocument_remote_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrequest',
            name='sync_type',
            field=models.CharField(choices=[('product', 'Product'), ('property', 'Property'), ('content', 'Content'), ('price', 'Price'), ('images', 'Images'), ('documents', 'Documents'), ('feed', 'Feed')], help_text='What kind of sync is required.', max_length=16),
        ),
        migrations.CreateModel(
            name='SalesChannelFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('product', 'Product'), ('offer', 'Offer'), ('combined', 'Combined')], max_length=32)),
                ('status', models.CharField(choices=[('gathering_products', 'Gathering products'), ('gathering_offers', 'Gathering offers'), ('ready_to_render', 'Ready to render'), ('new', 'New'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='new', max_length=32)),
                ('remote_id', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, help_text='Generated file uploaded to the remote integration when applicable.', null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'sales_channel_feeds'}))),
                ('payload_data', models.JSONField(blank=True, default=list)),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_batches', to='sales_channels.saleschannel')),
            ],
            options={
                'verbose_name': 'Sales Channel Feed',
                'verbose_name_plural': 'Sales Channel Feeds',
                'ordering': ['-created_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SalesChannelFeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='update', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('identifier', models.CharField(blank=True, default='', max_length=255)),
                ('payload_data', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_channels.saleschannelfeed')),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('remote_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='sales_channels.remoteproduct')),
                ('sales_channel_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items', to='sales_channels.saleschannelview')),
            ],
            options={
                'verbose_name': 'Sales Channel Feed Item',
                'verbose_name_plural': 'Sales Channel Feed Items',
                'ordering': ['id'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='saleschannelfeed',
            index=models.Index(fields=['sales_channel', 'type', 'status'], name='sales_chann_sales_c_b7f919_idx'),
        ),
        migrations.AddIndex(
            model_name='saleschannelfeeditem',
            index=models.Index(fields=['feed', 'status'], name='sales_chann_feed_id_4b12b4_idx'),
        ),
        migrations.AddIndex(
            model_name='saleschannelfeeditem',
            index=models.Index(fields=['remote_product', 'status'], name='sales_chann_remote__dbe9b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleschannelfeeditem',
            constraint=models.UniqueConstraint(fields=('feed', 'remote_product', 'sales_channel_view'), name='uniq_sales_channel_feed_item_per_remote_product', nulls_distinct=False),
        ),
    ]
