# Generated by Django 5.2 on 2026-03-13 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_productpropertiesruleitem_properties__rule_id_884958_idx'),
        ('sales_channels', '0082_alter_syncrequest_sync_type_saleschannelfeed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteproperty',
            name='local_instance',
            field=models.ForeignKey(blank=True, help_text='The local property associated with this remote property.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
    ]
