# Generated by Django 5.2 on 2026-03-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0083_alter_remoteproperty_local_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleschannelfeed',
            name='status',
            field=models.CharField(default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='saleschannelfeed',
            name='type',
            field=models.CharField(max_length=32),
        ),
    ]
