# Generated by Django 5.2 on 2026-03-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0084_alter_saleschannelfeed_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleschannelfeed',
            name='summary_data',
        ),
        migrations.AddField(
            model_name='saleschannelfeed',
            name='items_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleschannelfeed',
            name='rows_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
