# Generated by Django 5.2 on 2026-04-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0087_alter_remotelanguage_local_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedocumenttype',
            name='uploadable',
            field=models.BooleanField(default=True, help_text='Whether this remote document type can be uploaded through the integration API.'),
        ),
        migrations.AlterField(
            model_name='remoteproduct',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('APPROVAL_REJECTED', 'Approval rejected'), ('PENDING_EXTERNAL_DOCUMENTS', 'Pending external documents'), ('PARTIALLY_LISTED', 'Partially listed'), ('PENDING_APPROVAL', 'Pending approval'), ('PROCESSING', 'Processing')], db_index=True, default='PROCESSING', help_text='Current sync status derived from progress and sync errors.', max_length=32),
        ),
    ]
