# Generated by Django 5.2 on 2026-04-23 21:24

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_multitenantcompany_language_and_more'),
        ('products', '0025_alter_producttranslation_language'),
        ('sales_channels', '0088_remotedocumenttype_uploadable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannelview',
            name='include_in_todo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RejectedSalesChannelViewAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sales_channel_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannelview')),
            ],
            options={
                'verbose_name': 'Rejected Sales Channel View Assign',
                'verbose_name_plural': 'Rejected Sales Channel View Assigns',
                'ordering': ('product_id', 'sales_channel_view__name'),
                'indexes': [models.Index(fields=['product', 'sales_channel_view'], name='sales_chann_product_50dd54_idx')],
                'unique_together': {('product', 'sales_channel_view')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
    ]
