# Generated by Django 5.2 on 2026-04-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0089_saleschannelview_include_in_todo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannelview',
            name='todo_sort_order',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
