# Generated by Django 5.2 on 2026-04-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0090_saleschannelview_todo_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleschannelview',
            options={'ordering': ('todo_sort_order', 'id'), 'verbose_name': 'Sales Channel View', 'verbose_name_plural': 'Sales Channel Views'},
        ),
    ]
