# Generated by Django 5.2 on 2026-04-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0082_delete_amazoninventory'),
        ('magento2', '0015_delete_magentoinventory'),
        ('sales_channels', '0092_backfill_rejected_variations_for_configurable_assigns'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoteInventory',
        ),
    ]
