# Generated by Django 5.2 on 2026-04-29 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0093_delete_remoteinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSalesChannel',
            fields=[
                ('saleschannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannel')),
            ],
            options={
                'verbose_name': 'Manual Sales Channel',
                'verbose_name_plural': 'Manual Sales Channels',
            },
            bases=('sales_channels.saleschannel',),
        ),
        migrations.CreateModel(
            name='ManualSalesChannelView',
            fields=[
                ('saleschannelview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannelview')),
            ],
            options={
                'verbose_name': 'Manual Sales Channel View',
                'verbose_name_plural': 'Manual Sales Channel Views',
            },
            bases=('sales_channels.saleschannelview',),
        ),
    ]
