# Generated by Django 5.2 on 2026-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0094_manualsaleschannel_manualsaleschannelview'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='max_description_length',
            field=models.PositiveIntegerField(default=0, help_text='Maximum product description length enforced by this sales channel. Set to 0 to disable.'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='max_name_length',
            field=models.PositiveIntegerField(default=0, help_text='Maximum product name length enforced by this sales channel. Set to 0 to disable.'),
        ),
    ]
