# Generated by Django 5.0.7 on 2024-08-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20240810_1550'),
        ('shipments', '0004_shipmentitem_shipmentitemtoship_shipmentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
