# Generated by Django 5.0.7 on 2024-08-25 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20240810_1550'),
        ('shipments', '0005_shipmentitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageitem',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='packageitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
            preserve_default=False,
        ),
    ]
