# Generated by Django 5.0.7 on 2024-08-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_inventorylocation_shippingaddress'),
        ('shipments', '0006_rename_qty_packageitem_quantity_packageitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitem',
            name='inventory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('PACKED', 'Packed'),
                                   ('DISPATCHED', 'Dispatched')], default='NEW', max_length=11),
        ),
    ]
