# Generated by Django 5.1.1 on 2024-10-11 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_inventorymovement_product'),
        ('shipments', '0008_package_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitemtoship',
            name='inventorylocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorylocation'),
        ),
    ]
