# Generated by Django 5.1.1 on 2024-10-11 00:17

from django.db import migrations

def populate_inventorylocation(apps, schema_editor):
    ShipmentItemToShip = apps.get_model('shipments', 'ShipmentItemToShip')
    Inventory = apps.get_model('inventory', 'Inventory')

    for item in ShipmentItemToShip.objects.all():
        try:
            inventory = Inventory.objects.get(
                product=item.product,
                inventorylocation__shippingaddress=item.shipment.from_address
            )
            item.inventorylocation = inventory.inventorylocation
            item.save()
        except Inventory.DoesNotExist:
            item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_shipmentitemtoship_inventorylocation'),
    ]

    operations = [
        migrations.RunPython(populate_inventorylocation),
    ]
