# Generated by Django 4.2.5 on 2023-09-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('contacts', '0001_initial'),
        ('orders', '0001_initial'),
        ('django_shared_multi_tenant', '0007_alter_multitenantcompany_language'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoiceaddress_set', to='contacts.invoiceaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='multi_tenant_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_shared_multi_tenant.multitenantcompany'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shippingaddress_set', to='contacts.shippingaddress'),
        ),
    ]
