# Generated by Django 4.2.5 on 2023-09-20 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_shared_multi_tenant', '0007_alter_multitenantcompany_language'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='company',
            new_name='multi_tenant_company',
        ),
        migrations.RenameField(
            model_name='ordernote',
            old_name='company',
            new_name='multi_tenant_company',
        ),
        migrations.AddField(
            model_name='order',
            name='multi_tenant_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_shared_multi_tenant.multitenantcompany'),
        ),
    ]
