# Generated by Django 4.2.5 on 2023-09-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PENDING_INVENTORY', 'Pending Inventory'), ('TOPICK', 'To Pick'), ('TOSHIP', 'To Ship'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled'), (
                'HOLD', 'On Hold'), ('EXCHANGED', 'Exchanged'), ('REFUNDED', 'Refunded'), ('LOST', 'Lost'), ('MERGED', 'Merged'), ('DAMAGED', 'Damaged'), ('VOID', 'Void')], default='DRAFT', max_length=17),
        ),
    ]
