# Generated by Django 4.2.6 on 2023-10-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=3)),
                ('exchange_rate', models.FloatField(default=1)),
                ('round_prices_up_to', models.IntegerField(default=1)),
                ('is_default_currency', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('inherits_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_to', to='currencies.currency')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_currency', True)),
                                               fields=('is_default_currency',), name='unique_is_default_currency'),
        ),
    ]
