# Generated by Django 5.1.1 on 2025-02-25 10:57

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=3)),
                ('exchange_rate', models.FloatField(blank=True, default=1, null=True)),
                ('exchange_rate_official', models.FloatField(blank=True, default=1, null=True)),
                ('follow_official_rate', models.BooleanField(default=False)),
                ('round_prices_up_to', models.IntegerField(blank=True, default=1, null=True)),
                ('is_default_currency', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('inherits_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_to', to='currencies.currency')),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_currency', True)), fields=('multi_tenant_company',), name='unique_is_default_currency', violation_error_message='You can only have one default currency.'), models.UniqueConstraint(fields=('iso_code', 'multi_tenant_company'), name='unique_iso_code_multi_tenant_company', violation_error_message='This currency already exists.')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
