# Generated by Django 4.2.6 on 2023-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='exchange_rate_official',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='currency',
            name='follow_official_rate',
            field=models.BooleanField(default=False),
        ),
    ]
