# Generated by Django 5.0.2 on 2024-04-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_currency_exchange_rate_official_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currency',
            name='unique_is_default_currency',
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_currency', True)),
                                               fields=('multi_tenant_company',), name='unique_is_default_currency'),
        ),
    ]
