# Generated by Django 5.1.7 on 2025-05-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20250225_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='round_prices_up_to',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
