# Generated by Django 5.0.2 on 2024-06-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_remove_currency_unique_is_default_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate_official',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='round_prices_up_to',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
