# Generated by Django 5.0.2 on 2024-06-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_alter_currency_exchange_rate_official_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
