# Generated by Django 5.0.2 on 2024-07-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_remove_currency_unique_is_default_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
