# Generated by Django 5.0.2 on 2024-07-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_multitenantuser_timezone'),
        ('currencies', '0007_publiccurrency'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('iso_code', 'multi_tenant_company'), name='unique_iso_code_multi_tenant_company', violation_error_message='This currency already exists.'),
        ),
    ]
