# Generated by Django 5.0.2 on 2024-07-16 22:31

from django.db import migrations
from django.db.models import Count


def forwards(apps, schema_editor):
    Currency = apps.get_model('currencies', 'Currency')
    SalesPrice = apps.get_model('sales_prices', 'SalesPrice')
    SalesPriceList = apps.get_model('sales_prices', 'SalesPriceList')
    Order = apps.get_model('orders', 'Order')
    Company = apps.get_model('contacts', 'Company')
    PurchaseOrder = apps.get_model('purchasing', 'PurchaseOrder')

    # Find all duplicates
    duplicates = (Currency.objects
                  .values('iso_code', 'multi_tenant_company')
                  .annotate(count=Count('id'))
                  .filter(count__gt=1))

    for duplicate in duplicates:
        iso_code = duplicate['iso_code']
        multi_tenant_company = duplicate['multi_tenant_company']

        currencies = Currency.objects.filter(iso_code=iso_code, multi_tenant_company=multi_tenant_company)
        default_currency = currencies.filter(is_default_currency=True).first()
        if default_currency:
            currencies_to_delete = currencies.exclude(id=default_currency.id)
        else:
            default_currency = currencies.first()
            currencies_to_delete = currencies.exclude(id=default_currency.id)

        for currency in currencies_to_delete:
            related_models = [SalesPrice, SalesPriceList, Order, Company, PurchaseOrder]
            for model in related_models:
                model.objects.filter(currency=currency).update(currency=default_currency)

            currency.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0007_publiccurrency'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
