# Generated by Django 5.0.2 on 2024-07-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_alter_multitenantuser_timezone'),
        ('currencies', '0008_auto_20240716_2331'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('iso_code', 'multi_tenant_company'),
                                               name='unique_iso_code_multi_tenant_company', violation_error_message='This currency already exists.'),
        ),
    ]
