# Generated by Django 4.2.5 on 2023-09-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Company',
        ),
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contacts.company'),
            preserve_default=False,
        ),
    ]
