# Generated by Django 4.2.5 on 2023-09-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_address_company_alter_address_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='related_entities',
            new_name='related_companies',
        ),
    ]
