# Generated by Django 5.2 on 2026-03-11 13:18

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('properties', '0019_productpropertiesruleitem_properties__rule_id_884958_idx'),
        ('sales_channels', '0081_remove_remotedocument_remote_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiraklDocumentType',
            fields=[
                ('remotedocumenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotedocumenttype')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Mirakl Document Type',
                'verbose_name_plural': 'Mirakl Document Types',
            },
            bases=('sales_channels.remotedocumenttype',),
        ),
        migrations.CreateModel(
            name='MiraklEanCode',
            fields=[
                ('remoteeancode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteeancode')),
            ],
            options={
                'verbose_name': 'Mirakl EAN Code',
                'verbose_name_plural': 'Mirakl EAN Codes',
            },
            bases=('sales_channels.remoteeancode',),
        ),
        migrations.CreateModel(
            name='MiraklPrice',
            fields=[
                ('remoteprice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteprice')),
            ],
            options={
                'verbose_name': 'Mirakl Price',
                'verbose_name_plural': 'Mirakl Prices',
            },
            bases=('sales_channels.remoteprice',),
        ),
        migrations.CreateModel(
            name='MiraklProduct',
            fields=[
                ('remoteproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproduct')),
                ('product_id_type', models.CharField(blank=True, default='', max_length=64)),
                ('product_reference', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Mirakl Product',
                'verbose_name_plural': 'Mirakl Products',
            },
            bases=('sales_channels.remoteproduct',),
        ),
        migrations.CreateModel(
            name='MiraklProductCategory',
            fields=[
                ('remoteproductcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproductcategory')),
            ],
            options={
                'verbose_name': 'Mirakl Product Category',
                'verbose_name_plural': 'Mirakl Product Categories',
            },
            bases=('sales_channels.remoteproductcategory',),
        ),
        migrations.CreateModel(
            name='MiraklProductContent',
            fields=[
                ('remoteproductcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproductcontent')),
            ],
            options={
                'verbose_name': 'Mirakl Product Content',
                'verbose_name_plural': 'Mirakl Product Contents',
            },
            bases=('sales_channels.remoteproductcontent',),
        ),
        migrations.CreateModel(
            name='MiraklProperty',
            fields=[
                ('remoteproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproperty')),
                ('code', models.CharField(help_text='Mirakl attribute code.', max_length=255)),
                ('name', models.CharField(blank=True, default='', help_text='Mirakl attribute label.', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('required', models.BooleanField(default=False)),
                ('variant', models.BooleanField(default=False)),
                ('requirement_level', models.CharField(blank=True, default='', max_length=64)),
                ('default_value', models.CharField(blank=True, default='', max_length=255)),
                ('value_list_code', models.CharField(blank=True, default='', max_length=255)),
                ('value_list_label', models.CharField(blank=True, default='', max_length=255)),
                ('validations', models.JSONField(blank=True, default=dict)),
                ('transformations', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Mirakl Property',
                'verbose_name_plural': 'Mirakl Properties',
            },
            bases=('sales_channels.remoteproperty',),
        ),
        migrations.CreateModel(
            name='MiraklPropertySelectValue',
            fields=[
                ('remotepropertyselectvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotepropertyselectvalue')),
                ('code', models.CharField(blank=True, default='', max_length=255)),
                ('value', models.CharField(blank=True, default='', max_length=512)),
                ('translated_value', models.CharField(blank=True, default='', max_length=512)),
                ('value_list_code', models.CharField(blank=True, default='', max_length=255)),
                ('value_list_label', models.CharField(blank=True, default='', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Mirakl Property Select Value',
                'verbose_name_plural': 'Mirakl Property Select Values',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotepropertyselectvalue',),
        ),
        migrations.CreateModel(
            name='MiraklRemoteCurrency',
            fields=[
                ('remotecurrency_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotecurrency')),
                ('label', models.CharField(blank=True, help_text='Display label returned by Mirakl for the currency.', max_length=128, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Marks the default currency for the Mirakl shop.')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Original Mirakl currency payload.')),
            ],
            options={
                'verbose_name': 'Mirakl Remote Currency',
                'verbose_name_plural': 'Mirakl Remote Currencies',
            },
            bases=('sales_channels.remotecurrency',),
        ),
        migrations.CreateModel(
            name='MiraklRemoteLanguage',
            fields=[
                ('remotelanguage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotelanguage')),
                ('label', models.CharField(blank=True, help_text='Display label returned by Mirakl for the locale.', max_length=128, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Marks the default locale when known.')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Original Mirakl locale payload.')),
            ],
            options={
                'verbose_name': 'Mirakl Remote Language',
                'verbose_name_plural': 'Mirakl Remote Languages',
            },
            bases=('sales_channels.remotelanguage',),
        ),
        migrations.CreateModel(
            name='MiraklSalesChannel',
            fields=[
                ('saleschannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannel')),
                ('shop_id', models.BigIntegerField(blank=True, help_text='Mirakl shop identifier used to scope API requests.', null=True)),
                ('api_key', models.CharField(blank=True, help_text='Mirakl API key sent in the Authorization header.', max_length=512, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Cached shop/account metadata returned by Mirakl.')),
            ],
            options={
                'verbose_name': 'Mirakl Sales Channel',
                'verbose_name_plural': 'Mirakl Sales Channels',
            },
            bases=('sales_channels.saleschannel',),
        ),
        migrations.CreateModel(
            name='MiraklSalesChannelImport',
            fields=[
                ('saleschannelimport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannelimport')),
                ('type', models.CharField(choices=[('schema', 'Schema'), ('product', 'Product'), ('offer', 'Offer'), ('pricing', 'Pricing')], max_length=32)),
                ('remote_import_id', models.CharField(blank=True, default='', max_length=255)),
                ('source_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('has_error_report', models.BooleanField(default=False)),
                ('has_transformed_file', models.BooleanField(default=False)),
                ('summary_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Mirakl Sales Channel Import',
                'verbose_name_plural': 'Mirakl Sales Channel Imports',
            },
            bases=('sales_channels.saleschannelimport',),
        ),
        migrations.CreateModel(
            name='MiraklSalesChannelView',
            fields=[
                ('saleschannelview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannelview')),
                ('description', models.TextField(blank=True, help_text='Mirakl channel description.', null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Original Mirakl channel payload.')),
            ],
            options={
                'verbose_name': 'Mirakl Sales Channel View',
                'verbose_name_plural': 'Mirakl Sales Channel Views',
            },
            bases=('sales_channels.saleschannelview',),
        ),
        migrations.CreateModel(
            name='MiraklCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True)),
                ('successfully_created', models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.')),
                ('outdated', models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.')),
                ('outdated_since', models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True)),
                ('name', models.CharField(blank=True, default='', help_text='Mirakl category label.', max_length=255)),
                ('parent_code', models.CharField(blank=True, default='', help_text='Remote identifier of the parent category.', max_length=255)),
                ('level', models.PositiveIntegerField(default=0, help_text='Hierarchy level reported by Mirakl.')),
                ('is_leaf', models.BooleanField(default=False, help_text='True when the category has no children in the imported tree.')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Original Mirakl hierarchy payload.')),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('parent', models.ForeignKey(blank=True, help_text='Reference to the parent category node when known.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mirakl.miraklcategory')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel')),
            ],
            options={
                'verbose_name': 'Mirakl Category',
                'verbose_name_plural': 'Mirakl Categories',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MiraklInternalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True)),
                ('successfully_created', models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.')),
                ('outdated', models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.')),
                ('outdated_since', models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True)),
                ('code', models.CharField(help_text='Field code used when building Mirakl payloads.', max_length=255)),
                ('name', models.CharField(blank=True, default='', help_text='Human-readable name of the internal field.', max_length=255)),
                ('label', models.CharField(blank=True, default='', help_text='Display label returned by Mirakl.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Mirakl description for the internal field.')),
                ('entity', models.CharField(blank=True, default='', help_text='Mirakl entity the field belongs to.', max_length=64)),
                ('type', models.CharField(choices=[('INT', 'Integer'), ('FLOAT', 'Float'), ('TEXT', 'Text'), ('DESCRIPTION', 'Description'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DATETIME', 'Date time'), ('SELECT', 'Select'), ('MULTISELECT', 'Multi Select')], default='TEXT', help_text='Mapped local property type for this field.', max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=False)),
                ('accepted_values', models.JSONField(blank=True, default=list)),
                ('regex', models.CharField(blank=True, default='', max_length=255)),
                ('is_condition', models.BooleanField(default=False, help_text='True when this internal property represents Mirakl item condition.')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('local_instance', models.ForeignKey(blank=True, help_text='Local property associated with this internal Mirakl field.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel')),
            ],
            options={
                'verbose_name': 'Mirakl Internal Property',
                'verbose_name_plural': 'Mirakl Internal Properties',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MiraklProductTypeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True)),
                ('successfully_created', models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.')),
                ('outdated', models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.')),
                ('outdated_since', models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True)),
                ('required', models.BooleanField(default=False)),
                ('variant', models.BooleanField(default=False)),
                ('role_data', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_items', to='mirakl.miraklcategory')),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('local_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.productpropertiesruleitem')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='mirakl.miraklproperty')),
            ],
            options={
                'verbose_name': 'Mirakl Product Type Item',
                'verbose_name_plural': 'Mirakl Product Type Items',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MiraklInternalPropertyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('internal_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mirakl.miraklinternalproperty')),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('local_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyselectvalue')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_property_options', to='mirakl.miraklsaleschannel')),
            ],
            options={
                'verbose_name': 'Mirakl Internal Property Option',
                'verbose_name_plural': 'Mirakl Internal Property Options',
                'ordering': ('sort_order', 'label'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MiraklPropertyApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True)),
                ('successfully_created', models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.')),
                ('outdated', models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.')),
                ('outdated_since', models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicabilities', to='mirakl.miraklproperty')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_applicabilities', to='mirakl.miraklsaleschannelview')),
            ],
            options={
                'verbose_name': 'Mirakl Property Applicability',
                'verbose_name_plural': 'Mirakl Property Applicabilities',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='miraklcategory',
            constraint=models.UniqueConstraint(fields=('sales_channel', 'remote_id'), name='unique_mirakl_category_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='miraklinternalproperty',
            constraint=models.UniqueConstraint(fields=('sales_channel', 'code'), name='unique_mirakl_internal_property_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='miraklproducttypeitem',
            constraint=models.UniqueConstraint(fields=('category', 'property'), name='unique_mirakl_category_property_item'),
        ),
        migrations.AddConstraint(
            model_name='miraklinternalpropertyoption',
            constraint=models.UniqueConstraint(fields=('internal_property', 'value'), name='unique_mirakl_internal_property_option_value'),
        ),
        migrations.AddConstraint(
            model_name='miraklpropertyapplicability',
            constraint=models.UniqueConstraint(fields=('property', 'view'), name='unique_mirakl_property_applicability'),
        ),
    ]
