# Generated by Django 5.2 on 2026-03-12 17:38

import core.upload_paths
import django.db.models.deletion
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0001_initial'),
        ('sales_channels', '0082_alter_syncrequest_sync_type_saleschannelfeed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiraklSalesChannelFeed',
            fields=[
                ('saleschannelfeed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannelfeed')),
                ('stage', models.CharField(choices=[('product', 'Product'), ('offer', 'Offer')], default='product', max_length=32)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Mirakl Sales Channel Feed',
                'verbose_name_plural': 'Mirakl Sales Channel Feeds',
            },
            bases=('sales_channels.saleschannelfeed',),
        ),
        migrations.AddField(
            model_name='miraklsaleschannel',
            name='sub_type',
            field=models.CharField(choices=[('mirakl', 'Mirakl'), ('1_800_flowers', '1-800-Flowers'), ('abb', 'ABB'), ('abbott', 'Abbott'), ('accor', 'Accor'), ('acer', 'Acer'), ('adani', 'Adani'), ('aena', 'AENA'), ('afound', 'Afound'), ('agora', 'Agora'), ('ahlens', 'Åhléns'), ('ahold_delhaize', 'Ahold Delhaize'), ('airbus', 'Airbus'), ('aksal_group', 'Aksal Group'), ('al_futtaim', 'Al-Futtaim'), ('albertsons', 'Albertsons'), ('alltricks', 'Alltricks'), ('alshaya', 'Alshaya'), ('altitude_sports', 'Altitude Sports'), ('amerisource_bergen', 'Amerisource Bergen'), ('aniel', 'Aniel'), ('anjana_investments', 'Anjana Investments'), ('anthropologie', 'Anthropologie'), ('anwb', 'ANWB'), ('arezzo_and_co', 'Arezzo&Co'), ('asos', 'ASOS'), ('atlas_for_men', 'Atlas For Men'), ('auchan', 'Auchan'), ('aurgi', 'Aurgi'), ('autodoc', 'Autodoc'), ('b_and_q', 'B&Q'), ('baloise', 'Baloise'), ('bank_of_cyprus', 'Bank of Cyprus'), ('baur', 'Baur'), ('bed_bath_and_beyond', 'Bed Bath & Beyond'), ('beerwulf', 'Beerwulf'), ('belk', 'Belk'), ('best_buy', 'Best Buy'), ('best_secret', 'Best Secret'), ('bestseller', 'Bestseller'), ('beter_bed', 'Beter Bed'), ('bhv', 'BHV'), ('bigbang', 'Bigbang'), ('bild_shop', 'Bild Shop'), ('black_red_white', 'Black Red White'), ('blokker', 'Blokker'), ('bloomingdale_s', "Bloomingdale's"), ('blue_diamond_growers', 'Blue Diamond Growers'), ('bob_s_discount', "Bob's Discount"), ('boelter_food_service_exchange', 'Boelter - Food Service Exchange'), ('bol_com', 'Bol.com'), ('boohoo', 'Boohoo'), ('boozt', 'Boozt'), ('boots', 'Boots'), ('boticario', 'Boticario'), ('boulanger', 'Boulanger'), ('brakes', 'Brakes'), ('brandalley', 'Brandalley'), ('brico', 'Brico'), ('brico_cash', 'Brico Cash'), ('bricocenter', 'Bricocenter'), ('brico_depot', 'Brico Depot'), ('bricomarche', 'Bricomarché'), ('bulevip', 'Bulevip'), ('bunnings', 'Bunnings'), ('business_france', 'Business France'), ('but', 'BUT'), ('butlers', 'Butlers'), ('c_and_a', 'C&A'), ('c10', 'C10'), ('cabinets_com', 'Cabinets.com'), ('camif', 'Camif'), ('camper', 'Camper'), ('campings_com', 'Campings.com'), ('carpetright', 'Carpetright'), ('carethy', 'Carethy'), ('carrefour', 'Carrefour'), ('casa_del_libro', 'Casa del Libro'), ('casino', 'Casino'), ('castorama', 'Castorama'), ('catch', 'Catch'), ('cdiscount', 'Cdiscount'), ('central_group_thailand', 'Central Group Thailand'), ('changi_airport', 'Changi Airport'), ('chemetall', 'Chemetall'), ('cheney_brothers', 'Cheney Brothers'), ('chr_avenue', 'CHR Avenue'), ('chronopost_pour_de_bon', 'Chronopost - Pour De Bon'), ('clarel', 'Clarel'), ('click_frenzy', 'Click Frenzy'), ('cleor', 'Cléor'), ('clube_fashion', 'Clube Fashion'), ('cma_cgm', 'CMA CGM'), ('coca_cola_europacific_partners', 'Coca-Cola Europacific Partners'), ('cobasi', 'Cobasi'), ('coin', 'Coin'), ('coles', 'Coles'), ('colombo', 'Colombo'), ('colruyt', 'Colruyt'), ('comptoir_sante', 'Comptoir Santé'), ('conforama', 'Conforama'), ('conrad', 'Conrad'), ('continente', 'Continente'), ('coperama', 'Coperama'), ('coppel', 'Coppel'), ('cora', 'Cora'), ('creavea', 'Creavea'), ('cultura', 'Cultura'), ('currys', 'Currys'), ('dafiti', 'Dafiti'), ('de_bijenkorf', 'De Bijenkorf'), ('debenhams', 'Debenhams'), ('decathlon', 'Decathlon'), ('delhaize', 'Delhaize'), ('dia_styling', 'Dia Styling'), ('disposable_discounter_didi', 'Disposable Discounter (DiDi)'), ('distriartisan', 'Distriartisan'), ('do_it_best', 'Do it Best'), ('doctipharma', 'DoctiPharma'), ('doto', 'Doto'), ('dotz', 'Dotz'), ('douglas', 'Douglas'), ('dr_max', 'Dr. Max'), ('dpg_media_group', 'DPG Media Group'), ('driven_brands', 'Driven Brands'), ('dubaistore', 'DubaiStore'), ('eiffage', 'Eiffage'), ('e_leclerc', 'E.Leclerc'), ('el_corte_ingles', 'El Corte Inglés'), ('elkjop', 'Elkjop'), ('ellos', 'Ellos'), ('electra', 'Electra'), ('empik', 'Empik'), ('engie', 'Engie'), ('eprice', 'ePRICE'), ('espace_aubade', 'Espace Aubade'), ('euronics', 'Euronics'), ('exito', 'Éxito'), ('exelon', 'Exelon'), ('expert', 'Expert'), ('falabella', 'Falabella'), ('fanatics', 'Fanatics'), ('farmacias_direct', 'Farmacias Direct'), ('feelunique', 'Feelunique'), ('ferguson', 'Ferguson'), ('fnac_darty', 'Fnac Darty'), ('fonq', 'FonQ'), ('fossil', 'Fossil'), ('france_boissons', 'France Boissons'), ('freedom_furniture', 'Freedom Furniture'), ('free_people', 'Free People'), ('fressnapf_tiernahrungs', 'Fressnapf Tiernahrungs'), ('fruugo', 'Fruugo'), ('gacd', 'GACD'), ('galeries_lafayette', 'Galeries Lafayette'), ('galeria_karstadt_kaufhof', 'Galeria Karstadt Kaufhof'), ('game', 'Game'), ('giant_eagle', 'Giant Eagle'), ('gifi', 'Gifi'), ('go_sport', 'Go Sport'), ('grainger', 'Grainger'), ('greenweez', 'Greenweez'), ('grenier_alpin', 'Grenier Alpin'), ('grupo_andres', 'Grupo Andres'), ('grupo_distelsa', 'Grupo Distelsa'), ('grupo_exito', 'Grupo Exito'), ('h_and_m', 'H&M'), ('hagebau', 'Hagebau'), ('halfords', 'Halfords'), ('happy_size_popken_fashion', 'Happy Size - Popken Fashion'), ('happytal', 'Happytal'), ('harvey_nichols', 'Harvey Nichols'), ('hema', 'HEMA'), ('hewlett_packard_enterprise', 'Hewlett Packard Enterprise'), ('home_and_you', 'Home & You'), ('home24', 'Home24'), ('homebase', 'Homebase'), ('home_depot', 'Home Depot'), ('hornbach', 'Hornbach'), ('hudson_s_bay', "Hudson's Bay"), ('hunkemoller', 'Hunkemöller'), ('ibs', 'IBS'), ('iberia', 'Iberia'), ('ifema', 'IFEMA'), ('inno', 'Inno'), ('intercorp', 'Intercorp'), ('intermarche', 'Intermarché'), ('invivo', 'Invivo'), ('ishopchangi', 'iShopChangi'), ('j_crew', 'J.Crew'), ('janie_and_jack', 'Janie and Jack'), ('jc_penney', 'JC Penney'), ('jd_sports_go_outdoors', 'JD Sports - Go Outdoors'), ('john_lewis', 'John Lewis'), ('joules', 'Joules'), ('jumbo', 'Jumbo'), ('kabum_comercio_eletronico', 'Kabum Comercio Eletronico'), ('kiabi', 'Kiabi'), ('kleertjes', 'Kleertjes'), ('koctas', 'Koctas'), ('kogan', 'Kogan'), ('kroger', 'Kroger'), ('kruidvat', 'Kruidvat'), ('kwik_fit', 'Kwik Fit'), ('la_poste', 'La Poste'), ('la_redoute', 'La Redoute'), ('ldlc', 'LDLC'), ('leen_bakker', 'Leen Bakker'), ('leroy_merlin', 'Leroy Merlin'), ('linio', 'Linio'), ('liverpool', 'Liverpool'), ('loblaws', 'Loblaws'), ('l_oreal', "L'Oréal"), ('macway', 'Macway'), ('macy_s', "Macy's"), ('madewell', 'Madewell'), ('magasin_du_nord', 'Magasin du Nord'), ('magazine_zum_globus', 'Magazine zum Globus'), ('maisons_du_monde', 'Maisons du Monde'), ('makro', 'Makro'), ('mango', 'Mango'), ('manomano', 'ManoMano'), ('manor', 'Manor'), ('manutan', 'Manutan'), ('marisa', 'Marisa'), ('marks_and_spencer', 'Marks & Spencer'), ('materiel_chr_pro', 'Materiel CHR Pro'), ('matelpro', 'Matelpro'), ('mathis_home', 'Mathis Home'), ('mathon', 'Mathon'), ('maty', 'Maty'), ('matalan', 'Matalan'), ('maxeda', 'Maxeda'), ('maykers', 'Maykers'), ('mediamarkt_saturn', 'MediaMarkt Saturn'), ('meubles_fr', 'Meubles.fr'), ('miinto', 'Miinto'), ('minted', 'Minted'), ('misako', 'Misako'), ('mm_mega_market', 'MM Mega Market'), ('mobase_siemens', 'Mobase-Siemens'), ('moda_operandi', 'Moda Operandi'), ('modivo', 'Modivo'), ('mondial_tissus', 'Mondial Tissus'), ('monoprix', 'Monoprix'), ('monshowroom', 'MonShowRoom'), ('mountain_warehouse', 'Mountain Warehouse'), ('mr_bricolage', 'Mr Bricolage'), ('musgrave', 'Musgrave'), ('myer', 'Myer'), ('nature_and_decouvertes', 'Nature & Découvertes'), ('newegg', 'Newegg'), ('nocibe', 'Nocibé'), ('norauto', 'Norauto'), ('nordstrom', 'Nordstrom'), ('ntuc_fairprice', 'NTUC Fairprice'), ('obelink', 'Obelink'), ('ochsner_sport', 'Ochsner Sport'), ('ocp_repartition', 'OCP Repartition'), ('oechsle', 'Oechsle'), ('office_depot', 'Office Depot'), ('onceit', 'Onceit'), ('onlinemetals_com', 'OnlineMetals.com'), ('onbuy', 'OnBuy'), ('oney', 'Oney'), ('otto', 'Otto'), ('palacio_de_hierro', 'Palacio de Hierro'), ('pandacola', 'Pandacola'), ('paris', 'Paris'), ('partstown', 'PartsTown'), ('pc_componentes', 'PC Componentes'), ('perfume_s_club', "Perfume's Club"), ('petcity', 'Petcity'), ('pharmedistore', 'Pharmedistore'), ('pharmaprov', 'Pharmaprov'), ('phone_house', 'Phone House'), ('pingo_doce', 'Pingo Doce'), ('pixmania', 'Pixmania'), ('place_des_tendances', 'Place des Tendances'), ('praxis', 'Praxis'), ('premier_farnell', 'Premier Farnell'), ('printemps', 'Printemps'), ('private_sport_shop', 'Private Sport Shop'), ('privalia', 'Privalia'), ('promart', 'Promart'), ('promod', 'Promod'), ('promofarma', 'PromoFarma'), ('proudly_market', 'Proudly.Market'), ('public_gr', 'Public.gr'), ('pyramyd_air', 'Pyramyd Air'), ('quirumed', 'Quirumed'), ('rakuten', 'Rakuten'), ('reedoo', 'Reedoo'), ('renner', 'Renner'), ('retif', 'Retif'), ('rexel', 'Rexel'), ('riachuelo', 'Riachuelo'), ('ripley', 'Ripley'), ('rs_components', 'RS Components'), ('rubix', 'Rubix'), ('rue_des_maquettes', 'Rue des Maquettes'), ('rue_du_commerce', 'Rue du Commerce'), ('rusta', 'Rusta'), ('saks_com', 'Saks.com'), ('saks_fifth_avenue', 'Saks Fifth Avenue'), ('saloncentric', 'SalonCentric'), ('sarenza', 'Sarenza'), ('satair', 'Satair'), ('saturn', 'Saturn'), ('secret_sales', 'Secret Sales'), ('sephora', 'Sephora'), ('shop_apotheke', 'Shop Apotheke'), ('shop_premium_outlets_shop_simon', 'Shop Premium Outlets - Shop Simon'), ('showroomprive', 'Showroomprive'), ('siam_makro', 'Siam Makro'), ('siemens', 'Siemens'), ('sligro', 'Sligro'), ('snappy_gifts', 'Snappy Gifts'), ('sncf', 'SNCF'), ('sodimac', 'Sodimac'), ('sonae', 'Sonae'), ('sonepar', 'Sonepar'), ('spartoo', 'Spartoo'), ('sportzone', 'Sportzone'), ('sprinter', 'Sprinter'), ('stadium', 'Stadium'), ('staples', 'Staples'), ('suez', 'SUEZ'), ('superdrug', 'Superdrug'), ('superpharm', 'SuperPharm'), ('sysco', 'Sysco'), ('ta_ta_s_a', 'Ta-Ta S.A.'), ('target_plus', 'Target Plus'), ('teknosa', 'Teknosa'), ('teract_invivo_retail', 'Teract - Invivo Retail'), ('tesco', 'Tesco'), ('thales', 'Thales'), ('the_kase', 'The Kase'), ('the_knot', 'The Knot'), ('the_range', 'The Range'), ('tiendamia', 'Tiendamia'), ('tiendanimal', 'Tiendanimal'), ('toolstation', 'Toolstation'), ('totalplay', 'Totalplay'), ('toyota_material_handling', 'Toyota Material Handling'), ('tradeinn', 'TradeInn'), ('trendy_foods', 'Trendy Foods'), ('truffaut', 'Truffaut'), ('twil', 'Twil'), ('ubaldi', 'Ubaldi'), ('united_farmers_of_alberta_ufa', 'United Farmers of Alberta - UFA'), ('united_natural_foods_unfi', 'United Natural Foods (UNFI)'), ('urban_outfitters', 'Urban Outfitters'), ('vanden_borre', 'Vanden Borre'), ('veepee', 'Veepee'), ('venca', 'Venca'), ('vente_unique', 'Vente-Unique'), ('verdetierra', 'VerdeTierra'), ('verishop', 'Verishop'), ('vertbaudet', 'Vertbaudet'), ('vidaxl', 'vidaXL'), ('vink', 'Vink'), ('virtual_expo', 'Virtual Expo'), ('voelkner', 'voelkner'), ('walmart', 'Walmart'), ('watchfinder', 'WatchFinder'), ('wayfair_professional', 'Wayfair Professional'), ('wickes', 'Wickes'), ('woolworths', 'Woolworths'), ('worten', 'Worten'), ('wurth_marketplace', 'Würth Marketplace'), ('xxxlutz', 'XXXLutz'), ('yoox', 'Yoox'), ('yves_rocher', 'Yves Rocher'), ('zalando', 'Zalando'), ('zap_group', 'Zap Group'), ('zooplus', 'Zooplus'), ('zoro', 'Zoro'), ('zupply', 'Zupply')], default='mirakl', help_text='Known Mirakl operator subtype for frontend and integration-specific behavior.', max_length=128),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='error_report_file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'mirakl_imports'})),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mirakl_imports', to='sales_channels.saleschannelfeed'),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='has_new_product_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='has_transformation_error_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='import_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='new_product_report_file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'mirakl_imports'})),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='offer_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='reason_status',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='remote_date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='remote_shop_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='transform_lines_in_error',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='transform_lines_in_success',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='transform_lines_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='transform_lines_with_warning',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='transformation_error_report_file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'mirakl_imports'})),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='transformed_file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'mirakl_imports'})),
        ),
    ]
