# Generated by Django 5.2 on 2026-03-13 16:41

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('mirakl', '0002_miraklsaleschannelfeed_miraklsaleschannel_sub_type_and_more'),
        ('properties', '0019_productpropertiesruleitem_properties__rule_id_884958_idx'),
        ('sales_channels', '0082_alter_syncrequest_sync_type_saleschannelfeed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiraklProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True)),
                ('successfully_created', models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.')),
                ('outdated', models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.')),
                ('outdated_since', models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True)),
                ('name', models.CharField(blank=True, default='', help_text='Mirakl product type label.', max_length=255)),
                ('imported', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mirakl Product Type',
                'verbose_name_plural': 'Mirakl Product Types',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='miraklproducttypeitem',
            name='unique_mirakl_category_property_item',
        ),
        migrations.RemoveField(
            model_name='miraklinternalproperty',
            name='accepted_values',
        ),
        migrations.RemoveField(
            model_name='miraklproducttypeitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='miraklremotecurrency',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='miraklremotelanguage',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelview',
            name='raw_data',
        ),
        migrations.AlterField(
            model_name='miraklproducttypeitem',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type_items', to='mirakl.miraklproperty'),
        ),
        migrations.AddField(
            model_name='miraklproducttype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Mirakl category this product type mirrors.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='mirakl.miraklcategory'),
        ),
        migrations.AddField(
            model_name='miraklproducttype',
            name='created_by_multi_tenant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='miraklproducttype',
            name='last_update_by_multi_tenant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='miraklproducttype',
            name='local_instance',
            field=models.ForeignKey(blank=True, help_text='Local product rule associated with this Mirakl product type.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.productpropertiesrule'),
        ),
        migrations.AddField(
            model_name='miraklproducttype',
            name='multi_tenant_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany'),
        ),
        migrations.AddField(
            model_name='miraklproducttype',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
        ),
        migrations.AddField(
            model_name='miraklproducttypeitem',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mirakl.miraklproducttype'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='miraklproducttypeitem',
            constraint=models.UniqueConstraint(fields=('product_type', 'property'), name='unique_mirakl_product_type_property_item'),
        ),
        migrations.AddConstraint(
            model_name='miraklproducttype',
            constraint=models.UniqueConstraint(fields=('sales_channel', 'remote_id'), name='unique_mirakl_product_type_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='miraklproducttype',
            constraint=models.UniqueConstraint(condition=models.Q(('local_instance__isnull', False)), fields=('sales_channel', 'local_instance'), name='unique_mirakl_product_type_local_rule_per_channel'),
        ),
    ]
