# Generated by Django 5.2 on 2026-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0003_miraklproducttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miraklpropertyselectvalue',
            name='translated_value',
        ),
        migrations.AddField(
            model_name='miraklproperty',
            name='description_translations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='miraklproperty',
            name='example',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='miraklproperty',
            name='hierarchy_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='miraklproperty',
            name='label_translations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='miraklproperty',
            name='type_parameters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='miraklproperty',
            name='unique_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='miraklpropertyselectvalue',
            name='label_translations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='miraklpropertyselectvalue',
            name='value_label_translations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
