# Generated by Django 5.2 on 2026-03-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0004_remove_miraklpropertyselectvalue_translated_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiraklDocumentType',
        ),
    ]
