# Generated by Django 5.2 on 2026-03-13 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('mirakl', '0005_delete_mirakldocumenttype'),
        ('properties', '0019_productpropertiesruleitem_properties__rule_id_884958_idx'),
        ('sales_channels', '0082_alter_syncrequest_sync_type_saleschannelfeed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='miraklproducttypeitem',
            name='unique_mirakl_product_type_property_item',
        ),
        migrations.RenameField(
            model_name='miraklproducttypeitem',
            old_name='property',
            new_name='remote_property',
        ),
        migrations.AddConstraint(
            model_name='miraklproducttypeitem',
            constraint=models.UniqueConstraint(fields=('product_type', 'remote_property'), name='unique_mirakl_product_type_property_item'),
        ),
    ]
