# Generated by Django 5.2 on 2026-03-13 20:24

import core.upload_paths
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0006_remove_miraklproducttypeitem_unique_mirakl_product_type_property_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miraklinternalpropertyoption',
            name='internal_property',
        ),
        migrations.RemoveField(
            model_name='miraklinternalpropertyoption',
            name='created_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='miraklinternalpropertyoption',
            name='last_update_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='miraklinternalpropertyoption',
            name='local_instance',
        ),
        migrations.RemoveField(
            model_name='miraklinternalpropertyoption',
            name='multi_tenant_company',
        ),
        migrations.RemoveField(
            model_name='miraklinternalpropertyoption',
            name='sales_channel',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='error_report_file',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='has_error_report',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='has_new_product_report',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='has_transformation_error_report',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='has_transformed_file',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='import_status',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='new_product_report_file',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='offer_response',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='raw_response',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='reason_status',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='remote_date_created',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='remote_import_id',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='remote_shop_id',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='source_file_name',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='summary_data',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='transform_lines_in_error',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='transform_lines_in_success',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='transform_lines_read',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='transform_lines_with_warning',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='transformation_error_report_file',
        ),
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='transformed_file',
        ),
        migrations.AddField(
            model_name='miraklproperty',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='error_report_file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'mirakl_imports'})),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='has_error_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='has_new_product_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='has_transformation_error_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='has_transformed_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='import_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='new_product_report_file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'mirakl_imports'})),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='offer_remote_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='product_remote_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='reason_status',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='remote_date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='remote_shop_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='transform_lines_in_error',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='transform_lines_in_success',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='transform_lines_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='transform_lines_with_warning',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='transformation_error_report_file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'mirakl_imports'})),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='transformed_file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'mirakl_imports'})),
        ),
        migrations.AlterField(
            model_name='miraklsaleschannelimport',
            name='type',
            field=models.CharField(choices=[('schema', 'Schema'), ('products', 'Products')], max_length=32),
        ),
        migrations.DeleteModel(
            name='MiraklInternalProperty',
        ),
        migrations.DeleteModel(
            name='MiraklInternalPropertyOption',
        ),
    ]
