# Generated by Django 5.2 on 2026-03-13 22:29

import core.upload_paths
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0008_backfill_miraklproperty_is_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='miraklproducttype',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'mirakl_product_type_templates'}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AddField(
            model_name='miraklproperty',
            name='representation_type',
            field=models.CharField(choices=[('property', 'Property'), ('unit', 'Unit'), ('default_value', 'Default value'), ('product_title', 'Product title'), ('product_subtitle', 'Product subtitle'), ('product_description', 'Product description'), ('product_short_description', 'Product short description'), ('product_bullet_point', 'Product bullet point'), ('product_sku', 'Product SKU'), ('product_internal_id', 'Product internal ID'), ('product_category', 'Product category'), ('product_configurable_sku', 'Product configurable SKU'), ('product_configurable_id', 'Product configurable ID'), ('product_active', 'Product active'), ('product_url_key', 'Product URL key'), ('product_ean', 'Product EAN'), ('thumbnail_image', 'Thumbnail image'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('price', 'Price'), ('discounted_price', 'Discounted price'), ('stock', 'Stock'), ('vat_rate', 'VAT rate'), ('allow_backorder', 'Allow backorder'), ('condition', 'Condition')], default='property', max_length=64),
        ),
    ]
