# Generated by Django 5.2 on 2026-03-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0009_miraklproducttype_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miraklsaleschannel',
            name='list_of_multiple_values_separator',
            field=models.CharField(blank=True, default='', help_text='Separator used by the operator for multiple-values list fields.', max_length=32),
        ),
        migrations.AddField(
            model_name='miraklsaleschannel',
            name='offer_prices_decimals',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of decimals allowed in offer prices.', null=True),
        ),
        migrations.AddField(
            model_name='miraklsaleschannel',
            name='operator_csv_delimiter',
            field=models.CharField(blank=True, choices=[('COMMA', 'Comma'), ('SEMICOLON', 'Semicolon')], default='', help_text='Delimiter expected in operator CSV files.', max_length=16),
        ),
        migrations.AddField(
            model_name='miraklsaleschannel',
            name='product_import_only_on_leaf',
            field=models.BooleanField(default=False, help_text='Prevents the import of products into non-leaf categories when enabled by the operator.'),
        ),
    ]
