# Generated by Django 5.2 on 2026-03-14 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0010_miraklsaleschannel_list_of_multiple_values_separator_and_more'),
        ('sales_channels', '0083_alter_remoteproperty_local_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiraklDocumentType',
            fields=[
                ('remotedocumenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotedocumenttype')),
                ('entity', models.CharField(blank=True, default='', max_length=64)),
                ('mime_types', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotedocumenttype',),
        ),
        migrations.AlterField(
            model_name='miraklproperty',
            name='representation_type',
            field=models.CharField(choices=[('property', 'Property'), ('unit', 'Unit'), ('default_value', 'Default value'), ('product_title', 'Product title'), ('product_subtitle', 'Product subtitle'), ('product_description', 'Product description'), ('product_short_description', 'Product short description'), ('product_bullet_point', 'Product bullet point'), ('product_sku', 'Product SKU'), ('product_internal_id', 'Product internal ID'), ('product_category', 'Product category'), ('product_configurable_sku', 'Product configurable SKU'), ('product_configurable_id', 'Product configurable ID'), ('product_active', 'Product active'), ('product_url_key', 'Product URL key'), ('product_ean', 'Product EAN'), ('thumbnail_image', 'Thumbnail image'), ('swatch_image', 'Swatch image'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('price', 'Price'), ('discounted_price', 'Discounted price'), ('stock', 'Stock'), ('vat_rate', 'VAT rate'), ('allow_backorder', 'Allow backorder'), ('condition', 'Condition')], default='property', max_length=64),
        ),
    ]
