# Generated by Django 5.2 on 2026-03-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0011_mirakldocumenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miraklproperty',
            name='representation_type_decided',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MiraklPublicDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=255)),
                ('property_code', models.CharField(max_length=255)),
                ('representation_type', models.CharField(choices=[('property', 'Property'), ('unit', 'Unit'), ('default_value', 'Default value'), ('product_title', 'Product title'), ('product_subtitle', 'Product subtitle'), ('product_description', 'Product description'), ('product_short_description', 'Product short description'), ('product_bullet_point', 'Product bullet point'), ('product_sku', 'Product SKU'), ('product_internal_id', 'Product internal ID'), ('product_category', 'Product category'), ('product_configurable_sku', 'Product configurable SKU'), ('product_configurable_id', 'Product configurable ID'), ('product_active', 'Product active'), ('product_url_key', 'Product URL key'), ('product_ean', 'Product EAN'), ('thumbnail_image', 'Thumbnail image'), ('swatch_image', 'Swatch image'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('price', 'Price'), ('discounted_price', 'Discounted price'), ('stock', 'Stock'), ('vat_rate', 'VAT rate'), ('allow_backorder', 'Allow backorder'), ('condition', 'Condition')], default='property', max_length=64)),
                ('default_value', models.CharField(blank=True, default='', max_length=255)),
                ('yes_text_value', models.CharField(blank=True, default='', max_length=255)),
                ('no_text_value', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Mirakl Public Definition',
                'verbose_name_plural': 'Mirakl Public Definitions',
                'constraints': [models.UniqueConstraint(fields=('hostname', 'property_code'), name='unique_mirakl_public_definition_per_host_property')],
            },
        ),
    ]
