# Generated by Django 5.2 on 2026-03-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0012_miraklproperty_representation_type_decided_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miraklproperty',
            name='hierarchy_code',
        ),
        migrations.RemoveField(
            model_name='miraklproperty',
            name='required',
        ),
        migrations.RemoveField(
            model_name='miraklproperty',
            name='requirement_level',
        ),
        migrations.RemoveField(
            model_name='miraklproperty',
            name='unique_code',
        ),
        migrations.RemoveField(
            model_name='miraklproperty',
            name='variant',
        ),
        migrations.AddField(
            model_name='miraklproducttypeitem',
            name='hierarchy_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='miraklproducttypeitem',
            name='requirement_level',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
