# Generated by Django 5.2 on 2026-03-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0013_remove_miraklproperty_hierarchy_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='mirakl.miraklproducttype'),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='sales_channel_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='mirakl.miraklsaleschannelview'),
        ),
    ]
