# Generated by Django 5.2 on 2026-03-14 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0014_miraklsaleschannelfeed_product_type_and_more'),
        ('sales_channels', '0084_alter_saleschannelfeed_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiraklSalesChannelFeedItem',
            fields=[
                ('saleschannelfeeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannelfeeditem')),
            ],
            options={
                'verbose_name': 'Mirakl Sales Channel Feed Item',
                'verbose_name_plural': 'Mirakl Sales Channel Feed Items',
            },
            bases=('sales_channels.saleschannelfeeditem',),
        ),
    ]
