# Generated by Django 5.2 on 2026-03-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0015_miraklsaleschannelfeeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='miraklsaleschannelimport',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
