# Generated by Django 5.2 on 2026-03-16 22:46

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('mirakl', '0016_miraklsaleschannelimport_tracking_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='miraklsaleschannel',
            name='last_differential_issues_fetch',
            field=models.DateTimeField(blank=True, help_text='Last successful Mirakl differential issues fetch boundary.', null=True),
        ),
        migrations.AddField(
            model_name='miraklsaleschannel',
            name='last_full_fetch',
            field=models.DateTimeField(blank=True, help_text='Last successful Mirakl full issues fetch boundary.', null=True),
        ),
        migrations.CreateModel(
            name='MiraklProductIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_code', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_label', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_rejected', models.BooleanField(db_index=True, default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('remote_product', models.ForeignKey(help_text='The Mirakl remote product this issue refers to.', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='mirakl.miraklproduct')),
                ('views', models.ManyToManyField(blank=True, help_text='Mirakl channels where this issue applies, when provided by the API.', related_name='product_issues', to='mirakl.miraklsaleschannelview')),
            ],
            options={
                'verbose_name': 'Mirakl Product Issue',
                'verbose_name_plural': 'Mirakl Product Issues',
                'ordering': ('remote_product_id', 'main_code', 'code', 'id'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
    ]
