# Generated by Django 5.2 on 2026-03-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0017_miraklsaleschannel_last_differential_issues_fetch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miraklsaleschannel',
            old_name='last_full_fetch',
            new_name='last_full_issues_fetch',
        ),
        migrations.AddField(
            model_name='miraklsaleschannel',
            name='last_product_imports_request_date',
            field=models.DateTimeField(blank=True, help_text='Last successful Mirakl P51 product imports polling boundary.', null=True),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='conversion_options_ai_enrichment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='conversion_options_ai_rewrite_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='conversion_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='integration_details_invalid_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='integration_details_products_not_accepted_in_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='integration_details_products_not_synchronized_in_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='integration_details_products_reimported',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='integration_details_products_successfully_synchronized',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='integration_details_products_with_synchronization_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='integration_details_products_with_wrong_identifiers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='integration_details_rejected_products',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
