# Generated by Django 5.2 on 2026-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0018_rename_last_full_fetch_miraklsaleschannel_last_full_issues_fetch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miraklsaleschannelimport',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='miraklsaleschannelfeed',
            name='offer_import_remote_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
