# Generated by Django 5.2 on 2026-03-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0019_remove_miraklsaleschannelimport_tracking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miraklproperty',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='miraklpublicdefinition',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
