# Generated by Django 5.2 on 2026-03-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0021_alter_miraklproperty_representation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mirakldocumenttype',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='mirakldocumenttype',
            name='mime_types',
        ),
        migrations.RemoveField(
            model_name='mirakldocumenttype',
            name='raw_data',
        ),
    ]
