# Generated by Django 5.2 on 2026-04-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0022_remove_mirakldocumenttype_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miraklsaleschannel',
            name='product_data_validation_by_channel',
            field=models.BooleanField(default=False, help_text='Indicates whether Mirakl validates product attributes per sales channel view.'),
        ),
    ]
