# Generated by Django 5.2 on 2026-04-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirakl', '0023_miraklsaleschannel_product_data_validation_by_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miraklproperty',
            name='value_list_code',
        ),
        migrations.RemoveField(
            model_name='miraklproperty',
            name='value_list_label',
        ),
        migrations.AddField(
            model_name='miraklproducttypeitem',
            name='value_list_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='miraklproducttypeitem',
            name='value_list_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
