# Generated by Django 5.2 on 2026-04-29 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_dashboardcard_url'),
        ('mirakl', '0024_remove_miraklproperty_value_list_code_and_more'),
        ('properties', '0021_alter_productpropertytexttranslation_language_and_more'),
        ('sales_channels', '0093_delete_remoteinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='miraklproducttype',
            name='unique_mirakl_product_type_per_channel',
        ),
        migrations.AddIndex(
            model_name='miraklproducttype',
            index=models.Index(fields=['sales_channel', 'remote_id'], name='mirakl_mira_sales_c_06d283_idx'),
        ),
    ]
