# Generated by Django 5.2 on 2025-05-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifysaleschannel',
            name='api_version',
        ),
        migrations.RemoveField(
            model_name='shopifysaleschannel',
            name='shop_url',
        ),
        migrations.AlterField(
            model_name='shopifysaleschannel',
            name='access_token',
            field=models.CharField(blank=True, help_text='OAuth access token for this Shopify store.', max_length=255, null=True),
        ),
    ]
