# Generated by Django 5.0.6 on 2025-05-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_remove_shopifysaleschannel_api_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysaleschannel',
            name='state',
            field=models.CharField(blank=True, help_text='Unique state used for OAuth verification', max_length=64, null=True, unique=True),
        ),
    ]
