# Generated by Django 5.0.6 on 2025-05-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_shopifysaleschannel_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifycurrency',
            name='currency_code',
        ),
    ]
