# Generated by Django 5.0.6 on 2025-05-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_propertyselectvaluetranslation_value'),
        ('shopify', '0004_remove_shopifycurrency_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproduct',
            name='default_variant_id',
            field=models.CharField(blank=True, help_text='The ID of the default variant returned when the product is created on Shopify.',
                                   max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='shopifysaleschannel',
            name='vendor_property',
            field=models.ForeignKey(blank=True, help_text='The product property that maps to Shopify vendor (brand).',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
    ]
