# Generated by Django 5.0.6 on 2025-05-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_shopifyproduct_default_variant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyimageproductassociation',
            name='current_position',
            field=models.IntegerField(default=10),
        ),
    ]
