# Generated by Django 5.0.6 on 2025-05-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0006_shopifyimageproductassociation_current_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproductproperty',
            name='key',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
