# Generated by Django 5.2 on 2025-05-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0007_shopifyproductproperty_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysaleschannelview',
            name='publication_id',
            field=models.CharField(blank=True, max_length=216, null=True),
        ),
    ]
