# Generated by Django 5.2 on 2025-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0008_shopifysaleschannelview_publication_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproductproperty',
            name='namespace',
            field=models.CharField(default='onesila', max_length=64),
        ),
    ]
