# Generated by Django 5.2.1 on 2025-05-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0009_shopifyproductproperty_namespace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopifyproductproperty',
            options={'verbose_name_plural': 'Shopify Product Properties'},
        ),
    ]
