# Generated by Django 5.2 on 2025-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0010_alter_shopifyproductproperty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysaleschannel',
            name='hmac',
            field=models.CharField(blank=True, help_text='HMAC received during external install for validation.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='shopifysaleschannel',
            name='is_external_install',
            field=models.BooleanField(default=False, help_text='True if the installation was initiated from the Shopify App Store.'),
        ),
        migrations.AddField(
            model_name='shopifysaleschannel',
            name='timestamp',
            field=models.CharField(blank=True, help_text='Timestamp received during external install for validation.', max_length=64, null=True),
        ),
    ]
