# Generated by Django 5.2 on 2025-05-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0011_shopifysaleschannel_hmac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysaleschannel',
            name='host',
            field=models.CharField(blank=True, help_text='Shopify host parameter used for HMAC validation and redirect context.', max_length=255, null=True),
        ),
    ]
