# Generated by Django 5.2 on 2025-05-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0012_shopifysaleschannel_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifysaleschannel',
            name='is_external_install',
        ),
    ]
