# Generated by Django 4.2.6 on 2023-10-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('products', '0001_initial'),
        ('core', '0001_initial'),
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('price_incl_vat', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PENDING_INVENTORY', 'Pending Inventory'), ('TOPICK', 'To Pick'), ('TOSHIP', 'To Ship'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled'), (
                    'HOLD', 'On Hold'), ('EXCHANGED', 'Exchanged'), ('REFUNDED', 'Refunded'), ('LOST', 'Lost'), ('MERGED', 'Merged'), ('DAMAGED', 'Damaged'), ('VOID', 'Void')], default='DRAFT', max_length=17)),
                ('reason_for_sale', models.CharField(choices=[('SALE', 'Sale'), ('RETURN', 'Return goods'), ('SAMPLE',
                 'Commercial Sample'), ('GIFT', 'Gift'), ('DOCUMENTS', 'Documents')], default='SALE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.customer')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('invoice_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoiceaddress_set', to='contacts.invoiceaddress')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shippingaddress_set', to='contacts.shippingaddress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
