# Generated by Django 5.1.1 on 2025-03-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='internal_company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reason_for_sale',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
