# Generated by Django 5.0.2 on 2024-03-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='company',
            new_name='customer',
        ),
    ]
