# Generated by Django 5.0.2 on 2024-04-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customer'),
        ('products', '0010_alter_product_sku'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
