# Generated by Django 5.0.7 on 2024-08-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reason_for_sale',
            field=models.CharField(choices=[('SALE', 'Sale'), ('SAMPLE', 'Commercial Sample'), ('GIFT', 'Gift')], default='SALE', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PROCESSING', 'Pending Processing'), ('PENDING_APPROVE_SHIPPING', 'Pending Shipping Approval'), (
                'TO_SHIP', 'To Ship'), ('AWAIT_INVENTORY', 'Awaiting Inventory'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled'), ('HOLD', 'On Hold')], default='DRAFT', max_length=24),
        ),
    ]
