# Generated by Django 5.1.1 on 2024-10-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_alter_address_options_and_more'),
        ('integrations', '0008_alter_integration_internal_company'),
        ('orders', '0010_order_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders', to='contacts.company'),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.integration'),
        ),
    ]
