# Generated by Django 5.1.1 on 2024-10-18 09:18

from django.db import migrations

def populate_internal_company(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Company = apps.get_model('contacts', 'Company')

    for order in Order.objects.all().iterator():
        internal_company = Company.objects.filter(multi_tenant_company=order.multi_tenant_company, is_internal_company=True).first()
        if internal_company:
            order.internal_company = internal_company
            order.save()
        else:
            order.delete()

def reverse_populate_internal_company(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.update(internal_company=None)

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_internal_company_order_source'),
    ]

    operations = [
        migrations.RunPython(populate_internal_company, reverse_populate_internal_company),
    ]
