# Generated by Django 5.2 on 2026-04-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorylocation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventorylocation',
            name='created_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='inventorylocation',
            name='last_update_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='inventorylocation',
            name='multi_tenant_company',
        ),
        migrations.RemoveField(
            model_name='inventorylocation',
            name='shippingaddress',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='created_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='last_update_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='mf_content_type',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='mt_content_type',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='multi_tenant_company',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='product',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryLocation',
        ),
        migrations.DeleteModel(
            name='InventoryMovement',
        ),
    ]
