# Generated by Django 5.0.2 on 2024-03-18 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorylocation_parent_location'),
        ('products', '0004_alter_bundlevariation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='products.product'),
        ),
    ]
