# Generated by Django 5.0.2 on 2024-04-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_multitenantuser_timezone'),
        ('inventory', '0004_alter_inventory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylocation',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='inventorylocation',
            unique_together={('name', 'multi_tenant_company')},
        ),
    ]
