# Generated by Django 5.0.2 on 2024-04-09 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventorylocation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylocation',
            name='parent_location',
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.internalshippingaddress'),
        ),
    ]
