# Generated by Django 5.0.7 on 2024-07-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventorylocation_precise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylocation',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
