# Generated by Django 5.0.7 on 2024-07-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventorylocation_name'),
        ('products', '0024_remove_product_base_product_product_base_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='products.product'),
        ),
    ]
