# Generated by Django 5.0.7 on 2024-07-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventory_product'),
        ('products', '0024_remove_product_base_product_product_base_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stocklocation',
            new_name='inventorylocation',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'inventorylocation')},
        ),
    ]
