# Generated by Django 5.0.7 on 2024-07-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_stocklocation_inventory_inventorylocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylocation',
            old_name='location',
            new_name='shippingaddress',
        ),
    ]
