# Generated by Django 5.0.7 on 2024-08-08 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_inventoryshippingaddress'),
        ('inventory', '0012_rename_location_inventorylocation_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylocation',
            name='shippingaddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.inventoryshippingaddress'),
        ),
    ]
