# Generated by Django 5.0.7 on 2024-08-08 07:39

from django.db import migrations

def delete_null_shippingaddress(apps, schema_editor):
    InventoryLocation = apps.get_model('inventory', 'InventoryLocation')
    InventoryLocation.objects.filter(shippingaddress__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventorylocation_shippingaddress'),
    ]

    operations = [
        migrations.RunPython(delete_null_shippingaddress),
    ]
