# Generated by Django 5.1 on 2024-08-29 19:14

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0133_alter_multitenantuser_timezone'),
        ('inventory', '0015_alter_inventorylocation_shippingaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mf_object_id', models.PositiveIntegerField()),
                ('mt_object_id', models.PositiveIntegerField()),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('mf_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='inventory_movements_from', to='contenttypes.contenttype')),
                ('mt_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements_to', to='contenttypes.contenttype')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('multi_tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['mf_content_type', 'mf_object_id'], name='inventory_i_mf_cont_225324_idx'), models.Index(fields=['mt_content_type', 'mt_object_id'], name='inventory_i_mt_cont_608137_idx'), models.Index(fields=['quantity'], name='inventory_i_quantit_4c52a1_idx'), models.Index(fields=['created_at'], name='inventory_i_created_75a91c_idx'), models.Index(fields=['mf_content_type', 'mf_object_id', 'mt_content_type', 'mt_object_id'], name='inventory_i_mf_cont_044914_idx')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
