# Generated by Django 5.1 on 2024-08-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_inventorymovement'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_quantit_4c52a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_created_75a91c_idx',
        ),
    ]
