# Generated by Django 5.1 on 2024-08-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_inventory_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='multi_tenant_user',
        ),
    ]
