# Generated by Django 5.1 on 2024-08-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_inventorymovement_multi_tenant_user'),
        ('products', '0036_billofmaterial_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
            preserve_default=False,
        ),
    ]
