# Generated by Django 5.2 on 2025-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eancodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eancode',
            name='ean_code',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
    ]
