# Generated by Django 5.0.2 on 2024-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_multitenantuser_timezone'),
        ('eancodes', '0004_remove_eancode_unique_ean_code_per_tenant_and_more'),
        ('products', '0024_remove_product_base_product_product_base_products'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eancode',
            name='unique_ean_code_per_tenant',
        ),
        migrations.AddConstraint(
            model_name='eancode',
            constraint=models.UniqueConstraint(condition=models.Q(('ean_code__isnull', False)), fields=(
                'multi_tenant_company', 'ean_code'), name='unique_ean_code_per_tenant', violation_error_message='Ean code already exists'),
        ),
    ]
