# Generated by Django 5.0.2 on 2024-07-16 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eancodes', '0005_remove_eancode_unique_ean_code_per_tenant_and_more'),
        ('products', '0024_remove_product_base_product_product_base_products'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eancode',
            name='ean_code_or_inherit_from_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='eancode',
            name='unique_ean_code_per_tenant',
        ),
        migrations.AlterUniqueTogether(
            name='eancode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eancode',
            name='inherit_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='inherited_ean_codes', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='eancode',
            name='inherit_from',
        ),
    ]
