# Generated by Django 5.0.2 on 2024-04-03 09:03

from django.db import migrations

# old custom migration related
class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
    ]
