# Generated by Django 5.2 on 2025-10-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_channels', '0047_alter_remoteproduct_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheinSalesChannel',
            fields=[
                ('saleschannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannel')),
                ('remote_id', models.CharField(blank=True, help_text='Remote Shein identifier for the connected store.', max_length=255, null=True, unique=True)),
                ('state', models.CharField(blank=True, help_text='Opaque value used to validate the OAuth redirect flow.', max_length=64, null=True, unique=True)),
                ('open_key_id', models.CharField(blank=True, help_text='Shein openKeyId returned by the authorization token exchange.', max_length=128, null=True)),
                ('secret_key_encrypted', models.CharField(blank=True, help_text='Encrypted secretKey received from Shein (base64 encoded).', max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, help_text='Decrypted secret key used to sign Shein API requests.', max_length=255, null=True)),
                ('supplier_id', models.BigIntegerField(blank=True, help_text='Supplier identifier returned by Shein during OAuth validation.', null=True)),
                ('supplier_source', models.IntegerField(blank=True, help_text='Supplier source value provided in the authorization payload.', null=True)),
                ('supplier_business_mode', models.CharField(blank=True, help_text='Supplier business mode reported by Shein.', max_length=64, null=True)),
                ('last_authorized_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful Shein authorization.', null=True)),
            ],
            options={
                'verbose_name': 'Shein Sales Channel',
                'verbose_name_plural': 'Shein Sales Channels',
            },
            bases=('sales_channels.saleschannel',),
        ),
    ]
