# Generated by Django 5.2 on 2025-10-24 15:17

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_multitenantcompany_active_and_more'),
        ('sales_channels', '0047_alter_remoteproduct_status'),
        ('shein', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheinRemoteMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True)),
                ('successfully_created', models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.')),
                ('outdated', models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.')),
                ('outdated_since', models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True)),
                ('name', models.CharField(help_text='Human friendly name returned by Shein for the marketplace.', max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Marks the default marketplace reported for the store.')),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel')),
            ],
            options={
                'verbose_name': 'Shein Remote Marketplace',
                'verbose_name_plural': 'Shein Remote Marketplaces',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SheinSalesChannelView',
            fields=[
                ('saleschannelview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.saleschannelview')),
                ('site_status', models.IntegerField(blank=True, help_text='Raw site status integer reported by Shein.', null=True)),
                ('store_type', models.IntegerField(blank=True, help_text='Store type reported by Shein.', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Marks the default storefront for this Shein sales channel.')),
                ('marketplace', models.ForeignKey(blank=True, help_text='Marketplace grouping returned by Shein for this storefront.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='shein.sheinremotemarketplace')),
            ],
            options={
                'verbose_name': 'Shein Sales Channel View',
                'verbose_name_plural': 'Shein Sales Channel Views',
            },
            bases=('sales_channels.saleschannelview',),
        ),
        migrations.CreateModel(
            name='SheinRemoteLanguage',
            fields=[
                ('remotelanguage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotelanguage')),
                ('remote_name', models.CharField(blank=True, help_text='Display name for the remote language.', max_length=128, null=True)),
                ('sales_channel_view', models.ForeignKey(blank=True, help_text='Storefront associated with this language, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_languages', to='shein.sheinsaleschannelview')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotelanguage',),
        ),
        migrations.CreateModel(
            name='SheinRemoteCurrency',
            fields=[
                ('remotecurrency_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotecurrency')),
                ('symbol_left', models.CharField(blank=True, help_text='Currency symbol placed to the left of the value.', max_length=16, null=True)),
                ('symbol_right', models.CharField(blank=True, help_text='Currency symbol placed to the right of the value.', max_length=16, null=True)),
                ('sales_channel_view', models.ForeignKey(blank=True, help_text='Storefront that uses this currency.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_currencies', to='shein.sheinsaleschannelview')),
            ],
            options={
                'verbose_name': 'Shein Remote Currency',
                'verbose_name_plural': 'Shein Remote Currencies',
            },
            bases=('sales_channels.remotecurrency',),
        ),
        migrations.AddConstraint(
            model_name='sheinremotemarketplace',
            constraint=models.UniqueConstraint(fields=('sales_channel', 'remote_id'), name='unique_shein_marketplace_per_channel'),
        ),
    ]
