# Generated by Django 5.2 on 2025-11-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0003_sheinproperty_sheinpropertyselectvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheinproducttype',
            name='translated_name',
            field=models.CharField(blank=True, help_text='Human readable name reported by Shein for the category/product type.', max_length=255, null=True),
        ),
    ]
