# Generated by Django 5.2 on 2025-12-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0004_sheinproducttype_translated_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheinsaleschannelview',
            name='merchant_location_choices',
            field=models.JSONField(blank=True, default=list, help_text='Available warehouse codes returned by Shein.'),
        ),
        migrations.AddField(
            model_name='sheinsaleschannelview',
            name='merchant_location_key',
            field=models.CharField(blank=True, help_text='Selected warehouse code for this storefront.', max_length=128, null=True),
        ),
    ]
