# Generated by Django 5.2 on 2025-12-18 16:02

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_deprecated_inspector_dashboard_cards'),
        ('sales_channels', '0051_alter_remoteproduct_status'),
        ('shein', '0005_sheinsaleschannelview_merchant_location_choices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheinProductIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(blank=True, db_index=True, default='', help_text='Shein submission version associated with this audit result (SPMP...).', max_length=255)),
                ('document_sn', models.CharField(blank=True, db_index=True, default='', help_text='Shein document serial number for the audit (SPMPA...).', max_length=255)),
                ('spu_name', models.CharField(blank=True, db_index=True, default='', help_text='Shein spu_name when available.', max_length=255)),
                ('skc_name', models.CharField(blank=True, db_index=True, default='', help_text='Shein skcName/skc_name when available.', max_length=255)),
                ('sku_codes', models.JSONField(blank=True, default=list, help_text='List of sku_code values returned by Shein (when available).')),
                ('audit_state', models.IntegerField(blank=True, db_index=True, help_text='Audit state integer returned by webhook notifications.', null=True)),
                ('document_state', models.IntegerField(blank=True, db_index=True, help_text='Document state integer returned by query-document-state.', null=True)),
                ('failed_reason', models.JSONField(blank=True, default=list, help_text='Failure reasons returned by Shein (list of {language, content}).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='True when the issue is currently active.')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Last payload used to populate this issue.')),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('remote_product', models.ForeignKey(help_text='Remote product this issue refers to.', on_delete=django.db.models.deletion.CASCADE, related_name='shein_issues', to='sales_channels.remoteproduct')),
            ],
            options={
                'verbose_name': 'Shein Product Issue',
                'verbose_name_plural': 'Shein Product Issues',
                'ordering': ('remote_product_id', 'version', 'document_sn'),
                'constraints': [models.UniqueConstraint(fields=('remote_product', 'version', 'document_sn', 'skc_name'), name='unique_shein_issue_per_submission')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
    ]
