# Generated by Django 5.2 on 2025-12-18 18:16

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_deprecated_inspector_dashboard_cards'),
        ('products', '0023_producttranslation_subtitle'),
        ('sales_channels', '0051_alter_remoteproduct_status'),
        ('shein', '0006_sheinproductissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sheincategory',
            name='package_type_required',
            field=models.BooleanField(default=False, help_text='Indicates whether Shein requires package type information for publishing.'),
        ),
        migrations.AddField(
            model_name='sheincategory',
            name='supplier_barcode_required',
            field=models.BooleanField(default=False, help_text='Indicates whether Shein requires supplier barcode information for publishing.'),
        ),
        migrations.AddField(
            model_name='sheincategory',
            name='support_sale_attribute_sort',
            field=models.BooleanField(blank=True, help_text='Whether sales attributes can be sorted (as reported by Shein).', null=True),
        ),
        migrations.CreateModel(
            name='SheinProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(max_length=255)),
                ('site_remote_id', models.CharField(blank=True, default='', help_text='Optional marketplace/site identifier to disambiguate category trees.', max_length=64)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel')),
            ],
            options={
                'verbose_name': 'Shein Product Category',
                'verbose_name_plural': 'Shein Product Categories',
                'unique_together': {('product', 'sales_channel')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
    ]
