# Generated by Django 5.2 on 2025-12-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0007_sheincategory_package_type_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheinproductcategory',
            name='product_type_remote_id',
            field=models.CharField(blank=True, default='', help_text='Optional Shein product type identifier for this category selection.', max_length=255),
        ),
    ]
