# Generated by Django 5.2 on 2025-12-18 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0051_alter_remoteproduct_status'),
        ('shein', '0008_sheinproductcategory_product_type_remote_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheinImageProductAssociation',
            fields=[
                ('remoteimageproductassociation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteimageproductassociation')),
                ('remote_url', models.URLField(blank=True, help_text='Shein-transformed image URL returned by /open-api/goods/transform-pic.', null=True)),
                ('original_url', models.URLField(blank=True, help_text='Original image URL used for transform-pic (before conversion).', null=True)),
                ('image_type', models.PositiveSmallIntegerField(blank=True, help_text='Shein image type used for transform-pic (1 main, 2 detail, 5 square, 6 color block, 7 detail page).', null=True)),
            ],
            options={
                'verbose_name': 'Shein Image Product Association',
                'verbose_name_plural': 'Shein Image Product Associations',
            },
            bases=('sales_channels.remoteimageproductassociation',),
        ),
    ]
