# Generated by Django 5.2 on 2025-12-19 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0009_sheinimageproductassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheinremotecurrency',
            name='sales_channel_view',
            field=models.ForeignKey(blank=True, help_text='Storefront/sub-site associated with this currency, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_currencies', to='shein.sheinsaleschannelview'),
        ),
    ]
