# Generated by Django 5.2 on 2025-12-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0051_alter_remoteproduct_status'),
        ('shein', '0010_sheinremotecurrency_sales_channel_view'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sheinremotecurrency',
            constraint=models.UniqueConstraint(condition=models.Q(('sales_channel_view__isnull', False)), fields=('sales_channel_view',), name='unique_shein_currency_per_view'),
        ),
    ]
