# Generated by Django 5.2 on 2025-12-19 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0051_alter_remoteproduct_status'),
        ('shein', '0011_sheinremotecurrency_unique_shein_currency_per_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheinProduct',
            fields=[
                ('remoteproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproduct')),
                ('spu_name', models.CharField(blank=True, help_text='SPU identifier returned by publishOrEdit (spu_name).', max_length=64, null=True)),
                ('skc_name', models.CharField(blank=True, help_text='SKC identifier returned by publishOrEdit (skc_name).', max_length=128, null=True)),
                ('sku_code', models.CharField(blank=True, help_text='SKU identifier returned by publishOrEdit (sku_code).', max_length=128, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteproduct',),
        ),
    ]
