# Generated by Django 5.2 on 2025-12-19 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_shein_categories(apps, schema_editor):
    SheinCategory = apps.get_model("shein", "SheinCategory")
    SheinCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_delete_deprecated_inspector_dashboard_cards"),
        ("sales_channels", "0051_alter_remoteproduct_status"),
        ("shein", "0012_sheinproduct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_shein_categories, migrations.RunPython.noop),
    ]
