# Generated by Django 5.2 on 2025-12-23 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_deprecated_inspector_dashboard_cards'),
        ('sales_channels', '0051_alter_remoteproduct_status'),
        ('shein', '0013_sheincategory_sales_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sheincategory',
            name='unique_shein_category_per_site',
        ),
        migrations.RemoveField(
            model_name='sheincategory',
            name='site_remote_id',
        ),
        migrations.AddField(
            model_name='sheincategory',
            name='created_by_multi_tenant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sheincategory',
            name='last_update_by_multi_tenant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sheincategory',
            name='multi_tenant_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany'),
        ),
        migrations.AddField(
            model_name='sheincategory',
            name='sales_channel',
            field=models.ForeignKey(default=1, help_text='Sales channel that owns this category tree.', on_delete=django.db.models.deletion.CASCADE, to='sales_channels.saleschannel'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='sheincategory',
            constraint=models.UniqueConstraint(fields=('sales_channel', 'remote_id'), name='unique_shein_category_per_channel'),
        ),
    ]
