# Generated by Django 5.2 on 2025-12-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0014_remove_sheincategory_unique_shein_category_per_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheinproductcategory',
            name='site_remote_id',
        ),
    ]
