# Generated by Django 5.2 on 2025-12-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0015_remove_sheinproductcategory_site_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheinimageproductassociation',
            name='image_group_code',
            field=models.CharField(blank=True, help_text='Shein image_group_code associated with the image set.', max_length=128, null=True),
        ),
    ]
