# Generated by Django 5.2 on 2026-01-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0016_sheinimageproductassociation_image_group_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheinremotelanguage',
            name='sales_channel_view',
        ),
    ]
