# Generated by Django 5.2 on 2026-01-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0019_sheinprice_sheinproductproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheinproducttypeitem',
            name='approved_value_ids',
            field=models.JSONField(blank=True, default=list, help_text='Allowed attribute_value_id list scoped to this product type.'),
        ),
    ]
