# Generated by Django 5.2 on 2026-02-04 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('products', '0023_producttranslation_subtitle'),
        ('properties', '0019_productpropertiesruleitem_properties__rule_id_884958_idx'),
        ('sales_channels', '0062_remove_syncrequest_sales_chann_status_97c9e2_idx_and_more'),
        ('shein', '0020_sheinproducttypeitem_approved_value_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sheinproductcategory',
            index=models.Index(fields=['product', 'sales_channel'], name='shein_shein_product_3d4ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='sheinproducttypeitem',
            index=models.Index(fields=['product_type', 'property'], name='shein_shein_product_c1bc85_idx'),
        ),
    ]
