# Generated by Django 5.2 on 2026-02-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0021_sheinproductcategory_shein_shein_product_3d4ff6_idx_and_more'),
        ('sales_channels', '0065_remoteproperty_type_remote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheinproperty',
            name='type',
        ),
    ]
