# Generated by Django 5.2 on 2026-02-23 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0075_remotedocumenttype'),
        ('shein', '0023_remove_sheinproperty_allows_unmapped_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheinDocumentType',
            fields=[
                ('remotedocumenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotedocumenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remotedocumenttype',),
        ),
    ]
