# Generated by Django 5.2 on 2026-02-23 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0077_remoteproductcategory_legacy_id'),
        ('shein', '0024_sheindocumenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheinProductCategoryNew',
            fields=[
                ('remoteproductcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remoteproductcategory')),
                ('product_type_remote_id', models.CharField(blank=True, default='', help_text='Optional Shein product type identifier for this category selection.', max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sales_channels.remoteproductcategory',),
        ),
    ]
