# Generated by Django 5.2 on 2026-02-24 13:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('products', '0023_producttranslation_subtitle'),
        ('sales_channels', '0077_remoteproductcategory_legacy_id'),
        ('shein', '0026_populate_sheinproductcategorynew'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SheinProductCategory',
            new_name='SheinProductCategoryOld',
        ),
        migrations.RenameIndex(
            model_name='sheinproductcategoryold',
            new_name='shein_shein_product_d1f411_idx',
            old_name='shein_shein_product_3d4ff6_idx',
        ),
    ]
