# Generated by Django 5.2 on 2026-02-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0077_remoteproductcategory_legacy_id'),
        ('shein', '0027_rename_sheinproductcategory_sheinproductcategoryold_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SheinProductCategoryNew',
            new_name='SheinProductCategory',
        ),
    ]
