# Generated by Django 5.2 on 2026-02-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0028_rename_sheinproductcategorynew_sheinproductcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheinproductcategory',
            options={'verbose_name': 'Shein Product Category', 'verbose_name_plural': 'Shein Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='sheinproductcategoryold',
            options={},
        ),
    ]
