# Generated by Django 5.2 on 2026-03-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0081_remove_remotedocument_remote_url_and_more'),
        ('shein', '0029_alter_sheinproductcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheinDocument',
            fields=[
                ('remotedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotedocument')),
                ('remote_url', models.URLField(blank=True, help_text='Public URL of the certificate file mirrored on Shein.', max_length=2048, null=True)),
                ('remote_filename', models.CharField(blank=True, help_text='Filename stored or returned by Shein for this document.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Shein Remote Document',
                'verbose_name_plural': 'Shein Remote Documents',
            },
            bases=('sales_channels.remotedocument',),
        ),
        migrations.CreateModel(
            name='SheinDocumentThroughProduct',
            fields=[
                ('remotedocumentproductassociation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_channels.remotedocumentproductassociation')),
                ('expire_time', models.DateTimeField(blank=True, help_text='Certificate expiration timestamp returned by Shein, when available.', null=True)),
                ('missing_status', models.BooleanField(default=False, help_text='Whether this certificate is currently marked as missing by Shein.')),
            ],
            options={
                'verbose_name': 'Shein Document Through Product',
                'verbose_name_plural': 'Shein Documents Through Products',
            },
            bases=('sales_channels.remotedocumentproductassociation',),
        ),
    ]
