# Generated by Django 5.2 on 2026-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0030_sheindocument_sheindocumentthroughproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheindocumentthroughproduct',
            name='missing_status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='NEW', help_text='Current Shein certificate status for this product association.', max_length=16),
        ),
    ]
