# Generated by Django 5.2 on 2026-04-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0031_alter_sheindocumentthroughproduct_missing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheinproduct',
            name='pending_external_documents',
            field=models.BooleanField(default=False, help_text='True while this product waits for non-uploadable SHEIN compliance documents to be completed manually.'),
        ),
    ]
