# Generated by Django 5.1.1 on 2025-03-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipointcontentgenerateprocess',
            name='input_tokens',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aipointcontentgenerateprocess',
            name='output_tokens',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
