# Generated by Django 5.1.1 on 2025-03-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_aipointcontentgenerateprocess_input_tokens_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiPointContentGenerateProcess',
        ),
    ]
