# Generated by Django 4.2.5 on 2023-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='language',
            field=models.CharField(choices=[('NL', 'Dutch'), ('EN', 'English')], max_length=5),
        ),
    ]
