# Generated by Django 4.2.5 on 2023-09-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_producttranslation_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundlevariation',
            old_name='company',
            new_name='multi_tenant_company',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='company',
            new_name='multi_tenant_company',
        ),
        migrations.RenameField(
            model_name='producttranslation',
            old_name='company',
            new_name='multi_tenant_company',
        ),
        migrations.RenameField(
            model_name='umbrellavariation',
            old_name='company',
            new_name='multi_tenant_company',
        ),
    ]
