# Generated by Django 4.2.5 on 2023-09-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_shared_multi_tenant', '0007_alter_multitenantcompany_language'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'multi_tenant_company')},
        ),
    ]
