# Generated by Django 4.2.6 on 2023-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='related_companies',
            field=models.ManyToManyField(blank=True, to='contacts.company'),
        ),
    ]
