# Generated by Django 5.0.2 on 2024-04-04 21:03

from django.db import migrations


def enforce_invoice_address_constraint(apps, schema_editor):
    Address = apps.get_model('contacts', 'Address')
    Company = apps.get_model('contacts', 'Company')

    Address.objects.update(is_invoice_address=False)

    for company in Company.objects.all():
        first_address = Address.objects.filter(company=company).first()
        if first_address:
            first_address.is_invoice_address = True
            first_address.save()


def reverse_enforce_invoice_address_constraint(apps, schema_editor):
    return True


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_address_contact'),
    ]

    operations = [
        migrations.RunPython(enforce_invoice_address_constraint, reverse_enforce_invoice_address_constraint),
    ]
