# Generated by Django 5.0.2 on 2024-04-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20240404_2203'),
        ('core', '0038_alter_multitenantuser_timezone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_invoice_address', True)), fields=('company',), name='unique_invoice_address_per_company', violation_error_message='Company already has an invoice address.'),
        ),
    ]
