# Generated by Django 5.0.2 on 2024-04-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_address_unique_invoice_address_per_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalShippingAddress',
            fields=[
            ],
            options={
                'verbose_name_plural': 'internal shipping addresses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.address',),
        ),
    ]
