# Generated by Django 5.0.2 on 2024-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_internalshippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='eori_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='related_companies',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vat_number',
        ),
        migrations.AddField(
            model_name='address',
            name='eori_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='people', to='contacts.person'),
        ),
        migrations.AddField(
            model_name='address',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
