# Generated by Django 5.0.2 on 2024-04-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20240410_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='contact',
        ),
    ]
