# Generated by Django 5.0.2 on 2024-04-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_company_email_company_language_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='people',
            field=models.ManyToManyField(blank=True, to='contacts.person'),
        ),
    ]
