# Generated by Django 5.0.2 on 2024-04-11 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_alter_address_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='people',
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.person'),
        ),
    ]
