# Generated by Django 5.0.2 on 2024-06-05 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_remove_address_people_address_person'),
        ('currencies', '0003_remove_currency_unique_is_default_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
    ]
