# Generated by Django 5.0.7 on 2024-08-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_company_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryShippingAddress',
            fields=[
            ],
            options={
                'verbose_name_plural': 'inventory shipping addresses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.address',),
        ),
    ]
