# Generated by Django 5.0.7 on 2024-08-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_inventoryshippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalShippingAddress',
        ),
    ]
