# Generated by Django 5.0.7 on 2024-08-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_delete_internalshippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalShippingAddress',
            fields=[
            ],
            options={
                'verbose_name_plural': 'internal shipping addresses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.address',),
        ),
    ]
