# Generated by Django 5.1.1 on 2024-09-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_address_created_by_multi_tenant_user_and_more'),
        ('core', '0134_demodatarelation_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'email', 'multi_tenant_company')},
        ),
    ]
