# Generated by Django 5.2 on 2025-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='user id')),
                ('chat_id', models.CharField(blank=True, help_text='Chat id is the same as user id', max_length=100, null=True, verbose_name='chat id')),
            ],
        ),
    ]
