# Generated by Django 5.2 on 2025-04-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertytranslation',
            unique_together=set(),
        ),
    ]
