# Generated by Django 4.2.9 on 2024-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_private_information',
            field=models.BooleanField(default=False),
        ),
    ]
