# Generated by Django 5.0.2 on 2024-04-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_multitenantuser_timezone'),
        ('properties', '0002_property_is_private_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyselectvaluetranslation',
            name='value',
            field=models.CharField(max_length=200, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='propertytranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyselectvaluetranslation',
            unique_together={('value', 'multi_tenant_company')},
        ),
        migrations.AlterUniqueTogether(
            name='propertytranslation',
            unique_together={('name', 'multi_tenant_company')},
        ),
    ]
