# Generated by Django 4.2.6 on 2023-10-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_shared_multi_tenant', '0008_alter_multitenantcompany_options_and_more'),
        ('properties', '0002_rename_propertytranslations_propertytranslation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='value',
        ),
        migrations.RemoveField(
            model_name='propertyselectvalue',
            name='value',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('INT', 'Integer'), ('FLOAT', 'Float'), ('STRING', 'String'), ('STRING', 'Text'), ('BOOLEAN',
                                   'Boolean'), ('DATE', 'Date'), ('DATETIME', 'Date time')], db_index=True, max_length=20, verbose_name='Type of property'),
        ),
        migrations.CreateModel(
            name='PropertySelectValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('NL', 'Dutch'), ('EN', 'English')], max_length=5)),
                ('value', models.CharField(max_length=200, unique=True, verbose_name='Value')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.PROTECT, to='django_shared_multi_tenant.multitenantcompany')),
                ('propertyselectvalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertyselectvalue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
