# Generated by Django 5.1.7 on 2025-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertytranslation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpropertytexttranslation',
            name='language',
            field=models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'French')], default='en', max_length=7),
        ),
        migrations.AlterField(
            model_name='propertyselectvaluetranslation',
            name='language',
            field=models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'French')], default='en', max_length=7),
        ),
        migrations.AlterField(
            model_name='propertytranslation',
            name='language',
            field=models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'French')], default='en', max_length=7),
        ),
    ]
