# Generated by Django 5.0.2 on 2024-05-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertyselectvaluetranslation_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyselectvaluetranslation',
            name='language',
            field=models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English'), ('en-gb', 'English GB'), ('he', 'Hebrew')], default='en', max_length=7),
        ),
        migrations.AlterField(
            model_name='propertytranslation',
            name='language',
            field=models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English'), ('en-gb', 'English GB'), ('he', 'Hebrew')], default='en', max_length=7),
        ),
    ]
