# Generated by Django 5.0.2 on 2024-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertyselectvaluetranslation_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyselectvaluetranslation',
            name='language',
            field=models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English'), ('en-gb', 'English GB')], default='en', max_length=7),
        ),
        migrations.AlterField(
            model_name='propertytranslation',
            name='language',
            field=models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English'), ('en-gb', 'English GB')], default='en', max_length=7),
        ),
    ]
