# Generated by Django 5.2 on 2025-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_productpropertytexttranslation_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpropertytexttranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('nl', 'Dutch'), ('de', 'German'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pl', 'Polish'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('et', 'Estonian'), ('fi', 'Finnish'), ('el', 'Greek'), ('hu', 'Hungarian'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('sk', 'Slovak'), (
                'sl', 'Slovenian'), ('sv', 'Swedish'), ('th', 'Thai'), ('ja', 'Japanese'), ('zh-hans', 'Chinese (Simplified)'), ('hi', 'Hindi'), ('pt-br', 'Portuguese (Brazil)'), ('ru', 'Russian'), ('af', 'Afrikaans'), ('ar', 'Arabic'), ('he', 'Hebrew'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('ko', 'Korean'), ('ms', 'Malay'), ('vi', 'Vietnamese'), ('fa', 'Persian'), ('ur', 'Urdu')], default='en', max_length=7),
        ),
        migrations.AlterField(
            model_name='propertyselectvaluetranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('nl', 'Dutch'), ('de', 'German'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pl', 'Polish'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('et', 'Estonian'), ('fi', 'Finnish'), ('el', 'Greek'), ('hu', 'Hungarian'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('sk', 'Slovak'), (
                'sl', 'Slovenian'), ('sv', 'Swedish'), ('th', 'Thai'), ('ja', 'Japanese'), ('zh-hans', 'Chinese (Simplified)'), ('hi', 'Hindi'), ('pt-br', 'Portuguese (Brazil)'), ('ru', 'Russian'), ('af', 'Afrikaans'), ('ar', 'Arabic'), ('he', 'Hebrew'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('ko', 'Korean'), ('ms', 'Malay'), ('vi', 'Vietnamese'), ('fa', 'Persian'), ('ur', 'Urdu')], default='en', max_length=7),
        ),
        migrations.AlterField(
            model_name='propertytranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('nl', 'Dutch'), ('de', 'German'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pl', 'Polish'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('et', 'Estonian'), ('fi', 'Finnish'), ('el', 'Greek'), ('hu', 'Hungarian'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('sk', 'Slovak'), (
                'sl', 'Slovenian'), ('sv', 'Swedish'), ('th', 'Thai'), ('ja', 'Japanese'), ('zh-hans', 'Chinese (Simplified)'), ('hi', 'Hindi'), ('pt-br', 'Portuguese (Brazil)'), ('ru', 'Russian'), ('af', 'Afrikaans'), ('ar', 'Arabic'), ('he', 'Hebrew'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('ko', 'Korean'), ('ms', 'Malay'), ('vi', 'Vietnamese'), ('fa', 'Persian'), ('ur', 'Urdu')], default='en', max_length=7),
        ),
    ]
