# Generated by Django 5.2 on 2025-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_productproperty_value_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyselectvaluetranslation',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Value'),
        ),
    ]
