# Generated by Django 5.2 on 2025-04-30 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('products', '0005_alter_product_sku_alter_producttranslation_name_and_more'),
        ('properties', '0007_productproperty_properties__product_32a769_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productproperty',
            index=models.Index(fields=['property', 'value_select'], name='properties__propert_04eaf9_idx'),
        ),
    ]
