# Generated by Django 5.0.2 on 2024-07-18 16:01

import properties.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_base_product_product_base_products'),
        ('properties', '0007_productpropertytexttranslation_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='property',
            managers=[
                ('objects', properties.managers.PropertyManager()),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='internal_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Internal Name'),
        ),
        migrations.AlterUniqueTogether(
            name='productproperty',
            unique_together={('product', 'property')},
        ),
    ]
