# Generated by Django 5.0.2 on 2024-07-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_managers_property_internal_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='property',
            managers=[
            ],
        ),
    ]
