# Generated by Django 5.2 on 2025-05-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_propertyselectvaluetranslation_value'),
        ('properties', '0008_productproperty_properties__propert_04eaf9_idx'),
    ]

    operations = [
    ]
