# Generated by Django 5.0.2 on 2024-07-18 16:18

from django.db import migrations

def add_product_type_property(apps, schema_editor):
    from django.utils.text import slugify
    from core.defaults import get_product_type_name

    Property = apps.get_model('properties', 'Property')
    PropertyTranslation = apps.get_model('properties', 'PropertyTranslation')
    MultiTenantCompany = apps.get_model('core', 'MultiTenantCompany')

    for multi_tenant_company in MultiTenantCompany.objects.all():
        # initially a I tried a manager method but it fails even with this:
        # https://docs.djangoproject.com/en/5.0/topics/migrations/
        language = multi_tenant_company.language
        name = get_product_type_name(language)
        internal_name = slugify(name).replace('-', '_')

        property_instance, _ = Property.objects.get_or_create(
            type='SELECT',
            is_private_information=True,
            is_product_type=True,
            internal_name=internal_name,
            multi_tenant_company=multi_tenant_company
        )


        PropertyTranslation.objects.create(
            property=property_instance,
            language=language,
            name=name,
            multi_tenant_company=multi_tenant_company
        )

class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_property_managers'),
    ]

    operations = [
        migrations.RunPython(add_product_type_property)
    ]
