# Generated by Django 5.2 on 2025-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_merge_20250512_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='non_deletable',
            field=models.BooleanField(default=False),
        ),
    ]
