# Generated by Django 5.0.2 on 2024-07-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_media_image'),
        ('properties', '0010_add_product_type_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyselectvaluetranslation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.image'),
        ),
    ]
