# Generated by Django 5.2 on 2025-06-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20250624_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('propertytranslation__name',), 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyselectvalue',
            options={'ordering': ('propertyselectvaluetranslation__value',)},
        ),
    ]
