# Generated by Django 5.0.2 on 2024-07-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_propertyselectvaluetranslation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_private_information',
        ),
        migrations.AddField(
            model_name='property',
            name='add_to_filters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_public_information',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('INT', 'Integer'), ('FLOAT', 'Float'), ('TEXT', 'Text'), ('DESCRIPTION', 'Description'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DATETIME', 'Date time'), ('SELECT', 'Select'), ('MULTISELECT', 'Multi Select')], db_index=True, max_length=20, verbose_name='Type of property'),
        ),
    ]
