# Generated by Django 5.0.2 on 2024-07-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_media_image'),
        ('properties', '0012_remove_property_is_private_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyselectvaluetranslation',
            name='image',
        ),
        migrations.AddField(
            model_name='propertyselectvalue',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.image'),
        ),
    ]
