# Generated by Django 5.2 on 2025-07-21 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('properties', '0013_internal_name_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_name__isnull', False)), fields=('multi_tenant_company', 'internal_name'), name='unique_internal_name_per_company', violation_error_message='This internal name already exists for this company.'),
        ),
    ]
