# Generated by Django 5.0.7 on 2024-07-22 14:10

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_alter_multitenantuserlogintoken_token'),
        ('properties', '0013_remove_propertyselectvaluetranslation_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPropertiesRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('product_type', models.ForeignKey(limit_choices_to={'is_product_type': True},
                 on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Product Type')),
            ],
            options={
                'verbose_name_plural': 'Product Properties Rules',
                'unique_together': {('product_type', 'multi_tenant_company')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductPropertiesRuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('REQUIRED_IN_CONFIGURATOR', 'Required in Configurator'), ('OPTIONAL_IN_CONFIGURATOR',
                 'Optional in Configurator'), ('REQUIRED', 'Required'), ('OPTIONAL', 'Optional')], max_length=25, verbose_name='Type')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Property')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='rule_items', to='properties.productpropertiesrule', verbose_name='Rule')),
            ],
            options={
                'verbose_name_plural': 'Product Properties Rule Items',
                'unique_together': {('property', 'rule', 'multi_tenant_company')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
