# Generated by Django 5.2 on 2025-09-04 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_multitenantcompany_active_and_more'),
        ('properties', '0014_property_unique_internal_name_per_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productpropertytexttranslation',
            index=models.Index(fields=['product_property', 'language'], name='properties__product_b49782_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyselectvaluetranslation',
            index=models.Index(fields=['propertyselectvalue', 'language'], name='properties__propert_d93004_idx'),
        ),
        migrations.AddIndex(
            model_name='propertytranslation',
            index=models.Index(fields=['property', 'language'], name='properties__propert_6d90d9_idx'),
        ),
    ]
