# Generated by Django 5.0.7 on 2024-07-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_productpropertiesrule_productpropertiesruleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertiesruleitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='productpropertiesrule',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertyselectvalue', verbose_name='Product Type'),
        ),
    ]
