# Generated by Django 5.0.7 on 2024-07-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_productpropertiesruleitem_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpropertiesruleitem',
            options={'ordering': ('sort_order',), 'verbose_name_plural': 'Product Properties Rule Items'},
        ),
    ]
