# Generated by Django 5.2 on 2025-09-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_productpropertytexttranslation_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyselectvalue',
            options={'ordering': ('id',)},
        ),
    ]
