# Generated by Django 5.2 on 2025-11-06 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_multitenantcompany_active_and_more'),
        ('properties', '0017_alter_propertyselectvalue_options'),
        ('sales_channels', '0050_populate_saleschannelgptfeed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productpropertiesrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productpropertiesrule',
            name='sales_channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales_channels.saleschannel', verbose_name='Sales Channel'),
        ),
        migrations.AddConstraint(
            model_name='productpropertiesrule',
            constraint=models.UniqueConstraint(fields=('product_type', 'multi_tenant_company', 'sales_channel'), name='unique_product_properties_rule_per_sales_channel', nulls_distinct=False),
        ),
    ]
