# Generated by Django 5.0.7 on 2024-07-24 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_productpropertiesruleitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='value_multi_select',
            field=models.ManyToManyField(blank=True, related_name='value_multi_select_set', to='properties.propertyselectvalue'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='value_select',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_select_set', to='properties.propertyselectvalue'),
        ),
    ]
