# Generated by Django 5.0.7 on 2024-07-25 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_productproperty_value_multi_select_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpropertiesrule',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.propertyselectvalue', verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='productpropertiesruleitem',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='productpropertiesruleitem',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items',
                                    to='properties.productpropertiesrule', verbose_name='Rule'),
        ),
        migrations.AlterField(
            model_name='propertyselectvalue',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.property'),
        ),
    ]
