# Generated by Django 5.2 on 2026-02-04 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dashboardsection_description'),
        ('properties', '0018_alter_productpropertiesrule_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productpropertiesruleitem',
            index=models.Index(fields=['rule', 'property'], name='properties__rule_id_884958_idx'),
        ),
    ]
