# Generated by Django 5.1.1 on 2024-09-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_auto_create_product_properties_rules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyselectvaluetranslation',
            unique_together=set(),
        ),
    ]
