# Generated by Django 5.1.1 on 2025-02-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_alter_propertyselectvaluetranslation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
