# Generated by Django 5.1.1 on 2025-02-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_property_has_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertiesrule',
            name='require_ean_code',
            field=models.BooleanField(default=False),
        ),
    ]
