# Generated by Django 4.2.6 on 2023-10-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_shared_multi_tenant', '0008_alter_multitenantcompany_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=12)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.PROTECT, to='django_shared_multi_tenant.multitenantcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
