# Generated by Django 4.2.5 on 2023-09-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_shared_multi_tenant', '0007_alter_multitenantcompany_language'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyTranslations',
            new_name='PropertyTranslation',
        ),
        migrations.AlterModelOptions(
            name='productproperty',
            options={'verbose_name_plural': 'Product Properties'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
