# Generated by Django 4.2.5 on 2023-09-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertytranslations_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productproperty',
            old_name='company',
            new_name='multi_tenant_company',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='company',
            new_name='multi_tenant_company',
        ),
        migrations.RenameField(
            model_name='propertyselectvalue',
            old_name='company',
            new_name='multi_tenant_company',
        ),
        migrations.RenameField(
            model_name='propertytranslations',
            old_name='company',
            new_name='multi_tenant_company',
        ),
    ]
