# Generated by Django 5.2 on 2026-04-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
