# Generated by Django 5.1.1 on 2025-02-25 10:57

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_time', models.IntegerField()),
                ('max_time', models.IntegerField()),
                ('unit', models.IntegerField(choices=[(1, 'Hour'), (2, 'Day'), (3, 'Week'), (4, 'Month')])),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LeadTimeForShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('leadtime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lead_times.leadtime')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('shippingaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.shippingaddress')),
            ],
            options={
                'unique_together': {('multi_tenant_company', 'shippingaddress')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='leadtime',
            name='shippingaddresses',
            field=models.ManyToManyField(blank=True, related_name='leadtimes', through='lead_times.LeadTimeForShippingAddress', to='contacts.shippingaddress'),
        ),
        migrations.AddConstraint(
            model_name='leadtime',
            constraint=models.CheckConstraint(condition=models.Q(('max_time__gte', models.F('min_time'))), name='Maximum Time cannot be less then Minimum Time'),
        ),
        migrations.AddConstraint(
            model_name='leadtime',
            constraint=models.CheckConstraint(condition=models.Q(('max_time__gte', 0)), name='Maximum time cannot be 0'),
        ),
        migrations.AddConstraint(
            model_name='leadtime',
            constraint=models.CheckConstraint(condition=models.Q(('min_time__gte', 0)), name='Minimum Time cannot be 0'),
        ),
        migrations.AlterUniqueTogether(
            name='leadtime',
            unique_together={('multi_tenant_company', 'min_time', 'max_time', 'unit')},
        ),
    ]
