# Generated by Django 5.0.7 on 2024-07-30 07:29

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_company_currency'),
        ('core', '0133_alter_multitenantuser_timezone'),
        ('lead_times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTimeForShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leadtime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lead_times.leadtime')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('shippingaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.shippingaddress')),
            ],
            options={
                'unique_together': {('multi_tenant_company', 'shippingaddress', 'leadtime')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
