# Generated by Django 5.2 on 2026-04-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_times', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadtimeforshippingaddress',
            name='leadtime',
        ),
        migrations.AlterUniqueTogether(
            name='leadtimeforshippingaddress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leadtimeforshippingaddress',
            name='created_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='leadtimeforshippingaddress',
            name='last_update_by_multi_tenant_user',
        ),
        migrations.RemoveField(
            model_name='leadtimeforshippingaddress',
            name='multi_tenant_company',
        ),
        migrations.RemoveField(
            model_name='leadtimeforshippingaddress',
            name='shippingaddress',
        ),
        migrations.DeleteModel(
            name='LeadTime',
        ),
        migrations.DeleteModel(
            name='LeadTimeForShippingAddress',
        ),
    ]
