# Generated by Django 5.0.6 on 2025-05-03 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
        ('core', '0007_alter_multitenantcompany_ai_points_and_more'),
        ('lead_times', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leadtime',
            name='max_time_gte_min_time',
        ),
        migrations.RemoveConstraint(
            model_name='leadtime',
            name='max_time_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='leadtime',
            name='min_time_non_negative',
        ),
        migrations.AddConstraint(
            model_name='leadtime',
            constraint=models.CheckConstraint(check=models.Q(('max_time__gte', models.F('min_time'))), name='Maximum Time cannot be less then Minimum Time'),
        ),
        migrations.AddConstraint(
            model_name='leadtime',
            constraint=models.CheckConstraint(check=models.Q(('max_time__gte', 0)), name='Maximum time cannot be 0'),
        ),
        migrations.AddConstraint(
            model_name='leadtime',
            constraint=models.CheckConstraint(check=models.Q(('min_time__gte', 0)), name='Minimum Time cannot be 0'),
        ),
    ]
