# Generated by Django 5.0.7 on 2024-07-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_times', '0003_auto_20240730_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadtime',
            name='unit',
            field=models.CharField(choices=[('1', 'Hour'), ('2', 'Day'), ('3', 'Week'), ('4', 'Month')], max_length=5),
        ),
    ]
