# Generated by Django 5.0.7 on 2024-07-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_times', '0004_alter_leadtime_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadtime',
            name='unit',
            field=models.IntegerField(choices=[('1', 'Hour'), ('2', 'Day'), ('3', 'Week'), ('4', 'Month')]),
        ),
    ]
