# Generated by Django 5.0.7 on 2024-07-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_alter_multitenantuser_timezone'),
        ('lead_times', '0005_alter_leadtime_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadtime',
            unique_together={('multi_tenant_company', 'min_time', 'max_time', 'unit')},
        ),
    ]
