# Generated by Django 5.0.7 on 2024-07-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_company_currency'),
        ('core', '0133_alter_multitenantuser_timezone'),
        ('lead_times', '0008_alter_leadtimeforshippingaddress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leadtime',
            constraint=models.CheckConstraint(check=models.Q(('max_time__gte', models.F('min_time'))), name='Maximum Time cannot be less then Minimum Time'),
        ),
        migrations.AddConstraint(
            model_name='leadtime',
            constraint=models.CheckConstraint(check=models.Q(('max_time__gte', 0)), name='Maximum time cannot be 0'),
        ),
        migrations.AddConstraint(
            model_name='leadtime',
            constraint=models.CheckConstraint(check=models.Q(('min_time__gte', 0)), name='Minimum Time cannot be 0'),
        ),
    ]
