# Generated by Django 5.0.7 on 2024-08-04 19:48

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_alter_multitenantuser_timezone'),
        ('lead_times', '0009_leadtime_maximum_time_cannot_be_less_then_minimum_time_and_more'),
        ('products', '0025_rename_always_on_stock_product_allow_backorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTimeProductOutOfStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leadtime_outofstock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lead_times.leadtime')),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('multi_tenant_company', 'product')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='leadtime',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='leadtimes_outofstock',
                                         through='lead_times.LeadTimeProductOutOfStock', to='products.product'),
        ),
    ]
