# Generated by Django 5.1.1 on 2025-02-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_times', '0011_leadtime_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadtime',
            name='products',
        ),
        migrations.DeleteModel(
            name='LeadTimeProductOutOfStock',
        ),
    ]
