# Generated by Django 5.1.1 on 2024-10-17 21:40

import accounting.helpers
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0134_demodatarelation_created_by_multi_tenant_user_and_more'),
        ('order_returns', '0005_rename_orderitem_orderreturnitem_order_item_and_more'),
        ('orders', '0010_order_created_by_multi_tenant_user_and_more'),
        ('taxes', '0007_vatrate_created_by_multi_tenant_user_and_more'),
        ('integrations', '0005_alter_integrationlog_options'),
        ('sales_channels', '0032_remove_saleschannel_id_and_more'),
        ('magento2', '0014_alter_magentoattributesetattribute_remote_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('document_date', models.DateField()),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_address', models.TextField()),
                ('vendor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vendor_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_invoice_address', models.TextField()),
                ('customer_shipping_address', models.TextField(blank=True, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(max_length=20)),
                ('vendor_vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('credit_note_pdf', models.FileField(upload_to=accounting.helpers.get_credit_note_pdf_upload_path)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('order_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_returns.orderreturn')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preserved_vat_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.creditnote')),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('order_return_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_items', to='order_returns.orderreturnitem')),
                ('vat_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxes.vatrate')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('document_date', models.DateField()),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_address', models.TextField()),
                ('vendor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vendor_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_invoice_address', models.TextField()),
                ('customer_shipping_address', models.TextField(blank=True, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(max_length=20)),
                ('vendor_vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to=accounting.helpers.get_invoice_pdf_upload_path)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preserved_vat_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.invoice')),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='orders.orderitem')),
                ('vat_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxes.vatrate')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
