# Generated by Django 5.1.1 on 2024-10-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='price_incl_vat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price_incl_vat',
            field=models.BooleanField(default=True),
        ),
    ]
