# Generated by Django 5.1.1 on 2024-10-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_creditnote_price_incl_vat_invoice_price_incl_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
