# Generated by Django 5.1.1 on 2024-10-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_creditnote_subtotal_alter_invoice_subtotal'),
        ('core', '0134_demodatarelation_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='document_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='document_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='creditnote',
            unique_together={('document_number', 'multi_tenant_company')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('document_number', 'multi_tenant_company')},
        ),
    ]
