# Generated by Django 5.1.1 on 2024-10-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_creditnote_tax_amount_invoice_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
