# Generated by Django 5.1.1 on 2024-10-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountingmirroraccount_accountingmirrorcreditnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingmirrorcreditnote',
            name='outdated',
            field=models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.'),
        ),
        migrations.AddField(
            model_name='accountingmirrorcreditnote',
            name='outdated_since',
            field=models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True),
        ),
        migrations.AddField(
            model_name='accountingmirrorcreditnote',
            name='successfully_created',
            field=models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.'),
        ),
        migrations.AddField(
            model_name='accountingmirrorcustomer',
            name='outdated',
            field=models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.'),
        ),
        migrations.AddField(
            model_name='accountingmirrorcustomer',
            name='outdated_since',
            field=models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True),
        ),
        migrations.AddField(
            model_name='accountingmirrorcustomer',
            name='successfully_created',
            field=models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.'),
        ),
        migrations.AddField(
            model_name='accountingmirrorinvoice',
            name='outdated',
            field=models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.'),
        ),
        migrations.AddField(
            model_name='accountingmirrorinvoice',
            name='outdated_since',
            field=models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True),
        ),
        migrations.AddField(
            model_name='accountingmirrorinvoice',
            name='successfully_created',
            field=models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.'),
        ),
        migrations.AddField(
            model_name='accountingmirrorvat',
            name='outdated',
            field=models.BooleanField(default=False, help_text='Indicates if the remote product is outdated due to an error.'),
        ),
        migrations.AddField(
            model_name='accountingmirrorvat',
            name='outdated_since',
            field=models.DateTimeField(blank=True, help_text='Timestamp indicating when the object became outdated.', null=True),
        ),
        migrations.AddField(
            model_name='accountingmirrorvat',
            name='successfully_created',
            field=models.BooleanField(default=True, help_text='Indicates if the object was successfully created in the remote system.'),
        ),
        migrations.AlterField(
            model_name='accountingmirrorcreditnote',
            name='remote_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accountingmirroraccount'),
        ),
        migrations.AlterField(
            model_name='accountingmirrorcreditnote',
            name='remote_id',
            field=models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountingmirrorcustomer',
            name='remote_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accountingmirroraccount'),
        ),
        migrations.AlterField(
            model_name='accountingmirrorcustomer',
            name='remote_id',
            field=models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountingmirrorinvoice',
            name='remote_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accountingmirroraccount'),
        ),
        migrations.AlterField(
            model_name='accountingmirrorinvoice',
            name='remote_id',
            field=models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountingmirrorvat',
            name='remote_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accountingmirroraccount'),
        ),
        migrations.AlterField(
            model_name='accountingmirrorvat',
            name='remote_id',
            field=models.CharField(blank=True, help_text='ID of the object in the remote system', max_length=255, null=True),
        ),
    ]
