# Generated by Django 5.1.1 on 2024-10-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_accountingmirrorcreditnote_local_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='order_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
