# Generated by Django 5.1.1 on 2024-11-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_remove_creditnote_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
