# Generated by Django 5.0.7 on 2024-08-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_returns', '0002_orderreturnitem_orderreturn_orderreturnattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
