# Generated by Django 5.1.1 on 2024-10-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_returns', '0004_orderreturn_created_by_multi_tenant_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderreturnitem',
            old_name='orderitem',
            new_name='order_item',
        ),
        migrations.RenameField(
            model_name='orderreturnitem',
            old_name='orderreturn',
            new_name='order_return',
        ),
    ]
