# Generated by Django 5.1.1 on 2024-10-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_returns', '0005_rename_orderitem_orderreturnitem_order_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderreturnattachment',
            old_name='orderreturn',
            new_name='order_return',
        ),
    ]
