# Generated by Django 5.2 on 2025-08-28 15:43

import core.models.core
import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
import webhooks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_multitenantcompany_active_and_more'),
        ('integrations', '0008_alter_integration_hostname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookIntegration',
            fields=[
                ('integration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.integration')),
                ('topic', models.CharField(choices=[('product', 'product'), ('ean_code', 'ean_code'), ('price_list', 'price_list'), ('price_list_item', 'price_list_item'), ('media', 'media'), ('media_through', 'media_through'), ('property', 'property'), ('select_value', 'select_value'), ('property_rule', 'property_rule'), ('property_rule_item', 'property_rule_item'), ('product_property', 'product_property'), ('sales_channel_view_assign', 'sales_channel_view_assign'), ('all', 'all')], max_length=32)),
                ('version', models.CharField(choices=[('2025-08-01', '2025-08-01')], default='2025-08-01', max_length=10)),
                ('url', models.URLField()),
                ('secret', models.CharField(default=webhooks.models.generate_secret, max_length=128)),
                ('user_agent', models.CharField(default='OneSila-Webhook/1.0', max_length=64)),
                ('timeout_ms', models.IntegerField(default=webhooks.models.default_timeout_ms)),
                ('mode', models.CharField(choices=[('full', 'full'), ('delta', 'delta')], default='full', max_length=5)),
                ('extra_headers', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('retention_policy', models.CharField(choices=[('3m', '3m'), ('6m', '6m'), ('12m', '12m')], default='6m', max_length=3)),
            ],
            options={
                'indexes': [models.Index(fields=['topic'], name='webhooks_we_topic_df6b60_idx')],
            },
            bases=('integrations.integration',),
        ),
        migrations.CreateModel(
            name='WebhookOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('topic', models.CharField(choices=[('product', 'product'), ('ean_code', 'ean_code'), ('price_list', 'price_list'), ('price_list_item', 'price_list_item'), ('media', 'media'), ('media_through', 'media_through'), ('property', 'property'), ('select_value', 'select_value'), ('property_rule', 'property_rule'), ('property_rule_item', 'property_rule_item'), ('product_property', 'product_property'), ('sales_channel_view_assign', 'sales_channel_view_assign'), ('all', 'all')], db_index=True, max_length=32)),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], db_index=True, max_length=10)),
                ('subject_type', models.CharField(db_index=True, max_length=32)),
                ('subject_id', models.CharField(db_index=True, max_length=64)),
                ('sequence', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('webhook_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhooks.webhookintegration')),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENDING', 'SENDING'), ('DELIVERED', 'DELIVERED'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', max_length=10)),
                ('attempt', models.IntegerField(db_index=True, default=0)),
                ('response_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('response_body_snippet', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
                ('webhook_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookintegration')),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookoutbox')),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('sent_at', models.DateTimeField()),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('response_body_snippet', models.TextField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='webhooks.webhookdelivery')),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
            ],
            options={
                'indexes': [models.Index(fields=['delivery', 'number'], name='webhooks_we_deliver_d6d158_idx'), models.Index(fields=['delivery', 'created_at'], name='webhooks_we_deliver_c90ca8_idx')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='webhookoutbox',
            index=models.Index(fields=['webhook_integration', 'created_at'], name='webhooks_we_webhook_c2f398_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookoutbox',
            index=models.Index(fields=['topic', 'created_at'], name='webhooks_we_topic_f5c47d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookoutbox',
            index=models.Index(fields=['subject_type', 'subject_id', 'created_at'], name='webhooks_we_subject_71f0c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DELIVERED')), fields=('outbox',), name='webhook_delivery_unique_delivered_per_outbox'),
        ),
    ]
