# Generated by Django 5.2 on 2025-08-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='attempt',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
