# Generated by Django 5.2 on 2025-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_alter_webhookdelivery_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookintegration',
            name='retention_policy',
            field=models.CharField(choices=[('3m', '3m'), ('6m', '6m'), ('12m', '12m')], default='3m', max_length=3),
        ),
    ]
