# Generated by Django 5.2 on 2025-09-08 08:27

import django.core.validators
import webhooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_alter_webhookintegration_retention_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookintegration',
            name='timeout_ms',
            field=models.IntegerField(default=webhooks.models.default_timeout_ms, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
