# Generated by Django 5.0.7 on 2024-08-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='has_missing_information',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='has_missing_optional_information',
            field=models.BooleanField(default=True),
        ),
    ]
