# Generated by Django 5.0.7 on 2024-08-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_inspector', '0002_alter_inspector_has_missing_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomMismatchProductTypeInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block BOM Mismatch Product Type',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='BomMissingMandatoryInformationInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block BOM Missing Mandatory Information',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='DuplicateVariationsInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Duplicate Variations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='InspectorBlockInactiveBundleItems',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Inactive Bundle Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='InspectorBlockInactivePieces',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Inactive Pieces',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='InspectorBlockMissingBillOfMaterials',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Bill of Materials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='InspectorBlockMissingBundleItems',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Bundle Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='InspectorBlockMissingPrices',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Prices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='InspectorBlockMissingSupplierProducts',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Supplier Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='InspectorBlockMissingVariation',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Variations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='ItemsMismatchProductTypeInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Items Mismatch Product Type',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='ItemsMissingMandatoryInformationInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Items Missing Mandatory Information',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='MissingEanCodeInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing EAN Code',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='MissingLeadTimeInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Lead Time',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='MissingManualPriceListOverrideInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Manual Price List Override',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='MissingOptionalPropertiesInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Optional Properties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='MissingProductTypeInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Product Type',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='MissingRequiredPropertiesInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Required Properties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='MissingStockInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Stock',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='MissingSupplierPricesInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Missing Supplier Prices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='NonConfigurableRuleInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Non-Configurable Rule',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='VariationMismatchProductTypeInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Variation Mismatch Product Type',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.CreateModel(
            name='VariationsMissingMandatoryInformationInspectorBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Inspector Block Variations Missing Mandatory Information',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_inspector.inspectorblock',),
        ),
        migrations.AlterField(
            model_name='inspectorblock',
            name='error_code',
            field=models.IntegerField(choices=[(101, 'Product is missing required images'), (102, 'Product Missing Prices'), (103, 'Manufacturable Product has inactive bill of materials'), (104, 'Bundle Product has inactive items'), (105, 'Product is missing required variations'), (106, 'Bundle product is missing items'), (107, 'Manufacturable product is missing bill of materials'), (108, 'Product is missing supplier products'), (109, 'Product is missing an EAN code'), (110, 'Product is missing a required product type property'), (111, 'Product is missing required properties'), (112, 'Product is missing optional properties'), (113, 'Supplier product is missing required prices'), (114, 'Product is active, missing stock, and does not allow backorder'), (115, 'Product is missing lead time when out of stock'), (116, 'Manual price list price should have at least override price'), (117, 'Variations do not have the same product type'), (118, 'Items do not have the same product type'), (119, 'Bill of materials do not have the same product type'), (120, 'Items have inspectors missing mandatory information'), (121, 'Variations have inspectors missing mandatory information'), (122, 'Bill of materials have inspectors missing mandatory information'), (123, 'Configurable product has duplicate variations'), (124, 'Configurable product has no applicable configurator rules')]),
        ),
    ]
