# Generated by Django 5.2 on 2025-07-01 00:00

from django.db import migrations


def delete_error_code_118_blocks(apps, schema_editor):
    InspectorBlock = apps.get_model('products_inspector', 'InspectorBlock')
    InspectorBlock.objects.filter(error_code=118).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products_inspector', '0002_delete_itemsmismatchproducttypeinspectorblock_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_error_code_118_blocks, reverse_code=migrations.RunPython.noop),
    ]
