# Generated by Django 5.2 on 2025-07-19 08:45

from django.db import migrations

def update_has_images_block(apps, schema_editor):
    InspectorBlock = apps.get_model('products_inspector', 'InspectorBlock')
    from products_inspector.constants import HAS_IMAGES_ERROR, REQUIRED
    InspectorBlock.objects.filter(error_code=HAS_IMAGES_ERROR).update(
        simple_product_applicability=REQUIRED,
        configurable_product_applicability=REQUIRED,
        manufacturable_product_applicability=REQUIRED,
        bundle_product_applicability=REQUIRED,
        dropship_product_applicability=REQUIRED,
        supplier_product_applicability=REQUIRED,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products_inspector', '0003_delete_error_code_118'),
    ]

    operations = [
        migrations.RunPython(update_has_images_block, reverse_code=migrations.RunPython.noop),
    ]
