# Generated by Django 5.1.1 on 2025-02-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_inspector', '0005_delete_missingsupplierpricesinspectorblock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BomMismatchProductTypeInspectorBlock',
        ),
        migrations.DeleteModel(
            name='BomMissingMandatoryInformationInspectorBlock',
        ),
        migrations.DeleteModel(
            name='InspectorBlockInactivePieces',
        ),
        migrations.DeleteModel(
            name='InspectorBlockMissingBillOfMaterials',
        ),
        migrations.DeleteModel(
            name='InspectorBlockMissingSupplierProducts',
        ),
        migrations.DeleteModel(
            name='MissingLeadTimeInspectorBlock',
        ),
        migrations.DeleteModel(
            name='MissingSupplierPriceInspectorBlock',
        ),
        migrations.AlterField(
            model_name='inspectorblock',
            name='error_code',
            field=models.IntegerField(choices=[(101, 'Product is missing required images'), (102, 'Product Missing Prices'), (104, 'Bundle Product has inactive items'), (105, 'Product is missing required variations'), (106, 'Bundle product is missing items'), (109, 'Product is missing an EAN code'), (110, 'Product is missing a required product type property'), (111, 'Product is missing required properties'), (112, 'Product is missing optional properties'), (114, 'Product is active, missing stock, and does not allow backorder'), (116, 'Manual price list price should have at least override price'), (117, 'Variations do not have the same product type'), (118, 'Items do not have the same product type'), (120, 'Items have inspectors missing mandatory information'), (121, 'Variations have inspectors missing mandatory information'), (123, 'Configurable product has duplicate variations'), (124, 'Configurable product has no applicable configurator rules')]),
        ),
    ]
