# Generated by Django 5.2 on 2025-12-15

from django.db import migrations


def delete_amazon_issue_error_code_blocks(apps, schema_editor):
    InspectorBlock = apps.get_model("products_inspector", "InspectorBlock")
    InspectorBlock.objects.filter(error_code__in=[125, 126]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("products_inspector", "0006_delete_amazonremoteissuesinspectorblock_and_more"),
    ]

    operations = [
        migrations.RunPython(
            delete_amazon_issue_error_code_blocks,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

