# Generated by Django 5.2 on 2026-02-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_inspector', '0008_optionaldocumenttypesinspectorblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectorblock',
            name='error_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
