# Generated by Django 5.2 on 2026-02-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_inspector', '0009_inspectorblock_error_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectorblock',
            old_name='error_message',
            new_name='fixing_message',
        ),
    ]
