# Generated by Django 5.2 on 2025-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vatrate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vatrate',
            name='rate',
            field=models.IntegerField(blank=True, help_text='VAT rate in percent. Eg 21 for 21%', null=True),
        ),
    ]
