# Generated by Django 4.2.5 on 2023-09-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.IntegerField(help_text='Tax rate in percent.  Eg 21 for 21%'),
        ),
    ]
