# Generated by Django 5.0.2 on 2024-03-03 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_multitenantuser_timezone'),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='multi_tenant_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany'),
        ),
        migrations.AddField(
            model_name='tax',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
