# Generated by Django 5.0.2 on 2024-04-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0003_vatrate_delete_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatrate',
            name='name',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
