# Generated by Django 5.0.2 on 2024-04-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_multitenantuser_timezone'),
        ('taxes', '0004_alter_vatrate_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vatrate',
            unique_together={('rate', 'multi_tenant_company')},
        ),
    ]
