# Generated by Django 5.1.1 on 2025-03-07 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of task retries (between 1 and 20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
