# Generated by Django 5.1.1 on 2025-03-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integration_max_retries'),
        ('sales_channels', '0004_remoteproduct_syncing_current_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationlog',
            name='remote_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_channels.remoteproduct'),
        ),
    ]
