# Generated by Django 5.1.1 on 2025-03-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integrationlog_remote_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationlog',
            name='fixing_identifier',
            field=models.CharField(blank=True, help_text='Identifier used by a later log to indicate this error has been fixed.', max_length=255, null=True),
        ),
    ]
