# Generated by Django 5.1.1 on 2025-03-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_integrationlog_fixing_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='internal_company',
        ),
    ]
