# Generated by Django 5.2 on 2025-04-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_remove_integration_internal_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationtaskqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'),
                                   ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10),
        ),
    ]
