# Generated by Django 5.1.1 on 2024-10-18 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_alter_address_options_and_more'),
        ('integrations', '0005_alter_integrationlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='internal_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.company'),
        ),
    ]
