# Generated by Django 5.2 on 2025-06-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_alter_integration_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='hostname',
            field=models.CharField(help_text='Hostname or identifier for the integration (e.g. domain name or marketplace slug)', max_length=255),
        ),
    ]
