# Generated by Django 5.1.1 on 2024-10-18 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_alter_address_options_and_more'),
        ('integrations', '0007_populate_internal_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='internal_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.company'),
        ),
    ]
