# Generated by Django 5.2 on 2025-10-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_alter_integration_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationlog',
            name='related_object_str',
            field=models.CharField(blank=True, help_text='String representation of the related object.', max_length=1056, null=True),
        ),
    ]
