# Generated by Django 5.2 on 2026-03-12 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_alter_integrationlog_related_object_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicIntegrationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('subtype', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('storefront', 'Storefront'), ('marketplace', 'Marketplace'), ('webhooks', 'Webhooks')], db_index=True, max_length=32)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('is_beta', models.BooleanField(db_index=True, default=False)),
                ('supports_open_ai_product_feed', models.BooleanField(db_index=True, default=False)),
                ('logo_png', models.ImageField(blank=True, null=True, upload_to='integrations/public/logo_png/')),
                ('logo_svg', models.FileField(blank=True, null=True, upload_to='integrations/public/logo_svg/')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('based_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_integration_types', to='integrations.publicintegrationtype')),
            ],
            options={
                'ordering': ('sort_order', 'key'),
            },
        ),
        migrations.CreateModel(
            name='PublicIntegrationTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('nl', 'Dutch'), ('de', 'German'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pl', 'Polish'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('et', 'Estonian'), ('fi', 'Finnish'), ('el', 'Greek'), ('hu', 'Hungarian'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('th', 'Thai'), ('ja', 'Japanese'), ('zh-hans', 'Chinese (Simplified)'), ('hi', 'Hindi'), ('pt-br', 'Portuguese (Brazil)'), ('ru', 'Russian'), ('af', 'Afrikaans'), ('ar', 'Arabic'), ('he', 'Hebrew'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('ko', 'Korean'), ('ms', 'Malay'), ('vi', 'Vietnamese'), ('fa', 'Persian'), ('ur', 'Urdu')], db_index=True, default='en', max_length=7)),
                ('public_integration_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='integrations.publicintegrationtype')),
            ],
            options={
                'ordering': ('language', 'name'),
                'constraints': [models.UniqueConstraint(fields=('public_integration_type', 'language'), name='unique_public_integration_type_translation_language')],
            },
        ),
    ]
