from urllib.request import Request, urlopen

from django.core.files.base import ContentFile
from django.db import migrations

from sales_channels.integrations.mirakl.sub_type_constants import (
    DEFAULT_MIRAKL_SUB_TYPE,
    MIRAKL_SUB_TYPE_CHOICES,
)


APP_LABEL = "integrations"
DEFAULT_LANGUAGE = "en"


MIRAKL_LOGO_URLS = {
    "1800flowers-prod": "https://1800flowers-prod.mirakl.net/media/operator-interface-logo",
    "abb-prod": "https://abb-prod.mirakl.net/media/operator-interface-logo",
    "abbindia-prod": "https://abbindia-prod.mirakl.net/media/operator-interface-logo",
    "abbsa-prod": "https://abbsa-prod.mirakl.net/media/operator-interface-logo",
    "accor-prod": "https://accor-prod.mirakl.net/media/operator-interface-logo",
    "ahlens-prod": "https://ahlens-prod.mirakl.net/media/operator-interface-logo",
    "airbus-prod": "https://airbus-prod.mirakl.net/media/operator-interface-logo",
    "alltricks-prod": "https://alltricks-prod.mirakl.net/media/operator-interface-logo",
    "altitudesportsca-prod": "https://altitudesportsca-prod.mirakl.net/media/operator-interface-logo",
    "altitudesports-prod": "https://altitudesports-prod.mirakl.net/media/operator-interface-logo",
    "amerisourcebergenus-prod": "https://amerisourcebergenus-prod.mirakl.net/media/operator-interface-logo",
    "aniel-prod": "https://aniel-prod.mirakl.net/media/operator-interface-logo",
    "anwbnl-prod": "https://anwbnl-prod.mirakl.net/media/operator-interface-logo",
    "auchan-prod": "https://auchan-prod.mirakl.net/media/operator-interface-logo",
    "autodocde-prod": "https://autodocde-prod.mirakl.net/media/operator-interface-logo",
    "babybuntingau-prod": "https://babybuntingau-prod.mirakl.net/media/operator-interface-logo",
    "bancobradescobr2-prod": "https://bancobradescobr2-prod.mirakl.net/media/operator-interface-logo",
    "bauhausde-prod": "https://bauhausde-prod.mirakl.net/media/operator-interface-logo",
    "bazarchicfr-prod": "https://bazarchicfr-prod.mirakl.net/media/operator-interface-logo",
    "beerwulfnl-prod": "https://beerwulfnl-prod.mirakl.net/media/operator-interface-logo",
    "bestbuyus-prod": "https://bestbuyus-prod.mirakl.net/media/operator-interface-logo",
    "bestsecret-prod": "https://bestsecret-prod.mirakl.net/media/operator-interface-logo",
    "blackredwhitepl-prod": "https://blackredwhitepl-prod.mirakl.net/media/operator-interface-logo",
    "bloomingdalesus-prod": "https://bloomingdalesus-prod.mirakl.net/media/operator-interface-logo",
    "bluediamondgrowersus-prod": "https://bluediamondgrowersus-prod.mirakl.net/media/operator-interface-logo",
    "bobsdiscount-prod": "https://bobsdiscount-prod.mirakl.net/media/operator-interface-logo",
    "middleton-prod": "https://middleton-prod.mirakl.net/media/operator-interface-logo",
    "debenhamsuk-prod": "https://debenhamsuk-prod.mirakl.net/media/operator-interface-logo",
    "blg-prod": "https://blg-prod.mirakl.net/media/operator-interface-logo",
    "bandquk-prod": "https://bandquk-prod.mirakl.net/media/operator-interface-logo",
    "brandalleyuk-prod": "https://brandalleyuk-prod.mirakl.net/media/operator-interface-logo",
    "bricodepotes-prod": "https://bricodepotes-prod.mirakl.net/media/operator-interface-logo",
    "bricomarchefr-prod": "https://bricomarchefr-prod.mirakl.net/media/operator-interface-logo",
    "bricoprive-prod": "https://bricoprive-prod.mirakl.net/media/operator-interface-logo",
    "brutschrueggerch-prod": "https://brutschrueggerch-prod.mirakl.net/media/operator-interface-logo",
    "zarppaloes-prod": "https://zarppaloes-prod.mirakl.net/media/operator-interface-logo",
    "bunnings-prod": "https://bunnings-prod.mirakl.net/media/operator-interface-logo",
    "bunzlnl-prod": "https://bunzlnl-prod.mirakl.net/media/operator-interface-logo",
    "businessfrance-prod": "https://businessfrance-prod.mirakl.net/media/operator-interface-logo",
    "but-prod": "https://but-prod.mirakl.net/media/operator-interface-logo",
    "canadapostca-prod": "https://canadapostca-prod.mirakl.net/media/operator-interface-logo",
    "carrefourfr-prod": "https://carrefourfr-prod.mirakl.net/media/operator-interface-logo",
    "carrefoures-prod": "https://carrefoures-prod.mirakl.net/media/operator-interface-logo",
    "carrierus-prod": "https://carrierus-prod.mirakl.net/media/operator-interface-logo",
    "casadellibro-prod": "https://casadellibro-prod.mirakl.net/media/operator-interface-logo",
    "castoramafr-prod": "https://castoramafr-prod.mirakl.net/media/operator-interface-logo",
    "centralgroup-prod": "https://centralgroup-prod.mirakl.net/media/operator-interface-logo",
    "chalhoubae-prod": "https://chalhoubae-prod.mirakl.net/media/operator-interface-logo",
    "cheneyus-prod": "https://cheneyus-prod.mirakl.net/media/operator-interface-logo",
    "chr-prod": "https://chr-prod.mirakl.net/media/operator-interface-logo",
    "clubefashionpt-prod": "https://clubefashionpt-prod.mirakl.net/media/operator-interface-logo",
    "conforama-prod": "https://conforama-prod.mirakl.net/media/operator-interface-logo",
    "conforamaes-prod": "https://conforamaes-prod.mirakl.net/media/operator-interface-logo",
    "conradb2b-prod": "https://conradb2b-prod.mirakl.net/media/operator-interface-logo",
    "rein-prod": "https://rein-prod.mirakl.net/media/operator-interface-logo",
    "coperama-prod": "https://coperama-prod.mirakl.net/media/operator-interface-logo",
    "coppel-prod": "https://coppel-prod.mirakl.net/media/operator-interface-logo",
    "countryroadgroupau-prod": "https://countryroadgroupau-prod.mirakl.net/media/operator-interface-logo",
    "culturafr-prod": "https://culturafr-prod.mirakl.net/media/operator-interface-logo",
    "cultura1pfr-prod": "https://cultura1pfr-prod.mirakl.net/media/operator-interface-logo",
    "axelspringerde-prod": "https://axelspringerde-prod.mirakl.net/media/operator-interface-logo",
    "decathlonau-prod": "https://decathlonau-prod.mirakl.net/media/operator-interface-logo",
    "decathlonbelgium2-prod": "https://decathlonbelgium2-prod.mirakl.net/media/operator-interface-logo",
    "decathlonhk-prod": "https://decathlonhk-prod.mirakl.net/media/operator-interface-logo",
    "decathlonin-prod": "https://decathlonin-prod.mirakl.net/media/operator-interface-logo",
    "decathlontw-prod": "https://decathlontw-prod.mirakl.net/media/operator-interface-logo",
    "decathlontr-prod": "https://decathlontr-prod.mirakl.net/media/operator-interface-logo",
    "fressnapfde2-prod": "https://fressnapfde2-prod.mirakl.net/media/operator-interface-logo",
    "home24de-prod": "https://home24de-prod.mirakl.net/media/operator-interface-logo",
    "obide-prod": "https://obide-prod.mirakl.net/media/operator-interface-logo",
    "popkenfashionde-prod": "https://popkenfashionde-prod.mirakl.net/media/operator-interface-logo",
    "diastylingus-prod": "https://diastylingus-prod.mirakl.net/media/operator-interface-logo",
    "digitalareagroupge-prod": "https://digitalareagroupge-prod.mirakl.net/media/operator-interface-logo",
    "dotzbr-prod": "https://dotzbr-prod.mirakl.net/media/operator-interface-logo",
    "douglas-prod": "https://douglas-prod.mirakl.net/media/operator-interface-logo",
    "dpgmedianl-prod": "https://dpgmedianl-prod.mirakl.net/media/operator-interface-logo",
    "drivenbrandsus-prod": "https://drivenbrandsus-prod.mirakl.net/media/operator-interface-logo",
    "drmaxcz-prod": "https://drmaxcz-prod.mirakl.net/media/operator-interface-logo",
    "eczacibasitr-prod": "https://eczacibasitr-prod.mirakl.net/media/operator-interface-logo",
    "eiffagefr-prod": "https://eiffagefr-prod.mirakl.net/media/operator-interface-logo",
    "eci-prod": "https://eci-prod.mirakl.net/media/operator-interface-logo",
    "elkjop-prod": "https://elkjop-prod.mirakl.net/media/operator-interface-logo",
    "ellos-prod": "https://ellos-prod.mirakl.net/media/operator-interface-logo",
    "empik-prod": "https://empik-prod.mirakl.net/media/operator-interface-logo",
    "enbasisus-prod": "https://enbasisus-prod.mirakl.net/media/operator-interface-logo",
    "epc-prod": "https://epc-prod.mirakl.net/media/operator-interface-logo",
    "etisalatuae-prod": "https://etisalatuae-prod.mirakl.net/media/operator-interface-logo",
    "euronicsuk-prod": "https://euronicsuk-prod.mirakl.net/media/operator-interface-logo",
    "exelon-prod": "https://exelon-prod.mirakl.net/media/operator-interface-logo",
    "unitedelectionicssa-prod": "https://unitedelectionicssa-prod.mirakl.net/media/operator-interface-logo",
    "fanaticsus-prod": "https://fanaticsus-prod.mirakl.net/media/operator-interface-logo",
    "farmaciasdelahorromx-prod": "https://farmaciasdelahorromx-prod.mirakl.net/media/operator-interface-logo",
    "fedexus-prod": "https://fedexus-prod.mirakl.net/media/operator-interface-logo",
    "fergusonus-prod": "https://fergusonus-prod.mirakl.net/media/operator-interface-logo",
    "fnac-prod": "https://fnac-prod.mirakl.net/media/operator-interface-logo",
    "fonq-prod": "https://fonq-prod.mirakl.net/media/operator-interface-logo",
    "fossilus-prod": "https://fossilus-prod.mirakl.net/media/operator-interface-logo",
    "fossilus3-prod": "https://fossilus3-prod.mirakl.net/media/operator-interface-logo",
    "freedomau-prod": "https://freedomau-prod.mirakl.net/media/operator-interface-logo",
    "freeleacorpus-prod": "https://freeleacorpus-prod.mirakl.net/media/operator-interface-logo",
    "freemansuk-prod": "https://freemansuk-prod.mirakl.net/media/operator-interface-logo",
    "gacdfr-prod": "https://gacdfr-prod.mirakl.net/media/operator-interface-logo",
    "galeriainnobe-prod": "https://galeriainnobe-prod.mirakl.net/media/operator-interface-logo",
    "galeriakarstadtkaufhofgmbhde-prod": "https://galeriakarstadtkaufhofgmbhde-prod.mirakl.net/media/operator-interface-logo",
    "galerieslafayette-prod": "https://galerieslafayette-prod.mirakl.net/media/operator-interface-logo",
    "generalelectricus-prod": "https://generalelectricus-prod.mirakl.net/media/operator-interface-logo",
    "globalbrands-prod": "https://globalbrands-prod.mirakl.net/media/operator-interface-logo",
    "gpa-prod": "https://gpa-prod.mirakl.net/media/operator-interface-logo",
    "grandsmoulinsdeparisfr-prod": "https://grandsmoulinsdeparisfr-prod.mirakl.net/media/operator-interface-logo",
    "graybarus-prod": "https://graybarus-prod.mirakl.net/media/operator-interface-logo",
    "greenweezfr-prod": "https://greenweezfr-prod.mirakl.net/media/operator-interface-logo",
    "neumaticosandreses-prod": "https://neumaticosandreses-prod.mirakl.net/media/operator-interface-logo",
    "grupodistelsagt-prod": "https://grupodistelsagt-prod.mirakl.net/media/operator-interface-logo",
    "eroskies-prod": "https://eroskies-prod.mirakl.net/media/operator-interface-logo",
    "hankyuhanshinjp-prod": "https://hankyuhanshinjp-prod.mirakl.net/media/operator-interface-logo",
    "happytal-prod": "https://happytal-prod.mirakl.net/media/operator-interface-logo",
    "harveynormanau-prod": "https://harveynormanau-prod.mirakl.net/media/operator-interface-logo",
    "haweskode-prod": "https://haweskode-prod.mirakl.net/media/operator-interface-logo",
    "hearstecommerceus-prod": "https://hearstecommerceus-prod.mirakl.net/media/operator-interface-logo",
    "tdscus-prod": "https://tdscus-prod.mirakl.net/media/operator-interface-logo",
    "tdscus2-prod": "https://tdscus2-prod.mirakl.net/media/operator-interface-logo",
    "hmhome-prod": "https://hmhome-prod.mirakl.net/media/operator-interface-logo",
    "hennesmauritz-prod": "https://hennesmauritz-prod.mirakl.net/media/operator-interface-logo",
    "hmgrouppb-prod": "https://hmgrouppb-prod.mirakl.net/media/operator-interface-logo",
    "holtrenfrewca-prod": "https://holtrenfrewca-prod.mirakl.net/media/operator-interface-logo",
    "homemakerfurnitureus-prod": "https://homemakerfurnitureus-prod.mirakl.net/media/operator-interface-logo",
    "bbkpl-prod": "https://bbkpl-prod.mirakl.net/media/operator-interface-logo",
    "hornbachde-prod": "https://hornbachde-prod.mirakl.net/media/operator-interface-logo",
    "hygide-prod": "https://hygide-prod.mirakl.net/media/operator-interface-logo",
    "ibs-prod": "https://ibs-prod.mirakl.net/media/operator-interface-logo",
    "ipagencyfi-prod": "https://ipagencyfi-prod.mirakl.net/media/operator-interface-logo",
    "irisjp-prod": "https://irisjp-prod.mirakl.net/media/operator-interface-logo",
    "janieandjackus1-prod": "https://janieandjackus1-prod.mirakl.net/media/operator-interface-logo",
    "jarirsa-prod": "https://jarirsa-prod.mirakl.net/media/operator-interface-logo",
    "jbhifiau-prod": "https://jbhifiau-prod.mirakl.net/media/operator-interface-logo",
    "jcbuk-prod": "https://jcbuk-prod.mirakl.net/media/operator-interface-logo",
    "jcpenneyus-prod": "https://jcpenneyus-prod.mirakl.net/media/operator-interface-logo",
    "jcrew-prod": "https://jcrew-prod.mirakl.net/media/operator-interface-logo",
    "jdsportsuk-prod": "https://jdsportsuk-prod.mirakl.net/media/operator-interface-logo",
    "bankofcypruscy-prod": "https://bankofcypruscy-prod.mirakl.net/media/operator-interface-logo",
    "joezzfr-prod": "https://joezzfr-prod.mirakl.net/media/operator-interface-logo",
    "johnlewisuk-prod": "https://johnlewisuk-prod.mirakl.net/media/operator-interface-logo",
    "kabum-prod": "https://kabum-prod.mirakl.net/media/operator-interface-logo",
    "karacatr-prod": "https://karacatr-prod.mirakl.net/media/operator-interface-logo",
    "kiabifr-prod": "https://kiabifr-prod.mirakl.net/media/operator-interface-logo",
    "kmartau-prod": "https://kmartau-prod.mirakl.net/media/operator-interface-logo",
    "koctastr-prod": "https://koctastr-prod.mirakl.net/media/operator-interface-logo",
    "kofolacz-prod": "https://kofolacz-prod.mirakl.net/media/operator-interface-logo",
    "kohlsus-prod": "https://kohlsus-prod.mirakl.net/media/operator-interface-logo",
    "krisshopsg-prod": "https://krisshopsg-prod.mirakl.net/media/operator-interface-logo",
    "kruidvatnl1-prod": "https://kruidvatnl1-prod.mirakl.net/media/operator-interface-logo",
    "landersph-prod": "https://landersph-prod.mirakl.net/media/operator-interface-logo",
    "laposte-prod": "https://laposte-prod.mirakl.net/media/operator-interface-logo",
    "laredoutefr-prod": "https://laredoutefr-prod.mirakl.net/media/operator-interface-logo",
    "ldlc-prod": "https://ldlc-prod.mirakl.net/media/operator-interface-logo",
    "lebeauxus-prod": "https://lebeauxus-prod.mirakl.net/media/operator-interface-logo",
    "leclerc-prod": "https://leclerc-prod.mirakl.net/media/operator-interface-logo",
    "leenbakker-prod": "https://leenbakker-prod.mirakl.net/media/operator-interface-logo",
    "leonardoit-prod": "https://leonardoit-prod.mirakl.net/media/operator-interface-logo",
    "leroymerlinbr-prod": "https://leroymerlinbr-prod.mirakl.net/media/operator-interface-logo",
    "leroymerlinfr-prod": "https://leroymerlinfr-prod.mirakl.net/media/operator-interface-logo",
    "leroymerlinza-prod": "https://leroymerlinza-prod.mirakl.net/media/operator-interface-logo",
    "limangode-prod": "https://limangode-prod.mirakl.net/media/operator-interface-logo",
    "livingspacefurnitureus-prod": "https://livingspacefurnitureus-prod.mirakl.net/media/operator-interface-logo",
    "lowesus-prod": "https://lowesus-prod.mirakl.net/media/operator-interface-logo",
    "secretsales-prod": "https://secretsales-prod.mirakl.net/media/operator-interface-logo",
    "emgroupde-prod": "https://emgroupde-prod.mirakl.net/media/operator-interface-logo",
    "lyrecofr-prod": "https://lyrecofr-prod.mirakl.net/media/operator-interface-logo",
    "macway-prod": "https://macway-prod.mirakl.net/media/operator-interface-logo",
    "macysus-prod": "https://macysus-prod.mirakl.net/media/operator-interface-logo",
    "madewell-prod": "https://madewell-prod.mirakl.net/media/operator-interface-logo",
    "globusch-prod": "https://globusch-prod.mirakl.net/media/operator-interface-logo",
    "maisonette-prod": "https://maisonette-prod.mirakl.net/media/operator-interface-logo",
    "maisonsdumonde-prod": "https://maisonsdumonde-prod.mirakl.net/media/operator-interface-logo",
    "cadhifr-prod": "https://cadhifr-prod.mirakl.net/media/operator-interface-logo",
    "manor-prod": "https://manor-prod.mirakl.net/media/operator-interface-logo",
    "matalanuk-prod": "https://matalanuk-prod.mirakl.net/media/operator-interface-logo",
    "mathisbrothersus-prod": "https://mathisbrothersus-prod.mirakl.net/media/operator-interface-logo",
    "mathonfr-prod": "https://mathonfr-prod.mirakl.net/media/operator-interface-logo",
    "maty-prod": "https://maty-prod.mirakl.net/media/operator-interface-logo",
    "maxedanl-prod": "https://maxedanl-prod.mirakl.net/media/operator-interface-logo",
    "platformf-prod": "https://platformf-prod.mirakl.net/media/operator-interface-logo",
    "mediamarkt-prod": "https://mediamarkt-prod.mirakl.net/media/operator-interface-logo",
    "meijerus-prod": "https://meijerus-prod.mirakl.net/media/operator-interface-logo",
    "memoritz-prod": "https://memoritz-prod.mirakl.net/media/operator-interface-logo",
    "metcashau-prod": "https://metcashau-prod.mirakl.net/media/operator-interface-logo",
    "michelinus-prod": "https://michelinus-prod.mirakl.net/media/operator-interface-logo",
    "milliporesigmaus1-prod": "https://milliporesigmaus1-prod.mirakl.net/media/operator-interface-logo",
    "mintedus-prod": "https://mintedus-prod.mirakl.net/media/operator-interface-logo",
    "misterautofr-prod": "https://misterautofr-prod.mirakl.net/media/operator-interface-logo",
    "mmmegamarketvn-prod": "https://mmmegamarketvn-prod.mirakl.net/media/operator-interface-logo",
    "esm-prod": "https://esm-prod.mirakl.net/media/operator-interface-logo",
    "mobelhoffner-prod": "https://mobelhoffner-prod.mirakl.net/media/operator-interface-logo",
    "modaoperandius-prod": "https://modaoperandius-prod.mirakl.net/media/operator-interface-logo",
    "eobuwiepl-prod": "https://eobuwiepl-prod.mirakl.net/media/operator-interface-logo",
    "mondialtissusfr-prod": "https://mondialtissusfr-prod.mirakl.net/media/operator-interface-logo",
    "mountainwarehouseuk-prod": "https://mountainwarehouseuk-prod.mirakl.net/media/operator-interface-logo",
    "mtechnologiesus-prod": "https://mtechnologiesus-prod.mirakl.net/media/operator-interface-logo",
    "musgraveie-prod": "https://musgraveie-prod.mirakl.net/media/operator-interface-logo",
    "decathlonmy-prod": "https://decathlonmy-prod.mirakl.net/media/operator-interface-logo",
    "myerau-prod": "https://myerau-prod.mirakl.net/media/operator-interface-logo",
    "naturedecouverte-prod": "https://naturedecouverte-prod.mirakl.net/media/operator-interface-logo",
    "nbc-prod": "https://nbc-prod.mirakl.net/media/operator-interface-logo",
    "nitorijp-prod": "https://nitorijp-prod.mirakl.net/media/operator-interface-logo",
    "mediahuisnl-prod": "https://mediahuisnl-prod.mirakl.net/media/operator-interface-logo",
    "nordstromus-prod": "https://nordstromus-prod.mirakl.net/media/operator-interface-logo",
    "fairpricesg-prod": "https://fairpricesg-prod.mirakl.net/media/operator-interface-logo",
    "obelinknl-prod": "https://obelinknl-prod.mirakl.net/media/operator-interface-logo",
    "ocprepartitionfr-prod": "https://ocprepartitionfr-prod.mirakl.net/media/operator-interface-logo",
    "oitelecomunicacoesbr-prod": "https://oitelecomunicacoesbr-prod.mirakl.net/media/operator-interface-logo",
    "onlinemetalsus-prod": "https://onlinemetalsus-prod.mirakl.net/media/operator-interface-logo",
    "orangefr-prod": "https://orangefr-prod.mirakl.net/media/operator-interface-logo",
    "orangees-prod": "https://orangees-prod.mirakl.net/media/operator-interface-logo",
    "orientaltradingus-prod": "https://orientaltradingus-prod.mirakl.net/media/operator-interface-logo",
    "elpalaciodehierrous-prod": "https://elpalaciodehierrous-prod.mirakl.net/media/operator-interface-logo",
    "paramountliquorau-prod": "https://paramountliquorau-prod.mirakl.net/media/operator-interface-logo",
    "partstown-prod": "https://partstown-prod.mirakl.net/media/operator-interface-logo",
    "paybackde-prod": "https://paybackde-prod.mirakl.net/media/operator-interface-logo",
    "pccomponentes-prod": "https://pccomponentes-prod.mirakl.net/media/operator-interface-logo",
    "phoenixpharmait-prod": "https://phoenixpharmait-prod.mirakl.net/media/operator-interface-logo",
    "phonehousespain-prod": "https://phonehousespain-prod.mirakl.net/media/operator-interface-logo",
    "kaselu-prod": "https://kaselu-prod.mirakl.net/media/operator-interface-logo",
    "placedestendancesfr-prod": "https://placedestendancesfr-prod.mirakl.net/media/operator-interface-logo",
    "greenweezfr2-prod": "https://greenweezfr2-prod.mirakl.net/media/operator-interface-logo",
    "castoramapl-prod": "https://castoramapl-prod.mirakl.net/media/operator-interface-logo",
    "printempsfr-prod": "https://printempsfr-prod.mirakl.net/media/operator-interface-logo",
    "privaliamx1-prod": "https://privaliamx1-prod.mirakl.net/media/operator-interface-logo",
    "privatesportshopfr-prod": "https://privatesportshopfr-prod.mirakl.net/media/operator-interface-logo",
    "proudlymarketus-prod": "https://proudlymarketus-prod.mirakl.net/media/operator-interface-logo",
    "publicgr-prod": "https://publicgr-prod.mirakl.net/media/operator-interface-logo",
    "purchasingpowerus-prod": "https://purchasingpowerus-prod.mirakl.net/media/operator-interface-logo",
    "pyramydairus-prod": "https://pyramydairus-prod.mirakl.net/media/operator-interface-logo",
    "quirumedes-prod": "https://quirumedes-prod.mirakl.net/media/operator-interface-logo",
    "raymourflaniganus-prod": "https://raymourflaniganus-prod.mirakl.net/media/operator-interface-logo",
    "reachsharedservicesgb-prod": "https://reachsharedservicesgb-prod.mirakl.net/media/operator-interface-logo",
    "reemmallae-prod": "https://reemmallae-prod.mirakl.net/media/operator-interface-logo",
    "restaurantdepotus-prod": "https://restaurantdepotus-prod.mirakl.net/media/operator-interface-logo",
    "rtf-prod": "https://rtf-prod.mirakl.net/media/operator-interface-logo",
    "ripley-prod": "https://ripley-prod.mirakl.net/media/operator-interface-logo",
    "ripleyperu-prod": "https://ripleyperu-prod.mirakl.net/media/operator-interface-logo",
    "rogersca-prod": "https://rogersca-prod.mirakl.net/media/operator-interface-logo",
    "romanoriginalsuk-prod": "https://romanoriginalsuk-prod.mirakl.net/media/operator-interface-logo",
    "royalcaribbeanus-prod": "https://royalcaribbeanus-prod.mirakl.net/media/operator-interface-logo",
    "iph-prod": "https://iph-prod.mirakl.net/media/operator-interface-logo",
    "rueducommerce-prod": "https://rueducommerce-prod.mirakl.net/media/operator-interface-logo",
    "sainsburyuk-prod": "https://sainsburyuk-prod.mirakl.net/media/operator-interface-logo",
    "saksus-prod": "https://saksus-prod.mirakl.net/media/operator-interface-logo",
    "saloncentricus-prod": "https://saloncentricus-prod.mirakl.net/media/operator-interface-logo",
    "sapporojp-prod": "https://sapporojp-prod.mirakl.net/media/operator-interface-logo",
    "sarenza-prod": "https://sarenza-prod.mirakl.net/media/operator-interface-logo",
    "satair-prod": "https://satair-prod.mirakl.net/media/operator-interface-logo",
    "shopapothekege-prod": "https://shopapothekege-prod.mirakl.net/media/operator-interface-logo",
    "simonproperty2-prod": "https://simonproperty2-prod.mirakl.net/media/operator-interface-logo",
    "showroomprive-prod": "https://showroomprive-prod.mirakl.net/media/operator-interface-logo",
    "showroomprivefr2-prod": "https://showroomprivefr2-prod.mirakl.net/media/operator-interface-logo",
    "siammakroth-prod": "https://siammakroth-prod.mirakl.net/media/operator-interface-logo",
    "bigbangmarketplacesi-prod": "https://bigbangmarketplacesi-prod.mirakl.net/media/operator-interface-logo",
    "sigmasportsuk-prod": "https://sigmasportsuk-prod.mirakl.net/media/operator-interface-logo",
    "snappygiftsus-prod": "https://snappygiftsus-prod.mirakl.net/media/operator-interface-logo",
    "sokfi-prod": "https://sokfi-prod.mirakl.net/media/operator-interface-logo",
    "somethingnavy-prod": "https://somethingnavy-prod.mirakl.net/media/operator-interface-logo",
    "soneparit-prod": "https://soneparit-prod.mirakl.net/media/operator-interface-logo",
    "spotlightau-prod": "https://spotlightau-prod.mirakl.net/media/operator-interface-logo",
    "sprinter-prod": "https://sprinter-prod.mirakl.net/media/operator-interface-logo",
    "stadiumse-prod": "https://stadiumse-prod.mirakl.net/media/operator-interface-logo",
    "stepupforstudentsus-prod": "https://stepupforstudentsus-prod.mirakl.net/media/operator-interface-logo",
    "stihlus-prod": "https://stihlus-prod.mirakl.net/media/operator-interface-logo",
    "superdrugnl-prod": "https://superdrugnl-prod.mirakl.net/media/operator-interface-logo",
    "superpharmpl-prod": "https://superpharmpl-prod.mirakl.net/media/operator-interface-logo",
    "superpharm-prod": "https://superpharm-prod.mirakl.net/media/operator-interface-logo",
    "syscous-prod": "https://syscous-prod.mirakl.net/media/operator-interface-logo",
    "teknosatr-prod": "https://teknosatr-prod.mirakl.net/media/operator-interface-logo",
    "teractfr-prod": "https://teractfr-prod.mirakl.net/media/operator-interface-logo",
    "tergpl-prod": "https://tergpl-prod.mirakl.net/media/operator-interface-logo",
    "tescouk-prod": "https://tescouk-prod.mirakl.net/media/operator-interface-logo",
    "decathlonth-prod": "https://decathlonth-prod.mirakl.net/media/operator-interface-logo",
    "hudsonsbayus-prod": "https://hudsonsbayus-prod.mirakl.net/media/operator-interface-logo",
    "homedepotus-prod": "https://homedepotus-prod.mirakl.net/media/operator-interface-logo",
    "knot-prod": "https://knot-prod.mirakl.net/media/operator-interface-logo",
    "middlebyus-prod": "https://middlebyus-prod.mirakl.net/media/operator-interface-logo",
    "therangeuk-prod": "https://therangeuk-prod.mirakl.net/media/operator-interface-logo",
    "tiendamiaus-prod": "https://tiendamiaus-prod.mirakl.net/media/operator-interface-logo",
    "tiendanimal-prod": "https://tiendanimal-prod.mirakl.net/media/operator-interface-logo",
    "tireagentus2-prod": "https://tireagentus2-prod.mirakl.net/media/operator-interface-logo",
    "totalplaymx-prod": "https://totalplaymx-prod.mirakl.net/media/operator-interface-logo",
    "tmhu-prod": "https://tmhu-prod.mirakl.net/media/operator-interface-logo",
    "tropicmarket-prod": "https://tropicmarket-prod.mirakl.net/media/operator-interface-logo",
    "tru-prod": "https://tru-prod.mirakl.net/media/operator-interface-logo",
    "twi-prod": "https://twi-prod.mirakl.net/media/operator-interface-logo",
    "decathlonua-prod": "https://decathlonua-prod.mirakl.net/media/operator-interface-logo",
    "ubaldi-prod": "https://ubaldi-prod.mirakl.net/media/operator-interface-logo",
    "ultaus-prod": "https://ultaus-prod.mirakl.net/media/operator-interface-logo",
    "unfius-prod": "https://unfius-prod.mirakl.net/media/operator-interface-logo",
    "unitedfarmersca-prod": "https://unitedfarmersca-prod.mirakl.net/media/operator-interface-logo",
    "urbanoutfitters-prod": "https://urbanoutfitters-prod.mirakl.net/media/operator-interface-logo",
    "venteunique-prod": "https://venteunique-prod.mirakl.net/media/operator-interface-logo",
    "verishopus-prod": "https://verishopus-prod.mirakl.net/media/operator-interface-logo",
    "verizonus-prod": "https://verizonus-prod.mirakl.net/media/operator-interface-logo",
    "vertbaudetfr-prod": "https://vertbaudetfr-prod.mirakl.net/media/operator-interface-logo",
    "velocityfrequentflyerau-prod": "https://velocityfrequentflyerau-prod.mirakl.net/media/operator-interface-logo",
    "virtualexpofr-prod": "https://virtualexpofr-prod.mirakl.net/media/operator-interface-logo",
    "watchfindergb-prod": "https://watchfindergb-prod.mirakl.net/media/operator-interface-logo",
    "watscous-prod": "https://watscous-prod.mirakl.net/media/operator-interface-logo",
    "westjapanrailwaycompanyjp-prod": "https://westjapanrailwaycompanyjp-prod.mirakl.net/media/operator-interface-logo",
    "whirlpoolus-prod": "https://whirlpoolus-prod.mirakl.net/media/operator-interface-logo",
    "wookpt-prod": "https://wookpt-prod.mirakl.net/media/operator-interface-logo",
    "worten-prod": "https://worten-prod.mirakl.net/media/operator-interface-logo",
    "wurthitinternational2-prod": "https://wurthitinternational2-prod.mirakl.net/media/operator-interface-logo",
    "yvesrocherfr-prod": "https://yvesrocherfr-prod.mirakl.net/media/operator-interface-logo",
    "zapgroupil-prod": "https://zapgroupil-prod.mirakl.net/media/operator-interface-logo",
    "zooplus-prod": "https://zooplus-prod.mirakl.net/media/operator-interface-logo",
}


def build_marketplace_description(*, name):
    return f"{name} integration to manage your marketplace listings."


def build_mirakl_logo_png_url(*, subtype):
    return MIRAKL_LOGO_URLS.get(subtype)


def fetch_remote_logo_png(*, logo_url):
    request = Request(logo_url, headers={"User-Agent": "OneSila/seed-public-integration-types"})
    with urlopen(request, timeout=15) as response:
        return response.read()


def maybe_seed_logo_png(*, public_integration_type, key, logo_url):
    if not logo_url or public_integration_type.logo_png:
        return

    try:
        content = fetch_remote_logo_png(logo_url=logo_url)
    except Exception:
        return

    public_integration_type.logo_png.save(f"{key}.png", ContentFile(content), save=True)


PUBLIC_INTEGRATION_TYPES = [
    {
        "key": "magento",
        "type": "magento",
        "subtype": None,
        "based_to_key": None,
        "category": "storefront",
        "active": True,
        "is_beta": False,
        "supports_open_ai_product_feed": True,
        "name": "Magento",
        "description": "Integrate with Magento to manage your online store seamlessly.",
    },
    {
        "key": "shopify",
        "type": "shopify",
        "subtype": None,
        "based_to_key": None,
        "category": "storefront",
        "active": True,
        "is_beta": False,
        "supports_open_ai_product_feed": True,
        "name": "Shopify",
        "description": "Shopify integration to manage your products in seconds.",
    },
    {
        "key": "woocommerce",
        "type": "woocommerce",
        "subtype": None,
        "based_to_key": None,
        "category": "storefront",
        "active": True,
        "is_beta": True,
        "supports_open_ai_product_feed": True,
        "name": "Woocommerce",
        "description": "WooCommerce integration to manage your products.",
    },
    {
        "key": "amazon",
        "type": "amazon",
        "subtype": None,
        "based_to_key": None,
        "category": "marketplace",
        "active": True,
        "is_beta": False,
        "supports_open_ai_product_feed": False,
        "name": "Amazon",
        "description": "Amazon integration to manage your marketplace listings.",
    },
    {
        "key": "ebay",
        "type": "ebay",
        "subtype": None,
        "based_to_key": None,
        "category": "marketplace",
        "active": True,
        "is_beta": False,
        "supports_open_ai_product_feed": False,
        "name": "Ebay",
        "description": "Ebay integration to manage your marketplace listings.",
    },
    {
        "key": "shein",
        "type": "shein",
        "subtype": None,
        "based_to_key": None,
        "category": "marketplace",
        "active": True,
        "is_beta": True,
        "supports_open_ai_product_feed": False,
        "name": "Shein",
        "description": "Shein integration to manage your marketplace listings.",
    },
    {
        "key": "mirakl",
        "type": "mirakl",
        "subtype": None,
        "based_to_key": None,
        "category": "marketplace",
        "active": True,
        "is_beta": True,
        "supports_open_ai_product_feed": False,
        "name": "Mirakl",
        "description": "Mirakl integration to connect OneSila with hundreds of marketplace channels from a single setup.",
        "logo_url": None,
    },
    {
        "key": "webhook",
        "type": "webhook",
        "subtype": None,
        "based_to_key": None,
        "category": "webhooks",
        "active": True,
        "is_beta": False,
        "supports_open_ai_product_feed": False,
        "name": "Webhook",
        "description": "Send events to your application via HTTP",
    },
] + [
    {
        "key": subtype,
        "type": "mirakl",
        "subtype": subtype,
        "based_to_key": DEFAULT_MIRAKL_SUB_TYPE,
        "category": "marketplace",
        "active": False,
        "is_beta": True,
        "supports_open_ai_product_feed": False,
        "name": name,
        "description": None,
        "logo_url": build_mirakl_logo_png_url(subtype=subtype),
    }
    for subtype, name in MIRAKL_SUB_TYPE_CHOICES
    if subtype != DEFAULT_MIRAKL_SUB_TYPE
]


def seed_public_integration_types(apps, schema_editor):
    PublicIntegrationType = apps.get_model(APP_LABEL, "PublicIntegrationType")
    PublicIntegrationTypeTranslation = apps.get_model(APP_LABEL, "PublicIntegrationTypeTranslation")

    created_by_key = {}

    for sort_order, item in enumerate(PUBLIC_INTEGRATION_TYPES, start=1):
        based_to = None
        if item["based_to_key"]:
            based_to = created_by_key[item["based_to_key"]]

        obj, _ = PublicIntegrationType.objects.update_or_create(
            key=item["key"],
            defaults={
                "type": item["type"],
                "subtype": item["subtype"],
                "based_to": based_to,
                "category": item["category"],
                "active": item["active"],
                "is_beta": item["is_beta"],
                "supports_open_ai_product_feed": item["supports_open_ai_product_feed"],
                "sort_order": sort_order,
            },
        )
        created_by_key[item["key"]] = obj
        maybe_seed_logo_png(
            public_integration_type=obj,
            key=item["key"],
            logo_url=item.get("logo_url"),
        )

        PublicIntegrationTypeTranslation.objects.update_or_create(
            public_integration_type=obj,
            language=DEFAULT_LANGUAGE,
            defaults={
                "name": item["name"],
                "description": item["description"] or build_marketplace_description(name=item["name"]),
            },
        )


def unseed_public_integration_types(apps, schema_editor):
    PublicIntegrationType = apps.get_model(APP_LABEL, "PublicIntegrationType")
    PublicIntegrationType.objects.filter(
        key__in=[item["key"] for item in PUBLIC_INTEGRATION_TYPES]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        (APP_LABEL, "0010_publicintegrationtype_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_public_integration_types, unseed_public_integration_types),
    ]
