# Generated by Django 5.2 on 2026-04-23 12:20

import core.models.core
import core.upload_paths
import core.validators
import dirtyfields.dirtyfields
import django.core.validators
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_multitenantcompany_language_and_more'),
        ('integrations', '0013_alter_publicintegrationtypetranslation_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Public issue code must be exactly 4 digits.', regex='^\\d{4}$')])),
                ('issue', models.TextField()),
                ('cause', models.TextField(blank=True, null=True)),
                ('recommended_fix', models.TextField(blank=True, null=True)),
                ('integration_type', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='public_issues', to='integrations.publicintegrationtype')),
            ],
            options={
                'ordering': ('integration_type__key', 'code'),
            },
        ),
        migrations.CreateModel(
            name='PublicIssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=functools.partial(core.upload_paths._tenant_upload_to, *(), **{'subdir': 'public_issue_images'}), validators=[core.validators.validate_image_extension, core.validators.no_dots_in_filename])),
                ('public_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='integrations.publicissue')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PublicIssueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('submission_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('product_sku', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('integration_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_issue_requests', to='integrations.publicintegrationtype')),
                ('last_update_by_multi_tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_update_by_multi_tenant_user_set', to=settings.AUTH_USER_MODEL)),
                ('multi_tenant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.multitenantcompany')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.core.GetAbsoluteURLMixin, models.Model),
        ),
        migrations.AddField(
            model_name='publicissue',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_issues', to='integrations.publicissuerequest'),
        ),
        migrations.CreateModel(
            name='PublicIssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('public_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='integrations.publicissue')),
            ],
            options={
                'ordering': ('name', 'code'),
                'constraints': [models.UniqueConstraint(fields=('public_issue', 'code'), name='unique_public_issue_category_code_per_issue')],
            },
        ),
    ]
