# Generated by Django 5.2 on 2026-04-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_publicissue_publicissueimage_publicissuerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicissue',
            name='integration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_issues', to='integrations.publicintegrationtype'),
        ),
    ]
