# Generated by Django 5.2 on 2026-04-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_alter_publicissue_integration_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicissue',
            name='request',
        ),
        migrations.AddField(
            model_name='publicissue',
            name='request_reference',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publicissuerequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], db_index=True, default='NEW', max_length=16),
        ),
    ]
